### PR TITLE
[14.0][MIG] purchase_requisition_tier_validation

### PR DESCRIPTION
**Pull request by aphon61bank**
add _tier_validation_manual_config = False.

### CODE REVIEW

**Comment by kittiu** [comment]
I took over this PR. Now ready for review.

**Comment by kittiu** [comment]
cc @ps-tubtim

**Review by ps-tubtim — APPROVED** [review]
Code LGTM

**Review by newtratip — APPROVED** [review]
Code Reviewed :+1:

**Review by kittiu — APPROVED** [review]

**Pull request merged**
