### PR TITLE
[MIG] purchase_order_line_deep_sort: Migration to 13.0

### PR DESCRIPTION
**Pull request by tonygalmiche**

### CODE REVIEW

**Review by bealdav — APPROVED** [review]
LGTM

**Comment by tonygalmiche** [comment]
Thank you @bealdav  for your review

**Review by HaraldPanten — APPROVED** [review]
Functional review LGTM

**Comment by tonygalmiche** [comment]
Thank you @HaraldPanten for your review

**Comment by HaraldPanten** [comment]
> Thank you @HaraldPanten for your review

Thanks for your contribution 👍

**Pull request merged**
