### PR TITLE
[10.0][FIX]purchase_request Remove failing domain

### PR DESCRIPTION
**Pull request by hparfr**
There is no type in analytic domain.

Step to reproduce: open a draft purchase request line, click on analytic account. You will get an error.

### CODE REVIEW

**Comment by hparfr** [comment]
@hveficent

**Review by HviorForgeFlow — APPROVED** [review]
@hparfr good catch! :smile:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by rvalyi — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
