### PR TITLE
[14.0][MIG] purchase_order_qty_change_no_recompute

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Standard Migration 13.0 => 14.0
https://github.com/OCA/purchase-workflow/tree/13.0/purchase_order_qty_change_no_recompute

@ForgeFlow

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
I think you should add commit history :)

**Comment by DavidJForgeFlow** [comment]
> I think you should add commit history :)

Done!

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks! LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
