### PR TITLE
[15.0][MIG] purchase_order_weight_volume: Migration to 15.0

### PR DESCRIPTION
**Pull request by vincent-cowboy**

### CODE REVIEW

**Review by leemannd — APPROVED** [review]

**Comment by leemannd** [comment]
Hello @HviorForgeFlow as you reviewed and merged the module in 14.0, maybe you have a little bit of time to help us here?

**Comment by leemannd** [comment]
Hello @ilyasProgrammer , your module is currently beeing migrated to 15.0 do you have time for a review?

**Review by ilyasProgrammer — APPROVED** [review]

**Review by tuantrantg — APPROVED** [review]
lgtm

**Pull request merged**
