### PR TITLE
[PORT][9.0] Port of prod_by_supplier

### PR DESCRIPTION
**Pull request by leemannd**
Port from 8.0 to 9.0. The commits done in 8.0 are included.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
It's working perfectly. You can squash all the "OCA Transbot" commits together.

**Comment by leemannd** [comment]
@pedrobaeza Hello, the commits have been squashed. :)

**Comment by yterrettaz** [comment]
:+1: I checked on runbot and it works at the functional level.

**Review by yterrettaz — APPROVED** [review]
I checked on runbot. It works.

**Comment by pedrobaeza** [comment]
We can merge this one as it has been doubled verified

**Pull request merged**
