### PR TITLE
[ADD] product_supplierinfo_for_customer_purchase

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Product Supplierinfo for Customers Purchase
===========================================

Glue module. Adds purchase manager permissions for customerinfo.

- [x] Depends of https://github.com/OCA/product-attribute/pull/515.

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
LGTM Functional. Please fix CI

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Comment by AaronHForgeFlow** [comment]
cc @hveficent

**Comment by MiquelRForgeFlow** [comment]
After some thought, It is determined to be not functionally useful.

**Pull request closed without merging**
