### PR TITLE
[13.0] [MIG] purchase_order_product_recommendation_classification: Migration to 13.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT31768

This is the migration of PR https://github.com/OCA/purchase-workflow/pull/1153

This module depends on:

- [x] https://github.com/OCA/product-attribute/pull/1013
- [x] https://github.com/OCA/product-attribute/pull/1015

please @chienandalu @pedrobaeza review this

### CODE REVIEW

**Comment by chienandalu** [comment]
Rebase :)

**Comment by CarlosRoca13** [comment]
Done @chienandalu

**Review by chienandalu — APPROVED** [review]
Tested :+1:

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
/ocabot merge nobump
/ocabot migration purchase_order_product_recommendation_classification

**Pull request merged**
