### PR TITLE
[14.0][IMP] purchase_order_approved: add approved orders filter

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Forwardport of https://github.com/OCA/purchase-workflow/pull/1239

### CODE REVIEW

**Review by AdriaGForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Ty!

**Review by AaronHForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
I have added a new change to allow cancelling approved orders. cc @AaronHForgeFlow @LoisRForgeFlow

**Comment by LoisRForgeFlow** [comment]
> I have added a new change to allow cancelling approved orders. cc @AaronHForgeFlow @LoisRForgeFlow

That one LGTM too.

**Pull request merged**
