### PR TITLE
[12.0][IMP] purchase_request: add button Create RFQ on purchase request for…

### PR DESCRIPTION
**Pull request by kos94ok-3D**
…m view

### CODE REVIEW

**Comment by kos94ok-3D** [comment]
Hi, @pedrobaeza .
Can you help me?
I don`t know what I have to do.

**Comment by pedrobaeza** [comment]
You can ping to the original authors of the module to see if they can review the PR.

**Comment by kos94ok-3D** [comment]
HI @aheficent.
Can you review this PR?

**Comment by HviorForgeFlow** [comment]
@kos94ok-3D can you cover improvements with tests? Thanks

**Comment by kos94ok-3D** [comment]
@hveficent enough?

**Comment by kos94ok-3D** [comment]
@hveficent Is it OK?

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
Thanks @kos94ok-3D for your contribution :)

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM :+1: Tested

**Pull request merged**
