### PR TITLE
[15.0][MIG]purchase_order_vendor_product

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/purchase-workflow/pull/1676

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre

**Review by HaraldPanten — APPROVED** [review]
LGTM @pedrobaeza

**Comment by pedrobaeza** [comment]
Isn't this the same as https://github.com/OCA/purchase-workflow/tree/14.0/purchase_allowed_product ?

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza 

Finally we'll work on this one --> https://github.com/OCA/purchase-workflow/pull/1725

As it is older than purchase_order_vendor_product and it has more functionallities, as well.

Should we close this PR, then? I think that it's not going to be longer needed.

THX!

**Comment by pedrobaeza** [comment]
Yes, closing it and putting a note in the existing module to warn about the duplication.

**Pull request closed without merging**
