### PR TITLE
[14.0][MIG] purchase_stock_tier_validation

### PR DESCRIPTION
**Pull request by bosd**
Standard migration, made with OCA [odoo-module-migrator](https://github.com/OCA/odoo-module-migrator)

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by bosd** [comment]
@etobella Can you please review?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
V15 in #1851

**Pull request merged**
