### PR TITLE
[ADD][14.0] purchase_order_payment_term_report

### PR DESCRIPTION
**Pull request by AshishHirapara**
initial commit: adds a Purchase payment term on PO report

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
functional review is ok!

**Review by SicurSam — APPROVED** [review]
functional review is ok!

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers good for merge?

**Comment by etobella** [comment]
Sorry to ask, but I don't understand the funcionality really well. Why do you need to hide/show the field according to PO? wouldn't have more sense to do this by partner or for all?

**Comment by francesco-ooops** [comment]
@etobella this module adds payment terms to report (if they're populated in PO) by default. 

Additionally, if user doesn't want to display payment terms in report for a specific PO, they can do so by deactivating the flag. 

Our customer does not need to have payment terms in report per customer, but should this need arise, the module can always be enhanced

**Comment by francesco-ooops** [comment]
@etobella what do you say? :)

**Comment by francesco-ooops** [comment]
@etobella @OCA/procurement-purchase-maintainers could you take a look again? Thank you

**Review by etobella — APPROVED** [review]

**Comment by francesco-ooops** [comment]
@etobella could you try again?

**Pull request merged**
