### PR TITLE
[14.0][ADD] purchase_vendor_bill_breakdown

### PR DESCRIPTION
**Pull request by geomer198**
This module offers a solution for the following scenario:

* We purchase a **Toolbox** product from a supplier
* Supplier delivers us the Toolbox but issues an invoice with **1x Box**, **2x Wrench**, **5x Screwdriver** and **1x Hammer** products in line

This module allows to replace a product in PO Line with a predefined set of components in the vendor bill line and also allows to calculate vendors product price by product components price.

(supersedes [#1562](https://github.com/OCA/purchase-workflow/pull/1562))

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
functional ok! 

this is the non-stock version (another PR is ready for storable product)

**Review by elvise — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers could you review?

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers gentle reminder :)

**Comment by francesco-ooops** [comment]
@rousseldenis could you provide an opinion? This PR comes from your comment here: https://github.com/OCA/purchase-workflow/pull/1547#issuecomment-1226898301

Thank you!

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers review request

**Pull request merged**
