### PR TITLE
[13.0][FIX] purchase_line_procurement_group: Greenify CI

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Following commit from @victoralmau 

CC @ForgeFlow @MiquelRForgeFlow

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
travis is red

**Comment by HviorForgeFlow** [comment]
> travis is red

any insight?

**Comment by pedrobaeza** [comment]
Any progress on this?

**Comment by HviorForgeFlow** [comment]
no @pedrobaeza, I couldn't figure out why test are failing, I can't reproduce it in local environments

**Comment by victoralmau** [comment]
In my opinion, this error appears since the change https://github.com/odoo/odoo/commit/006ab22aae0e6d8e9bd88d827282d6755f808cf0

**Comment by pedrobaeza** [comment]
Superseded by #1234

**Pull request closed without merging**
