### PR TITLE
[13.0][MIG] purchase_open_qty

### PR DESCRIPTION
**Pull request by kittiu**
Standard migration

### CODE REVIEW

**Comment by kittiu** [comment]
Ready for review.

**Comment by JordiBForgeFlow** [comment]
@hveficent

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Functional review :+1: 
Code review hard to do with 1 commit for black and migration.
Travis :red_circle:

**Comment by kittiu** [comment]
Yes, I am trying to see it. Do you know why?
On my local, it seem ok.
image

**Comment by kittiu** [comment]
> Code review hard to do with 1 commit for black and migration

IC. So you think we (always) should have 2 commits for v13 ?

**Comment by MiquelRForgeFlow** [comment]
@sbidoul can you help @kittiu about what's wrong with travis and how to solve it?

**Comment by sbidoul** [comment]
@kittiu @mreficent you can see the reason of the travis error in the diff at the end of the log: it tries to modify `.isort.cfg`. If you run `pre-commit run -a` locally it should do the same and you can commit the change.

> think we (always) should have 2 commits for v13 ?

It is important to have a separate commit *the first time* you run `pre-commit` on an existing code base, to isolate that massive automated change from any other manual change. After that, it becomes part of the normal workflow and it becomes part of regular commits.

**Comment by kittiu** [comment]
@hveficent @mreficent commit split, now ready for final review/merge.
Thanks!

**Review by HviorForgeFlow — APPROVED** [review]
Functional review :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
