### PR TITLE
[9.0][purchase_location_by_line] Fixes error when picking is created

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Prior to this fix users were required to manually enter the destination location in all the PO lines. Otherwise an error would occur at the time of creating the picking.

Extended the test cases to cover the changes made.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@mreficent, @lreficent, @gmeficent can you review?

**Review by MiquelRForgeFlow — APPROVED** [review]
I approve, but I prefer the following approach:
1. Define `order_id._get_destination_location()` as `default` for the `location_dest_id` field.
2. Add a migration script to fill the `location_dest_id` field whenever it's empty.

Perhaps when migrating the `purchase_location_by_line` module to v10 then we might apply this approach.

**Comment by JordiBForgeFlow** [comment]
Thanks @mreficent for your proposal.

**Review by LoisRForgeFlow — APPROVED** [review]
Code review. LGTM :+1:

**Review by gmeficent — APPROVED** [review]
Code and functional review :+1:

**Pull request merged**
