### PR TITLE
[FIX] No account type on analytic account.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by sbidoul** [comment]
:+1:

**Review by benwillig — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by benwillig** [comment]
This PR can be merged I think.

**Comment by benwillig** [comment]
This PR can be closed, the issue was fixed in https://github.com/OCA/purchase-workflow/pull/458...

**Pull request closed without merging**
