### PR TITLE
[15.0][MIG] purchase_order_type

### PR DESCRIPTION
**Pull request by vvrossem**

### CODE REVIEW

**Comment by vvrossem** [comment]
Hi @kittiu, @newtratip , @SurachetS ,  could you please review this PR? 🙏 Thank you !

**Comment by vincent-cowboy** [comment]
@Olageibol could you please review this PR ? 🙏

**Comment by Rad0van** [comment]
@vvrossem it seems you didn't follow instructions in migration guide. See https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 If you had there would be 2 commits at the end like this:
[IMP] purchase_order_type: black, isort, prettier
[MIG] purchase_order_type: Migration to 15.0

**Comment by vvrossem** [comment]
@Rad0van thank you for your kind review, requested changes are now made.

**Review by Rad0van — APPROVED** [review]
LGTM. Tested and works. Couldn't make test to run on 15.0 though.

**Review by xhnilic3 — APPROVED** [review]

**Pull request merged**
