### PR TITLE
[IMP] various: improve code style and performance by improve ``all()`…

### PR DESCRIPTION
**Pull request by tanghulu0608**
Like this. 
[[IMP] various: improve code style and performance by improve ``all()`` usage
](https://github.com/odoo/odoo/commit/1cc6bb1231401ea7f501d2f5b5e9641ec8734850)

### CODE REVIEW

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
check pre-commit

**Review by legalsylvain — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
It cannot be merged if any check is failing @tanghulu0608

**Comment by tanghulu0608** [comment]
@HviorForgeFlow  hello, I don't know what is wrong.Could you help me please?

**Comment by HviorForgeFlow** [comment]
> @HviorForgeFlow hello, I don't know what is wrong.Could you help me please?

You must use pre-commit, in order to use it on your local development environment you can run:
```
pip install pre-commit
# Then from repo folder you would run
pre-commit run -a
```
Finally amend to previous commit and push the code again

**Comment by tanghulu0608** [comment]
@HviorForgeFlow  thank you very much

**Pull request merged**
