### PR TITLE
8.0 metafiles

### PR DESCRIPTION
**Pull request by pedrobaeza**

### CODE REVIEW

**Comment by oihane** [comment]
:+1:

**Comment by bwrsandman** [comment]
Getting a false negative in the tests

**Comment by eLBati** [comment]
It seems an error of travis_run_tests

**Comment by pedrobaeza** [comment]
This is because there is any module outside `__unported__`. Others have put a fake module inside until first migration, but I prefer not to put it. First migration is coming ;)

**Comment by bwrsandman** [comment]
> First migration is coming

:fearful: sounds ominous!

**Comment by pedrobaeza** [comment]
Hehe, it's only a joke with Game of thrones sentence.

I have _purchase_discount_ module prepared for PR when you merge this one.

Regards.

**Comment by bwrsandman** [comment]
:+1: trivially correct

**Comment by bwrsandman** [comment]
@dreispt https://github.com/OCA/maintainer-quality-tools/pull/52 fixed tests on empty repos
Awesome!

**EDIT:** partially... for some reason OCB is failing...

**Comment by pedrobaeza** [comment]
odoo test is taking `__unported__` dir:

```
/home/travis/build/OCA/purchase-workflow/__unported__
```

but OCB isn't.

**Comment by bwrsandman** [comment]
In any case, the tests should ignore `__unported__` and not use the `-i`parameter (or at least add base when none are present) when it can't find modules

**Comment by dreispt** [comment]
@bwrsandman Yes, there's something wrong there. I'll investigate to find a fix.

**Comment by pedrobaeza** [comment]
With the new python port, it's simpler to check the result of get_addons

**Comment by bwrsandman** [comment]
Actually, I restarted the odoo build, but not the OCB one after the python port, so the `-i` parameter problem is probably from before. I will restart the OCB build to make sure.

**Comment by bwrsandman** [comment]
Ok, that was the issue.
Sorry false alarm @dreispt 

```
usage: spawn [spawn-args] program [program-args]
while executing
"spawn -noecho"
("eval" body line 1)
invoked from within
"eval [list spawn -noecho] $argv"
invoked from within
"if {[string compare [lindex $argv 0] "-p"] == 0} {
# pipeline
set stty_init "-echo"
eval [list spawn -noecho] [lrange $argv 1 end]
clo..."
(file "/usr/bin/unbuffer" line 13)
```

Is this something to worry about?

**Comment by dreispt** [comment]
There was something wrong anyway: **unported** normaly doesn't get into the addons path, but in the case of an empty repo it does.
Provided a fix with https://github.com/OCA/maintainer-quality-tools/pull/58

**Pull request merged**
