### PR TITLE
8.0 procurement purchase no grouping

### PR DESCRIPTION
**Pull request by NL66278**
Move module procurement_purchase_no_group to OCA, while correcting tests.

See this discussion:
https://github.com/odoomrp/odoomrp-wip/issues/1141

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please respect commit history following this guide: https://github.com/odoomrp/odoomrp-wip/wiki/Migration-to-OCA and adapt readme to latest conventions

**Comment by tafaRU** [comment]
I'm working on it.

**Comment by tafaRU** [comment]
Please close it in favour of https://github.com/OCA/purchase-workflow/pull/343

**Comment by NL66278** [comment]
Closed in favour of #343

**Comment by tafaRU** [comment]
Thanks, @NL66278!

**Pull request closed without merging**
