### PR TITLE
[14.0][ADD] purchase_request_exception

### PR DESCRIPTION
**Pull request by kittiu**
This module extend `base_exception` for purchase request. Ready for review

### CODE REVIEW

**Comment by kittiu** [comment]
cc @flook-chaiwat

**Comment by flook-chaiwat** [comment]
Functional tested: Look good to me, it can be used to custom several rules for Purchase Request.

**Review by flook-chaiwat — COMMENTED** [review]
Functional tested: OK

**Comment by kittiu** [comment]
Ready for final review.

**Review by newtratip — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Pull request merged**
