### PR TITLE
[13.0][UPD] Eficent -> ForgeFlow and add fragmented readme

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
...

### CODE REVIEW

**Review by albariera — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by MiquelRForgeFlow** [comment]
I deleted the old readmes to avoid that stupid bot error.

**Comment by HviorForgeFlow** [comment]
/ocabot merge nobump

:sleepy: :zzz:

**Pull request merged**
