### PR TITLE
[15.0][MIG] purchase_discount: Migration to 15.0

### PR DESCRIPTION
**Pull request by moaadbourhim**
Migration of purchase_discount to 15.0

### CODE REVIEW

**Comment by moaadbourhim** [comment]
@pedrobaeza Can you Please review this PR

**Comment by pedrobaeza** [comment]
The same problem about splitting the migration changes in its own commit.

/ocabot migration purchase_discount

**Comment by moaadbourhim** [comment]
@pedrobaeza 
I have split changes in two commits  
can you please review it

**Review by pedrobaeza — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Pull request merged**
