### PR TITLE
[16.0][IMP] purchase_discount: Use core hook

### PR DESCRIPTION
**Pull request by pedrobaeza**
This will fail until https://github.com/odoo/odoo/pull/175998 is merged.

Following https://github.com/odoo/odoo/pull/175998, we can remove the hacks done for cleaner code.

The hook method `_get_discounted_price_unit` is preserved for not having to adapt subsequent modules (like purchase_triple_discount).

@Tecnativa

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]

**Comment by carlos-lopez-tecnativa** [comment]
Error on test are related?
Total/Subtotal are incorrect, please check image

With this PR
image

Before this PR
image

**Comment by pedrobaeza** [comment]
@carlos-lopez-tecnativa please check initial comment:

image

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by legalsylvain** [comment]
@pedrobaeza : could you rebase ?

**Comment by pedrobaeza** [comment]
Done, and finally I had to touch `purchase_triple_discount`, as it was ignoring `_get_discounted_price_unit` method and doing something a bit with a weird extensibility system (for discounts 4 and 5?).

**Review by carlos-lopez-tecnativa — APPROVED** [review]
LGTM thanks!

**Pull request merged**
