### PR TITLE
[14.0][MIG] purchase_invoice_plan

### PR DESCRIPTION
**Pull request by SurachetS**
depends on

- [x] purchase_open_qty [pull1023](https://github.com/OCA/purchase-workflow/pull/1023)

### CODE REVIEW

**Comment by kittiu** [comment]
@SurachetS purchase_open_qty is done. Can you rebase and this this one again please.

**Comment by kittiu** [comment]
@SurachetS can rebase?

**Comment by PrapassornS** [comment]
Functional Tested LGTM.

**Review by PrapassornS — APPROVED** [review]
Functional Tested LGTM.

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
