### PR TITLE
[17.0][MIG] purchase_order_qty_change_no_recompute: Migration to 17.0

### PR DESCRIPTION
**Pull request by maciej-wichowski**

### CODE REVIEW

**Comment by maciej-wichowski** [comment]
FYI @victoralmau

**Review by victoralmau — APPROVED** [review]
Code and functional review OK.

Please change title to: [17.0][MIG] purchase_order_qty_change_no_recompute: Migration to 17.0

Ping @pedrobaeza

**Review by StefanRijnhart — APPROVED** [review]

**Pull request merged**
