### PR TITLE
[16.0][MIG] product_form_purchase_link

### PR DESCRIPTION
**Pull request by aliciagaarzo**
Migration of **product_form_purchase_link** module to version 16

### CODE REVIEW

**Review by flalexg — APPROVED** [review]
Code LGTM!

**Comment by HviorForgeFlow** [comment]
It seems that the feature is already in standard Odoo, isn't it? @aliciagaarzo 
image

**Comment by aliciagaarzo** [comment]
Absolutely right @HviorForgeFlow , migration is closed.

**Pull request closed without merging**
