### PR TITLE
[15.0][MIG] subcontracted_service: Migration to 15.0

### PR DESCRIPTION
**Pull request by PauBForgeFlow**
Migration based on last 14.0 PR: https://github.com/OCA/purchase-workflow/pull/1952

### CODE REVIEW

**Review by AaronHForgeFlow — COMMENTED** [review]
Functional review LG.

**Comment by AaronHForgeFlow** [comment]
BTW I think you can remove the test-requirements commit, as the dependency https://github.com/OCA/stock-logistics-warehouse/pull/1818 is now merged

**Review by JasminSForgeFlow — APPROVED** [review]

**Comment by rafaelbn** [comment]
/ocabot migration subcontracted_service

Please @PauBForgeFlow attend comments from @AaronHForgeFlow

**Comment by PauBForgeFlow** [comment]
test-requirements file has been removed @AaronHForgeFlow @rafaelbn

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Pull request merged**
