### PR TITLE
[13.0][FIX] purchase_deposit

### PR DESCRIPTION
**Pull request by ps-tubtim**
- Fix multi down payment error.

**Process**
1. Create and Confirm PO.
2. Register Deposit 10%
3. Return to PO
4. Register Deposit 30% -> Error

Bug_purchase_deposit
Selection_014

**After fix it**

bug_fix_purchase_deposit

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by ps-tubtim** [comment]
@newtratip @Saran440 Cloud you review this PR?

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Review by Saran440 — APPROVED** [review]
Code Reviewed. LGTM :+1:

**Pull request merged**
