### PR TITLE
[14.0][ADD] purchase_request_cancel_confirm

### PR DESCRIPTION
**Pull request by kittiu**
Depends on,
- [x] base_cancel_confirm https://github.com/OCA/server-ux/pull/297

This module extend `base_cancel_confirm` to make cancel confirmation with cancel reason (none / optional / requried).

Selection_044

### CODE REVIEW

**Comment by kittiu** [comment]
Test added, ready for review.

**Review by ps-tubtim — APPROVED** [review]
Code LGTM.

**Review by newtratip — APPROVED** [review]
LGTM :+1:

**Pull request merged**
