### PR TITLE
[13.0][IMP] purchase_open_qty: consider services

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Qty to receive for services cannot be based on stock moves.

@ForgeFlow

### CODE REVIEW

**Review by JordiMForgeFlow — APPROVED** [review]
Makes sense 👍🏼

**Review by JaumeBforgeFlow — APPROVED** [review]
LGTM :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@LoisRForgeFlow should it be forwardported? I guess yes

**Comment by LoisRForgeFlow** [comment]
@HviorForgeFlow Yes, once merged I can fwport it

**Comment by MiquelRForgeFlow** [comment]
needs forward ports

**Pull request merged**
