### PR TITLE
[11.0][MIG] subcontracted_service

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Major changes are related to deletion of procurement.order model in v11.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot, LGTM :+1:

**Comment by mreficent** [comment]
Please, rebase and **drop** commits 0d43546, 0fe3340, f1a58f6 and 25d8a45, they shouldn't be here.

**Comment by mreficent** [comment]
please, delete also commit 0881678

**Review by MiquelRForgeFlow — APPROVED** [review]
code review :+1:

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
