### PR TITLE
[11.0][purchase_workflow_tier_valiation] add the status 'to approve' to the initiating states to trigger the validation.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Fixes a compatibility problem with https://github.com/OCA/purchase-workflow/tree/11.0/purchase_order_approval_block

cc @etobella

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Comment by rousseldenis** [comment]
@jbeficent Don't forget to update module version

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
~~Superseed https://github.com/OCA/purchase-workflow/pull/682~~

**Review by etobella — CHANGES_REQUESTED** [review]
You should review all the views. Buttons of validation are not shown due to the missing state. 
I made a PR into your branch in order to fix it.
eficent/purchase-workflow#22

**Review by etobella — APPROVED** [review]
LGTM :+1:

**Comment by HviorForgeFlow** [comment]
@etobella what about add this view change, to keep all tier validations models the same.

**Comment by etobella** [comment]
:+1:

**Review by HviorForgeFlow — APPROVED** [review]
Superseed https://github.com/OCA/purchase-workflow/pull/682

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Confirmation Order when it has been validated is not working.
image

**Comment by etobella** [comment]
The problem is related to purchase_exception. A PR was created today in order to solve the issue:
OCA/server-tools#1572

**Comment by HviorForgeFlow** [comment]
I'm not sure because I tried also on my local environment and it is working. Just has faiiled on runbot...

**Comment by JordiBForgeFlow** [comment]
I merged OCA/server-tools#1572

**Comment by etobella** [comment]
The problem happens when purchase_exception and purchase_order_tier_validation are installed at the same time.

**Pull request merged**
