### PR TITLE
[14.0][ADD] purchase_order_line_description_picking

### PR DESCRIPTION
**Pull request by MateuGForgeFlow**
Propagates product description from PO to stock picking.
cc @LoisRForgeFlow

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Name should be adjusted I think. Other than that, code review looks good to me

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM, the module name is a bit hard I think

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
What about purchase_order_line_description_picking ? @LoisRForgeFlow @AaronHForgeFlow @MateuGForgeFlow 

A simple test won't hurt :100:

**Comment by MateuGForgeFlow** [comment]
@HviorForgeFlow @AaronHForgeFlow Name changed and tests added, please review!

**Review by HviorForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
