### PR TITLE
[12.0][FIX] purchase_request: allocations

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
This PR aims the need to keep a consistency on Purchase Request Allocation UoM across PR and PO lines.
I decided to keep same UoM on allocations and PR Lines, it makes sense for me to keep that way.
Allocations behave as they should when PO is Cancel, Set to Draft and Deleted.

cc ~ @Eficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: 

Test performed:

- Created PR for less qty and selecting different uom in the wizard. Allocations created for the correct qty
- Deleting the PO will flag the allocations as cancelled
- Receive less qty than qty requested. Allocations updated accordingly

**Comment by HviorForgeFlow** [comment]
CC @joansis @NuriaMartinXifre can you review? Thanks!

**Review by JoanSForgeFlow — APPROVED** [review]
Functional review done!

**Review by NuriaXifre — APPROVED** [review]
Functional review done, works as expected!

**Comment by kittiu** [comment]
@kongrattapong

**Pull request merged**
