### PR TITLE
[11.0][FIX] purchase_request : ValueError: Expected singleton

### PR DESCRIPTION
**Pull request by bodedra**
Issue Reference: https://github.com/OCA/purchase-workflow/issues/751

### CODE REVIEW

**Comment by bodedra** [comment]
@jbeficent @lreficent @aheficent @hveficent

**Comment by bodedra** [comment]
@JonathanNEMRY @adrienpeiffer

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
Thanks for the fix! @aheficent can you review in v12?

**Pull request merged**
