### PR TITLE
Add module procurement_select_route

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The normal way to handle the scenario you describe is to make routes selectable on sale order lines, and select from there which one you want. It's even easier, as you don't need to switch your view to procurements. Please check this option.

On this, I don't see the meaning for this module.

**Comment by ghost** [comment]
@pedrobaeza I don't agree. The user who creates the sale order is not necessarily the one who decides which route must be used. In the case of my client, the warehouse manager is the one who decides the route to use, but he is not the one who confirms the sale.

**Comment by pedrobaeza** [comment]
OK, you're right. Please add this rationale to the README.

**Comment by ghost** [comment]
@pedrobaeza ok done

**Pull request closed without merging**
