### PR TITLE
[16.0][FIX] purchase_exception

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Reference from https://github.com/OCA/sale-workflow/pull/2918.

@qrtl

### CODE REVIEW

**Review by yostashiro — APPROVED** [review]
Code review.

**Review by flotho — APPROVED** [review]
code review,
LGTM

**Review by rousseldenis — APPROVED** [review]
Of course

**Comment by AungKoKoLin1997** [comment]
@OCA-purchase-workflow-maintainers
Can we get this PR merged?

**Pull request merged**
