### PR TITLE
[15.0][MIG] purchase_order_supplierinfo_update: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT36509

Based on https://github.com/OCA/purchase-workflow/pull/1303

### CODE REVIEW

**Comment by ernestotejeda** [comment]
I got the same error https://github.com/OCA/purchase-workflow/pull/1303#issuecomment-972654032 :confused:

**Comment by ernestotejeda** [comment]
ping @carlosdauden @dreispt @pedrobaeza

**Comment by pedrobaeza** [comment]
Please check red CI

**Comment by sergio-teruel** [comment]
Ready

**Review by sergio-teruel — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
