### PR TITLE
[11.0][FIX] purchase_request: Always use Product Unit Of Measure precision

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Port to v11 of https://github.com/OCA/purchase-workflow/pull/740/commits/d8876cdb8c22948a4a39666409f516ce394ed288

@hparfr as we merged purchase request I couldn't cherry-pick it

### CODE REVIEW

**Review by rousseldenis — APPROVED** [review]
Makes sense !

**Review by hparfr — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Thank you!

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
