### PR TITLE
[12.0][FIX] purchase_work_acceptance: fix xpath config view

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @augustodinizl @kaynnan

**Review by kaynnan — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
ping @OCA/procurement-purchase-maintainers

**Review by augustodinizl — APPROVED** [review]
LGTM

**Comment by rafaelbn** [comment]
Please @marcelsavegnago , could you provide a screenshot with before and after this FIX?

**Comment by marcelsavegnago** [comment]
> Please @marcelsavegnago , could you provide a screenshot with before and after this FIX?

**Before**
image


**After**
image

**Review by rvalyi — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
