### PR TITLE
[FIX]purchase_request: add product_uom_id domain

### PR DESCRIPTION
**Pull request by vib-adhoc**
Show only the same uom category of product_id

### CODE REVIEW

**Comment by vib-adhoc** [comment]
@rousseldenis @kittiu Would you please review this PR and merge if it's okay?

**Review by nicomacr — APPROVED** [review]
LGTM

**Review by hitrosol — APPROVED** [review]
LGTM

**Review by rousseldenis — APPROVED** [review]
LGTM.

@vib-adhoc Don't update module version in manifest as it will be done by ocabot.

**Comment by vib-adhoc** [comment]
@rousseldenis I made the suggested change. Would you please merge this PR if it's okay?

**Review by rousseldenis — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@vib-adhoc can you forward port it to v14 and v15? Thanks!

**Comment by vib-adhoc** [comment]
@HviorForgeFlow [FW v14](https://github.com/OCA/purchase-workflow/pull/1548) [FW v15](https://github.com/OCA/purchase-workflow/pull/1549)

**Pull request merged**
