### PR TITLE
FIX purchase_order_revision

### PR DESCRIPTION
**Pull request by eLBati**
1.create purchase order ..maybe: PO00001
2.confirm purchase order
3. cancle this purchase order .name: PO00001
4.new revision ....then create new purhcase order name i s PO00001-1
5.cancel this purchase order name PO00001-1
6.more->duplicate
7.new purchase order create...name is PO00002
8. confirm this order PO00002
9.cancel this order PO00002
10. new revision.....then error

Order Reference must be unique per Company

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why the `copy=` attribute is not working? It would be great to have a test to cover this use case.

**Comment by eLBati** [comment]
@pedrobaeza because `unrevisioned_name` must be copied only when a new revision is created, not in the standard copy.

Added the test case

**Comment by pedrobaeza** [comment]
:+1: 

Thanks!

**Comment by omar7r** [comment]
:+1:

**Comment by jaronemo** [comment]
Dears:
Updated Code.
It has completed testing on a new database and production database.
Thank you very much help!

**Pull request merged**
