### PR TITLE
[15.0][MIG] purchase_order_qty_change_no_recompute: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36508

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
@pedrobaeza could you please review?

**Review by pedrobaeza — APPROVED** [review]
Code review and tested on runboat

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
