### PR TITLE
[15.0][MIG] supplier_calendar

### PR DESCRIPTION
**Pull request by DavidJForgeFlow**
Standard Migration to 15.0

There is a test failing in purchase_stock_secondary_unit. Fix in #2125 

@ForgeFlow

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@DavidJForgeFlow it seems that CI is red, could you have a look?

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
