### PR TITLE
[17.0][MIG] purchase_force_invoiced

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Review by cormaza — APPROVED** [review]
LGTM

**Review by gurneyalex — APPROVED** [review]

**Comment by dalonsod** [comment]
@celm1990 I've notice that you've actually changed `readonly` condition for `force_invoiced` flag. Was it an error or an intended change? Otherwise, this could be restored to its original behavior IMO

cc @cormaza @gurneyalex

**Pull request merged**
