### PR TITLE
[9.0][REF] Refactor deprecated fields and methods Zak

### PR DESCRIPTION
**Pull request by zakiuu**
* the `get_id()` method on ir.sequence model is deprecated in the new API,
hence using next_by_code() is better.
* The `location_id` field doesn't exist anymore in `purchase.order` nor in
`purchase.order.line` models

* The `fiscal_position` field was renamed to `fiscal_position_id`

* the `pricelist_id` doesn't exist on the `purchase.order` model anymore

### CODE REVIEW

**Comment by zakiuu** [comment]
@adrienpeiffer @sbidoul

**Comment by zakiuu** [comment]
@lreficent

**Review by LoisRForgeFlow — APPROVED** [review]
Code review, makes sense for me :+1:

**Comment by zakiuu** [comment]
@lreficent thanks for the review

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
