### PR TITLE
[16.0][MIG] purchase_order_general_discount: Migration to 16.0

### PR DESCRIPTION
**Pull request by cuongnmtm**

### CODE REVIEW

**Review by navarrorico — APPROVED** [review]
Functional review

**Review by dsolanki-initos — COMMENTED** [review]
Function review LGTM.
Minor change: For method `fields_view_get`.It's showing deprecated warning, could to please fix it? Thanks.

**Comment by cuongnmtm** [comment]
> Function review LGTM. Minor change: For method `fields_view_get`.It's showing deprecated warning, could to please fix it? Thanks.

Thank you for the information. 

I have updated the code (and related automatic tests).

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
