### PR TITLE
[13.0][MIG] purchase_request

### PR DESCRIPTION
**Pull request by kongrattapong**
Ready for review.
replace https://github.com/OCA/purchase-workflow/pull/785
cc. @hveficent @CasVissers

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
PRs in process to be merged:
https://github.com/OCA/purchase-workflow/pull/795
https://github.com/OCA/purchase-workflow/pull/761

Please cherry-pick them when merged :disappointed: 

Thanks!

**Comment by kongrattapong** [comment]
> PRs in process to be merged:
> #795
> #761
> 
> Please cherry-pick them when merged 
> 
> Thanks!

OK, I'll
Thank you.

**Comment by kongrattapong** [comment]
@hveficent Can you tell me what is this function work? https://github.com/OCA/purchase-workflow/pull/804/commits/863013ddd3fec4a43c2c0a41b17e5d40c47c18bd#diff-7859c750a9292fa6914d280282c9ce09R271-R275
``` 
         if (
                float_compare(qty_done, request.product_qty, precision_digits=precision)
                >= 0
            ):
                request.set_done()
``` 
I can't find function  ``` set_done() ```

I hypothesized that It change state of purchase_request_line to 'done' am I right?

**Comment by HviorForgeFlow** [comment]
@kongrattapong As you can see check_done functions is not implemented anywhere, so this piece of code is not used. So you may ask @aheficent, I think it needs to be implemented at some point to mark purchase request done when all their purchase request line allocations are completed.

**Comment by HviorForgeFlow** [comment]
Feel free to add the feature and a coverage test to ensure the workflow or just mention it on README's roadmap.

**Comment by kongrattapong** [comment]
Okay, after I finish I'll tell you to review. thank you very much for your suggestions

**Comment by kongrattapong** [comment]
@hveficent in ```purchase_request_line```  function ```_planned_date``` Can you explain what case in business to use this function?

**Comment by HviorForgeFlow** [comment]
> @hveficent in `purchase_request_line` function `_planned_date` Can you explain what case in business to use this function?

@kongrattapong Another example of function that is not used. Same as above, It tries to implement Security Lead Time for Purchase on Advanced Scheduling from Inventory option allowing at company level to increase Lead Time margin from vendor to receive earlier for purchases.

It requires to evaluate if this piece of code is required to handle this option, or at purchase side it is automatically used when create the PO.

CC @aheficent

**Comment by HviorForgeFlow** [comment]
I miss this 2 commits from v12:
https://github.com/OCA/purchase-workflow/commit/6e2a53560fed38aa11600cb35b0d6928a2d7a735#diff-294d60bd77276ebb3d8a85078cc6484c
https://github.com/OCA/purchase-workflow/commit/4fe36979f824d0b9b3680e5817bb524ab2eef5df#diff-294d60bd77276ebb3d8a85078cc6484c

**Comment by HviorForgeFlow** [comment]
Hello @kongrattapong can you greenify this PR? I would like it to be merged soon.

**Comment by kongrattapong** [comment]
> Hello @kongrattapong can you greenify this PR? I would like it to be merged soon.

@HviorForgeFlow Fixed it.

**Comment by HviorForgeFlow** [comment]
@kongrattapong I was trying to open a PR on your repository, but I couldn't, don't know why.
I pushed a branch here https://github.com/ForgeFlow/purchase-workflow/tree/13.0-mig-purchase_request_bis with some changes, and taking current purchase_request v12 version.
Please take a look
Thanks,

**Review by HviorForgeFlow — APPROVED** [review]
Technical and functional review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review. Working as expected.

**Pull request merged**
