### PR TITLE
[15.0][MIG] purchase_order_product_recommendation_xlsx: Migration to version 15.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT40184

ping @CarlosRoca13 @chienandalu

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Tested. :+1: 

Looks like the tests are failing on `purchase_tier_validation` deps

**Comment by sergio-teruel** [comment]
ping @CarlosRoca13

**Review by CarlosRoca13 — APPROVED** [review]
Test + Code review :+1:

**Pull request merged**
