### PR TITLE
[9.0] purchase_location_by line

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Purchase Location by Line
=========================

Allows to define a specific destination location on each Purchase Order line.
When the PO is confirmed, it will generate one Incoming Shipment per
combination of destination location and expected date indicated in the
Purchase Order Lines.

The corresponding PR for v8 can be found here: https://github.com/OCA/purchase-workflow/pull/237

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @darshan-serpent @aheficent

**Comment by JordiBForgeFlow** [comment]
Depends on https://github.com/OCA/purchase-workflow/pull/311

**Comment by AaronHForgeFlow** [comment]
I expect 3 shipments for this PO but I'm getting 4.

image

**Comment by LoisRForgeFlow** [comment]
Same as @aheficent We expected the two PO for Chicago and same date to be together.

**Comment by gmeficent** [comment]
@aheficent, it may be that it compares the minutes, so the grouping is technically correct, the dates minutes should be the same or truncated.

**Comment by gmeficent** [comment]
@aheficent, Confirmed, if you choose the same date down to the minute it works
image

**Comment by AaronHForgeFlow** [comment]
You're right! @gmeficent <code>date_planned</code> is type Datetime in v9. Thank you!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM now! :+1:

**Pull request merged**
