### PR TITLE
[16.0][MIG] purchase_request_department: migration

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by AungKoKoLin1997** [comment]
@mav-adhoc Can you please check why tests CI are failed?

**Comment by bruno-zanotti** [comment]
@AungKoKoLin1997 I already fixed the tests, the problem was that this module has 'hr' as dependency and this broke the tests of purchase_request, you can check the last commit

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review ok

**Comment by mav-adhoc** [comment]
@AungKoKoLin1997 Can you review the PR? Thanks!

**Comment by AungKoKoLin1997** [comment]
@mav-adhoc I am wondering why you didn't migrate from 15.0 branch instead of 13.0. Is there any reason?

**Comment by mav-adhoc** [comment]
@AungKoKoLin1997 Sorry, my mistake. However, after checking the differences between 13.0 and 15.0 i only saw a slight difference in the purchase_request model, which of course i've included in this PR.

**Comment by ced-adhoc** [comment]
Hi @AungKoKoLin1997 , could you please check this pr? thanks!

**Comment by jcadhoc** [comment]
@HviorForgeFlow Hello Héctor!

Can you check this pr and merge? Thank you!

**Comment by HviorForgeFlow** [comment]
@jcadhoc @mav-adhoc commit history is broken, try to migrate from the previous major version if it is available there. thanks

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Ok! Thanks! Im going to close this PR so as we migrate this one: https://github.com/OCA/purchase-workflow/pull/2362, which is the migration from v15 to v16.

**Pull request closed without merging**
