### PR TITLE
[IMP] purchase_discount: Use hooks + tests + icon

### PR DESCRIPTION
**Pull request by pedrobaeza**
- Use hooks provided by https://github.com/odoo/odoo/commit/617ef49959d027fab52e2be74aa4c0dc3ce60e30
- Added specific icon
- Added tests

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Coverage is decreasing because although I provide tests, the number of lines of this module has drastically been reduced, so the overall weight in the repo has decreased.

**Comment by guewen** [comment]
:+1:

**Comment by max3903** [comment]
:+1:

**Comment by lmignon** [comment]
:+1:

**Pull request merged**
