### PR TITLE
[IMP] purchase_order_general_discount: checkbox to use real purchase supplier discounts

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
IMP to adapt the purchase_order_general_discount module to IMP #2070 (purchase_discount) in which a checkbox is added to use the real supplier discount.

In the case of having the checkbox 'Real Purchase Supplier Discount' activated and not finding the seller, the discount of the purchase line will be set to the general discount.

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@HaraldPanten @ValentinVinagre

**Comment by legalsylvain** [comment]
I think you refer to https://github.com/OCA/purchase-workflow/pull/2070, not https://github.com/OCA/purchase-workflow/pull/270

**Comment by HaraldPanten** [comment]
@pedrobaeza the last one 👍

**Review by HaraldPanten — APPROVED** [review]

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Pull request merged**
