### PR TITLE
[13.0][IMP] purchase_order_approved: add approved orders filter

### PR DESCRIPTION
**Pull request by JordiMForgeFlow**
Add filter for approved Purchase Orders + Allow cancelling approved Purchase Orders

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]

**Review by RaulOForgeFlow — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]

**Comment by JordiMForgeFlow** [comment]
I have added a new commit to allow cancelling approved orders. cc @AaronHForgeFlow @AdriaGForgeFlow @RaulOForgeFlow

**Review by RaulOForgeFlow — APPROVED** [review]
LGTM

**Review by AdriaGForgeFlow — APPROVED** [review]

**Pull request merged**
