### PR TITLE
[12.0][FIX] purchase_order_product_recommendation: Don't recommend inactive or not purchasable products

### PR DESCRIPTION
**Pull request by pedrobaeza**
It includes a tests that exercises the patch.

@Tecnativa TT23991

### CODE REVIEW

**Review by sergio-teruel — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Please, remember apply to v13.0

**Comment by pedrobaeza** [comment]
Yes, when merged I will cherry-pick it. I'm wondering about the performance of this addition and not sure if we should look to filter at `read_group` level.

**Comment by pedrobaeza** [comment]
Performance checked and it's very similar, as the products have to be fetched anyway later.

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Cherry-picked for v13 in 7c1692cb01b67939f64a1174f45935dcaa7e3ffc

**Pull request merged**
