### PR TITLE
[16.0][MIG] purchase_order_uninvoiced_amount: Migration to version 16.0

### PR DESCRIPTION
**Pull request by Yadier-Tecnativa**
@Tecnativa TT42425

### CODE REVIEW

**Comment by Yadier-Tecnativa** [comment]
ping @sergio-teruel , @pedrobaeza

**Review by pedrobaeza — APPROVED** [review]
Code and functional review

**Review by hugo-cordoba — APPROVED** [review]
LGTM! (Code Review)

**Comment by sergio-teruel** [comment]
ping @juangomezzurita

**Pull request merged**
