### PR TITLE
[17.0][MIG] purchase_partner_incoterm

### PR DESCRIPTION
**Pull request by manishkumarbohra**
Module Name : Default purchase incoterm per partner (purchase_partner_incoterm)

Migration to 17.0

For Issue https://github.com/OCA/purchase-workflow/issues/2087

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Review by nguyenminhchien — APPROVED** [review]

**Comment by gurneyalex** [comment]
@manishkumarbohra can you 

```
git rm purchase_partner_incoterm/readme/*.rst 
git commit --amend
```

**Comment by HviorForgeFlow** [comment]
ping @manishkumarbohra

**Comment by yvaucher** [comment]
bump @manishkumarbohra

**Comment by HviorForgeFlow** [comment]
ping @manishkumarbohra

**Comment by chaule97** [comment]
Created https://github.com/OCA/purchase-workflow/pull/2386 to fix the redundant md/rst issue.

**Comment by HviorForgeFlow** [comment]
Superseeded

**Pull request closed without merging**
