### PR TITLE
[MIG] purchase_order_archive: Migration to 16.0

### PR DESCRIPTION
**Pull request by CLaurelB**

### CODE REVIEW

**Comment by CLaurelB** [comment]
@luisg123v @desdelinux could you review, please?

**Review by desdelinux — APPROVED** [review]
Functional Review is ok :+1: 

Could you review @HviorForgeFlow

**Comment by desdelinux** [comment]
Could you review @pedrobaeza @HviorForgeFlow @rafaelbn

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1: 
Thanks for adding tests, you should add yourself as a contributor :)
Why are you removing es.po translations?
 @CLaurelB

**Comment by CLaurelB** [comment]
> Code review 👍 Thanks for adding tests, you should add yourself as a contributor :) Why are you removing es.po translations? @CLaurelB

Thanks, I just added myself as a contributor.

About the es.po file, I removed it by mistake. It is now back in the last commit. 

P.S. After updating the PR, I noticed that the pre-commit fails but the error is in the module purchase_request.

@HviorForgeFlow

**Comment by HviorForgeFlow** [comment]
@CLaurelB try rebasing with current 16.0 branch, I think it will fix this issue. Thanks for the fast response!

**Comment by CLaurelB** [comment]
> @CLaurelB try rebasing with current 16.0 branch, I think it will fix this issue. Thanks for the fast response!

@HviorForgeFlow I just rebase my branch but It seems the issue is in the 16.0 branch.

https://github.com/OCA/purchase-workflow/actions/runs/6174540577/job/16759365412

**Comment by HviorForgeFlow** [comment]
Solving issue here: https://github.com/OCA/purchase-workflow/pull/2005

**Comment by CLaurelB** [comment]
> Solving issue here: #2005

@HviorForgeFlow I rebase again and the issue is still there but only on the SHA-256 hash.

**Comment by CLaurelB** [comment]
@HviorForgeFlow all checks have passed 👍

**Comment by HviorForgeFlow** [comment]
@sbidoul please take a look here: https://github.com/OCA/purchase-workflow/pull/1993#issuecomment-1720720649

**Review by kaynnan — APPROVED** [review]

**Comment by sbidoul** [comment]
I'm preparing a fix to the bot: https://github.com/OCA/oca-github-bot/pull/259

**Comment by sbidoul** [comment]
Okay, bot updated. Let's see how it goes now.

/ocabot merge nobump

**Pull request merged**
