### PR TITLE
[15.0][MIG] purchase_stock_secondary_unit: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT40701

Supersede https://github.com/OCA/purchase-workflow/pull/1788

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @sergio-teruel @carlosdauden

**Review by carlosdauden — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]
Tested on runboat :+1:

**Pull request merged**
