### PR TITLE
[16.0][ADD] purchase_order_purchase_manager

### PR DESCRIPTION
**Pull request by EmilioPascual**
This module extends the functionality of the purchase order to allow the purchase manager to be set manually or automatically from the value contained in the supplier manually.

@rafaelbn @Gelojr @Shide please review 😃.  

MT-4253

### CODE REVIEW

**Review by Shide — APPROVED** [review]
Functional review

**Comment by rafaelbn** [comment]
Thank you!

Maybe it was a misunderstanding! user_id in the purchase.order should be the purchase.manager . We don't want duplicated the field in the purchase order, just set in the partner (vendor) de responsible

😄 ❤️

**Comment by EmilioPascual** [comment]
> Thank you!
> 
> Maybe it was a misunderstanding! user_id in the purchase.order should be the purchase.manager . We don't want duplicated the field in the purchase order, just set in the partner (vendor) de responsible
> 
> 😄 ❤️

I must have misunderstood, I thought we were adding a new field, but it is true that a new field will complicate the behaviour.
Changed, thanks for the explanation.

New behavior: https://www.loom.com/share/d33b248617464327a5e089473431ef7d

**Review by Gelojr — APPROVED** [review]
LGTM Thanks @EmilioPascual 
https://www.loom.com/share/6361b916b9ba4bcfbc4e9e4e00003bff?sid=0caf903e-adf2-43f3-973d-583922fa585c

**Review by Shide — APPROVED** [review]
LGTM

**Review by rafaelbn — APPROVED** [review]
👍🏼 Tested!

Really nice job!

Hey @EmilioPascual @Gelojr , why don't you record the videos explaining with your sweet voice and your delicious British accent? 😄 It's quite sad just see with out some voice or just good music! 😃 

🤣 

/ocabot merge patch

**Comment by EmilioPascual** [comment]
> Hey @EmilioPascual @Gelojr , why don't you record the videos explaining with your sweet voice and your delicious British accent? 😄 It's quite sad just see with out some voice or just good music! 😃


Next time with relaxing music 🤣

**Comment by rousseldenis** [comment]
@EmilioPascual @rafaelbn Don't you have problems with this with orderpoints ?

This can be a little bit dangerous as when orderpoints are triggered and will generate a new purchase order line, if the user_id is always set, a new purchase order will be created (as Odoo core will search for draft purchases with no user_id filled in). This can be tedious for buyers to have a ton of purchase orders to manage.

**Comment by EmilioPascual** [comment]
Yes, you're right @rousseldenis. We noticed it a few days ago. We are thinking of a different solution that allows us to filter purchases by the purchasing manager set in vendor.

**Comment by rousseldenis** [comment]
> Yes, you're right @rousseldenis. We noticed it a few days ago. We are thinking of a different solution that allows us to filter purchases by the purchasing manager set in vendor.

Have the same requirements. Let us know (we do it internally for now)

**Comment by rafaelbn** [comment]
Hello @rousseldenis,

Last weeks I was thinking in make a Meet with you. I sould like to show in 1 hour our project yo get you ideas and you hours.

In this point, as you pointed we realize with this implementation we have to improve as is "buggy". Remember @EmilioPascual to make a PR adding the know issues about this matter!! 😄 

- [ ] Make PR with known issues

- There is a function in Odoo where it looks for this field and don't group purchases if this field is set. But now with the hurry we go for more simple solution (and less sophisticated)

- I will use https://github.com/OCA/partner-contact/tree/16.0/partner_purchase_manager and filter in the purchase order by the purchase manager of the vendor... (not the product "responsible"). So we are not going to use the "user_id" in pruchase order until we have time to make it better.

As said, if you would like to meet, I'm glad yo show you everything. 👍🏼 

Regards!

**Pull request merged**
