### PR TITLE
[FIX] purchase_request: Incorrect mapping in compute

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Super seed https://github.com/OCA/purchase-workflow/pull/798

CC @ForgeFlow

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
ping @CasVissers

**Review by CasVissers-360ERP — APPROVED** [review]
Sorry forgot this PR, already have this code running for some time!

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Pull request merged**
