### PR TITLE
[15.0][MIG] purchase_stock_tier_validation

### PR DESCRIPTION
**Pull request by bosd**
Standard migration using odoo-module-migrator  .

/ocabot migration purchase_stock_tier_validation

### CODE REVIEW

**Comment by bosd** [comment]
> Sorry @bosd you are not allowed to mark the addon tobe migrated.
> 
> To do so you must either have push permissions on the repository, or be a declared maintainer of all modified addons.
> 
> If you wish to adopt an addon and become it's [maintainer](https://odoo-community.org/page/maintainer-role), open a pull request to add your GitHub login to the `maintainers` key of its manifest.

Will you finally listen to me on the V16 migration :robot:

**Review by HviorForgeFlow — APPROVED** [review]

**Review by LoisRForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
