### PR TITLE
[16.0][MIG] purchase_request

### PR DESCRIPTION
**Pull request by tewtawat**
Standard Migration

### CODE REVIEW

**Comment by rconjour** [comment]
@tewtawat can you check the failed tests in this PR?

**Comment by tewtawat** [comment]
sure im working on it @rconjour

**Comment by Nikul-OSI** [comment]
superseded: ~~https://github.com/OCA/purchase-workflow/pull/1652~~ https://github.com/OCA/purchase-workflow/pull/1653

**Comment by StefanRijnhart** [comment]
@tewtawat thanks for you contribution! We're proposing our own version after no response on this PR for some time.

**Pull request closed without merging**
