### PR TITLE
[10.0] [FIX] location should be set to draft PO line only

### PR DESCRIPTION
**Pull request by bista-amitd**
Fixes: #498

### CODE REVIEW

**Review by rousseldenis — CHANGES_REQUESTED** [review]
Seems good to me.

Please add a test case and change module version.

**Comment by gurneyalex** [comment]
@bista-amitd do you need help with the CLA?

**Comment by jarmokortetjarvi** [comment]
I Don't have a permission to do an actual review, but for what it's worth, this looks fine to me (except the missing test case).
Tested on a production-clone where this problem is present, and the fix works as intended.

**Review by AaronHForgeFlow — COMMENTED** [review]
But if we allow this, is it consistent when changing the location in confirmed lines? I don't think so.

**Comment by jarmokortetjarvi** [comment]
> But if we allow this, is it consistent when changing the location in confirmed lines? I don't think so.

This is a valid point @aheficent . Do you see a similar problem if this was done by filtering out done stock moves instead of checking the line status?

E.g.
```
if location:
	line.move_ids.filtered(lambda m: m.state != 'done').write(
	{'location_dest_id': location.id})
```

I feel like something like this would be more consistent when changing the location, but wouldn't try to modify validated moves.

**Comment by AaronHForgeFlow** [comment]
At first sight that would be correct. We can try that.

**Comment by jarmokortetjarvi** [comment]
@bista-amitd do you want to take this, or should I make a new PR?

**Pull request closed without merging**
