### PR TITLE
[15.0][MIG] purchase_work_acceptance: Migration to 15.0

### PR DESCRIPTION
**Pull request by sanchonuria**
Standard migration.

@etobella

### CODE REVIEW

**Comment by sanchonuria** [comment]
@ps-tubtim I think you might be interested on this PR :smile:

**Review by Saran440 — APPROVED** [review]
Functional Test :+1: 

@sanchonuria May i add test script and can you check and merge this https://github.com/tegin/purchase-workflow/pull/1?

**Review by ps-tubtim — APPROVED** [review]
LGTM.

**Comment by Saran440** [comment]
@etobella
Can you merge this https://github.com/tegin/purchase-workflow/pull/2 and rebase commit, please?.
Fix test script and refactor some function for easily.
I think this PR will covert all test script :)

**Comment by Saran440** [comment]
@OCA/procurement-purchase-maintainers Can you help review and merge this please?

**Review by etobella — APPROVED** [review]

**Pull request merged**
