### PR TITLE
[FIX] add store=True

### PR DESCRIPTION
**Pull request by fmdl**
You use api.depends to update the status of purchase picking, with that you can use store='true'. Like that you cangroup_by picking_status in tree view.

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by sla-subteno-it** [comment]
👍

**Review by andhit-r — APPROVED** [review]
:+1:

**Comment by fmdl** [comment]
this commit generate this error, when you change the state of move or picking, and system is very slow.

if you remove  picking_ids.state in  @api.depends('picking_ids', 'picking_ids.state'), the error disappear, but the compute don't works.

ERROR openerp.osv.expression: Non-stored field purchase.order.picking_ids cannot be searched.

**Comment by pedrobaeza** [comment]
Please propose a new PR for amending this.

**Pull request merged**
