### PR TITLE
[ADD] purchase_request: Make product.template#purchase_request a property

### PR DESCRIPTION
**Pull request by hbrunn**
this way we can turn on the request workflow for a product per company

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
What happens if you already migrated to properties using https://github.com/OCA/purchase-workflow/pull/997?

**Comment by HviorForgeFlow** [comment]
> What happens if you already migrated to properties using #997?

Migrate will fail when quering this:
12.0-purchase_request-company-dep-route=# select id, coalesce(purchase_request, False) from product_template
12.0-purchase_request-company-dep-route-# ;
ERROR:  column "purchase_request" does not exist
LINE 1: select id, coalesce(purchase_request, False) from product_te...

@hbrunn fix conflicts as #999 has already been applied, Thanks!

**Comment by AaronHForgeFlow** [comment]
so then, either we don't touch version 12 or we adapt the scripts here.

**Review by AaronHForgeFlow — CHANGES_REQUESTED** [review]
so then we adapt the scripts here

**Comment by hbrunn** [comment]
rebased. The migration will be fine here if done already in v12 because it only kicks in when the [the column exists](https://github.com/OCA/purchase-workflow/pull/996/files#diff-78044130d89e82e899e67380e28ca732f2ba580a4d48732a8095fbc58b00cce8R7)

**Review by HviorForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
