### PR TITLE
[13.0][MIG] purchase_triple_discount

### PR DESCRIPTION
**Pull request by benwillig**
Duplicate of https://github.com/OCA/purchase-workflow/pull/912 but based on https://github.com/OCA/account-invoicing/pull/733

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @benwillig. could you cherry pick recent commit : https://github.com/OCA/purchase-workflow/pull/929

**Comment by benwillig** [comment]
Hi @legalsylvain, I already fixed the view during the migration. Do you want the v12 commit to appear in the history? Just asking to be sure

**Comment by legalsylvain** [comment]
> Hi @legalsylvain, I already fixed the view during the migration. Do you want the v12 commit to appear in the history? Just asking to be sure

No, it's ok ! Thanks for porting this module.

**Comment by chusamo** [comment]
@benwillig Hello, do you need help in order to merge this? I can help to you if you want

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1:

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Add account-invoicing to oca_dependencies.txt

**Pull request closed without merging**
