### PR TITLE
[12.0][FIX] purchase_request: allow Purchase users to see purchase requests

### PR DESCRIPTION
**Pull request by etobella**
Purchase Users should need to see purchase requests
#637

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]

**Comment by LoisRForgeFlow** [comment]
cc @AaronHForgeFlow

**Review by jarroyomorales — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
It makes sense to me. I think  in previous versions happens the same.

**Comment by HviorForgeFlow** [comment]
Allowing Purchase User belong to Purchase Request User don't allow that user to see PRs from other users, just generate their own ones. It can be done by manual configuration.

I can't see benefits of this fix.

@etobella

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
ping @etobella 
So this is a workaround to allow testing, isn't it?
I could not see previous tests on related PR.

**Comment by etobella** [comment]
The problem is, the order of execution. On previous repos the tests were not colliding, but now it is. The problem was that the user was trying to access stock requests but he was not allowed.

**Comment by etobella** [comment]
@HviorForgeFlow maybe this is a workaround for a test, But purcase users should be able to see who asked for something. Isn't it?

**Comment by HviorForgeFlow** [comment]
Then they should be Manager, or new group read only all, because Purchase Request Users can only see their own Purchase Requests.

@etobella

**Comment by etobella** [comment]
Good for me any of both options, @LoisRForgeFlow which option do you prefer?

**Comment by AaronHForgeFlow** [comment]
I vote for new group readonly all, it is less restrictive

**Comment by etobella** [comment]
If we want to add this kind of permissions, the simplest would be to add the permission directly to the Purchase user

**Comment by etobella** [comment]
I think now is enough @HviorForgeFlow

**Review by HviorForgeFlow — APPROVED** [review]
Ok! Better this way, thanks!

**Pull request merged**
