### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**
simplify the test config by using UNIT_TEST=1

### CODE REVIEW

**Comment by yvaucher** [comment]
:+1:

**Comment by lepistone** [comment]
:+1: thanks

**Comment by bwrsandman** [comment]
While you're at is, please remove .coveragerc as it is provided my MQT

**Comment by bwrsandman** [comment]
:+1:

**Comment by gurneyalex** [comment]
builds with this config take way to much time, and we are finding this difficult to cope with in OCA/vertical-ngo and we are reverting the change. I'm withdrawing this PR for now.

**Pull request closed without merging**
