### PR TITLE
[14.0][MIG] purchase_tier_validation

### PR DESCRIPTION
**Pull request by kittiu**
Dependencies

- [x] base_tier_validation https://github.com/OCA/server-ux/pull/226

### CODE REVIEW

**Comment by kittiu** [comment]
@SurachetS can you review this? 
If this got merged, you can then rebase and push again yours.
Thanks.

**Comment by SurachetS** [comment]
LGTM krub

**Comment by kittiu** [comment]
Ready for review.

@HviorForgeFlow

**Review by SurachetS — APPROVED** [review]
Functional Tested OK

**Review by HviorForgeFlow — APPROVED** [review]
Code reivew :+1:

**Comment by kittiu** [comment]
> Code reivew

Great thanks!

**Pull request merged**
