### PR TITLE
16.0 mig purchase_open_qty

### PR DESCRIPTION
**Pull request by santostelmo**
Migration of purchase_open_qty from 15.0 to 16.0

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review (got it running for about a month now)

**Review by dsolanki-initos — APPROVED** [review]
Functional review LGTM.

**Comment by HviorForgeFlow** [comment]
@santostelmo can you squash migration commits https://github.com/OCA/purchase-workflow/pull/1881/commits/cc027b2a64db8bc0e335182d025a7aa676ae43a6 and https://github.com/OCA/purchase-workflow/pull/1881/commits/973f1bf9eea6d366a5a8ce6629d35c5715e02bc7 ?

Thanks for your contribution!

**Comment by santostelmo** [comment]
@HviorForgeFlow done

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
