### PR TITLE
[FIX] Decimal precision parameter for products

### PR DESCRIPTION
**Pull request by clonedagain**
Supersedes https://code.launchpad.net/~numerigraphe-team/purchase-wkfl/7.0-fix-decimal-precision/+merge/223883
"In version 7 the name of the digital precision parameter for UoMs has changed : this branch updates the modules where the change is missing."
Rebased on 7.0 today

### CODE REVIEW

**Comment by clonedagain** [comment]
@pedrobaeza do you still agree with this please?

**Comment by pedrobaeza** [comment]
We have to see why Travis complains before giving my approval.

**Comment by clonedagain** [comment]
Looks like it fails on the mainline 7.0 branch I forked from, too, so I guess it's not related to my change?

**Comment by gurneyalex** [comment]
purchase_landed_costs tests are red (#22)

:+1: on this PR.

**Comment by max3903** [comment]
:+1:

**Comment by joaoalf** [comment]
:+1: 
lgtm.

**Pull request merged**
