### PR TITLE
10.0 purchase order line sequence

### PR DESCRIPTION
**Pull request by jpoa**
Cleaned the PR to only include the changes to the module purchase_order_line_sequence.

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Is this superseding this ? #425 In case it is, did you agreed @darshan-serpent to close the other PR?

There's a conflict with the latest changes related .pot files. Needs rebasing. It is happening in many opening Pull Requests

**Comment by MiquelRForgeFlow** [comment]
@jpoa could you rebase this PR?

**Comment by JordiBForgeFlow** [comment]
As there seems to be little activity on this PR, @mreficent can you superseed it and rebase?

**Comment by MiquelRForgeFlow** [comment]
Superseeded by https://github.com/OCA/purchase-workflow/pull/567. This PR can be closed.

**Pull request closed without merging**
