### PR TITLE
[16.0][IMP] purchase_order_line_menu: Remove form in action

### PR DESCRIPTION
**Pull request by EmilioPascual**
Cherry-pick https://github.com/OCA/purchase-workflow/pull/1845/commits/863b1dbab393a4957d1dece771aed6adb08d55b0 from pr https://github.com/OCA/purchase-workflow/pull/1845
Overwrite behaviour in pr: https://github.com/OCA/purchase-workflow/pull/1971.

### CODE REVIEW

**Review by kikopeiro — APPROVED** [review]
LTGM :+1:

**Review by hugo-cordoba — APPROVED** [review]
Thanks @EmilioPascual! LGTM!

**Comment by hugo-cordoba** [comment]
@pedrobaeza Hi!!

Can we merge this? We saw it here a while ago https://github.com/OCA/purchase-workflow/pull/1845

Best regards!

**Pull request merged**
