### PR TITLE
[16.0][MIG] purchase_order_line_sequence: Migration to 16.0

### PR DESCRIPTION
**Pull request by AungKoKoLin1997**
Standard migration base on https://github.com/OCA/purchase-workflow/pull/1933
Depends on: https://github.com/OCA/stock-logistics-workflow/pull/1316

@qrtl

### CODE REVIEW

**Comment by gbrito** [comment]
@AungKoKoLin1997 
You can fix tests here by including a pending PR by adding a separated commit w/ this change in tests-requirements.txt:

`odoo-addon-stock_picking_line_sequence @ git+https://github.com/OCA/stock-logistics-workflow@refs/pull/1316/head#subdirectory=setup/stock_picking_line_sequence`

**Comment by LoisRForgeFlow** [comment]
https://github.com/OCA/purchase-workflow/pull/1933 got merged, can you ensure that you have the lastest version included here?

**Comment by AungKoKoLin1997** [comment]
> #1933 got merged, can you ensure that you have the lastest version included here?

This PR is included  the latest version of https://github.com/OCA/purchase-workflow/pull/1933

**Comment by FreezeS** [comment]
Hi guys, is there a problem with this PR? I see it's been almost a year and it's not merged.

**Comment by StefanRijnhart** [comment]
Looks like we need https://github.com/OCA/purchase-workflow/pull/1990 in here as well.

**Comment by AungKoKoLin1997** [comment]
> Looks like we need #1990 in here as well.

I added the new commit.

**Review by StefanRijnhart — APPROVED** [review]
Thanks for the update!

**Comment by StefanRijnhart** [comment]
FYI I based my v17 migration on this PR. https://github.com/OCA/purchase-workflow/pull/2414

**Comment by AungKoKoLin1997** [comment]
@oca/purchase-workflow-maintainers
Can you please view this PR?

**Comment by AungKoKoLin1997** [comment]
@FreezeS Can you please review?

**Review by christian-ramos-tecnativa — APPROVED** [review]
LGTM

**Pull request merged**
