### PR TITLE
[17.0][MIG] purchase_tier_validation: Migration to 17.0

### PR DESCRIPTION
**Pull request by celm1990**
waiting for https://github.com/OCA/server-ux/pull/787

### CODE REVIEW

**Comment by bosd** [comment]
@celm1990 Can you please include commits from https://github.com/OCA/purchase-workflow/pull/1328

**Comment by celm1990** [comment]
> @celm1990 Can you please include commits from #1328

done, please update your review

**Review by bosd — APPROVED** [review]
LGTM

**Comment by celm1990** [comment]
@OCA/procurement-purchase-maintainers, could you please help me review this PR and merge it if it is OK?

**Comment by bosd** [comment]
Can we hold on a bit more? Couple of days? Later today I will open the refactor pr of the base module. 🙏

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
