### PR TITLE
[12.0][ADD] purchase_invoice_plan

### PR DESCRIPTION
**Pull request by kongrattapong**
## Ready to review.

### CODE REVIEW

**Comment by kittiu** [comment]
@kongrattapong is this ready for review? If so, please remove [WIP] from the PR name.

**Comment by kongrattapong** [comment]
> @kongrattapong is this ready for review? If so, please remove [WIP] from the PR name.

@kittiu ready to review krub

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
@Saran440 would you help review and test this

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Functional review it is a good feature.

Little comments:
- I miss access to purchase invoice plan view model, to list them, not just Invoice Plan tab on PO.
- Plan date is not propagated to Invoice when using creating all remaining bills. Not sure if in Bill Date or Due Date.
- Invoice plan can be only created on a draft PO, once is confirmed PO I can't manipulate it. I would like to have the ability to decide if I use Invoice Plan or not until my next step is create bill.

Do this comments make sense?

**Comment by kittiu** [comment]
Thank you @hveficent for your comment, let's address one by one,

> I miss access to purchase invoice plan view model, to list them, not just Invoice Plan tab on PO.

You mean, you want to have a new menu "Purchase Invoice Plan" as new menu? Just wonder what use case is it for?
Note: The intention of invoice plan is just a helper. Even there is a plan, you don't need to follow them all.

> Plan date is not propagated to Invoice when using creating all remaining bills. Not sure if in Bill Date or Due Date

It should be Bill Date. Is it not propagated? I will check.

> Invoice plan can be only created on a draft PO, once is confirmed PO I can't manipulate it. I would like to have the ability to decide if I use Invoice Plan or not until my next step is create bill.

We don't allow because, I afraid that, says, there is 10 installment and user used it for 3 installments. But then, he decided to edit the plan, I just afraid it won't be consistent anymore.

What I could do is, once PO created 1st invoice, we will disallow creating again, will this works?

**Comment by HviorForgeFlow** [comment]
> > I miss access to purchase invoice plan view model, to list them, not just Invoice Plan tab on PO.
> 
> You mean, you want to have a new menu "Purchase Invoice Plan" as new menu? Just wonder what use case is it for?
> Note: The intention of invoice plan is just a helper. Even there is a plan, you don't need to follow them all.

Maybe it this is not the use case, but: If I want to take an overview about all Invoice plans with my vendors I need to go 1 per 1 on their related purchase to see the plan and the status.

A Entry, in vendors like Vendor Invoice Plans calling a tree view with all Invoice Plans created by the system can help me to speed up my periodically revision. Not mandatory, nice to have.

> > Invoice plan can be only created on a draft PO, once is confirmed PO I can't manipulate it. I would like to have the ability to decide if I use Invoice Plan or not until my next step is create bill.
> 
> We don't allow because, I afraid that, says, there is 10 installment and user used it for 3 installments. But then, he decided to edit the plan, I just afraid it won't be consistent anymore.

It depends on the workflow of the users. I mean, I can't activate/deactivate invoice plan once I confirmed the order, if I forget to add my invoice plan or I reach a deal with vendor later than order confirmation to allocate payments in different installments.

A good first approach is:
> What I could do is, once PO created 1st invoice, we will disallow creating again, will this works?

**Comment by kittiu** [comment]
@hveficent let me enhance it first. Thanks for the constructive comment :+1:

**Comment by kittiu** [comment]
@hveficent Fixed all 3 points, you can make review again.
Thank you very much, they all good points.

**Review by HviorForgeFlow — APPROVED** [review]
@kittiu  I've been testing the module again, maybe Invoice Plan Tab could be located on Invoice App, not sure, it depends which users are interested on see that, nevertheless they also can get this information filetring Purchase Orders where Invoice Plan is set. So I think I was mistaken about point 1.

Other points are covered with new changes. 

LGTM :+1:

Let's see how perform this module on customers.

Thanks!

**Comment by kittiu** [comment]
@hveficent also, there is another module `purchase_deposit` which is already merged.
As both of them will create invoice, as separated module they are not good together (as they not aware of each other).
I am creating a new bridge module `purchase_invoice_plan_deposit` which will auto install if both are installed. I will let you know when it is ready. :)

Note: Featured that we just did for purchase_invoice_plan, I will port them also to sale_invoice_plan.

Thank you!

**Pull request merged**
