### PR TITLE
[10.0][MIG] purchase_order_analytic_search

### PR DESCRIPTION
**Pull request by gurneyalex**

### CODE REVIEW

**Comment by gurneyalex** [comment]
superseeds #462 and has improvements over  #519 such as allowing to search the account by name, and implementing "!=" and "not in" in search

cc @aheficent

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM :+1: 

BTW here @damdam-s asked for adding the analytic to the list view also, but form my side it's not blocking

**Review by grindtildeath — APPROVED** [review]

**Comment by damdam-s** [comment]
@aheficent not blocking. you can merge :smile:

**Comment by pedrobaeza** [comment]
Isn't better to use web_advanced_search_x2x that is generic an serve for any children field?

**Comment by gurneyalex** [comment]
@pedrobaeza This module also gets you a chance to display the field in form view and to have an easy filter. Searching PO by analytic account should not require an advanced search imo.

**Comment by pedrobaeza** [comment]
OK, just a suggestion for reducing your footprint :smile:

**Review by LoisRForgeFlow — APPROVED** [review]
:+1:

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
@gurneyalex  I'd appreciate a lot some comments here: https://github.com/OCA/account-invoicing/pull/298 :innocent:

**Pull request merged**
