### PR TITLE
[MIG] purchase_request_tier_validation: Migration to 16.0

### PR DESCRIPTION
**Pull request by imarulbala**
Depends on https://github.com/OCA/server-ux/pull/540 and https://github.com/OCA/purchase-workflow/pull/1653

### CODE REVIEW

**Comment by StefanRijnhart** [comment]
Please reword the commit in which you update the version number to `[MIG] purchase_request_tier_validation: Migration to 16.0`.

**Review by StefanRijnhart — APPROVED** [review]
Thanks! Code reviewed, ran tests and tested manually (locally, because of unmerged dependency base_tier_validation).

**Review by alan196 — APPROVED** [review]
Tested locally 👍

**Pull request merged**
