### PR TITLE
[12.0][MIG] purchase_location_by_line

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Standard migration.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
@aheficent @lreficent @bjeficent @jbeficent

**Review by tbaden — APPROVED** [review]
thanks for the work 👍 
I did a code review: LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
Tested on runbot :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍Tested in local.

**Pull request merged**
