### PR TITLE
[12.0][IMP] purchase_order_line_packaging_qty: add default packaging

### PR DESCRIPTION
**Pull request by MateuGForgeFlow**
Add default packaging in the product form, in the PO it will be added by default.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
> @HviorForgeFlow The merge process could not start, because of exception 403 Must have admin access to view repository collaborators..

Hi @pedrobaeza any idea on this message? Thanks!

**Comment by pedrobaeza** [comment]
https://twitter.com/PedroMBaeza/status/1438405500236963841?s=20

**Pull request merged**
