### PR TITLE
fix purchase order revision test and post_init_hook

### PR DESCRIPTION
**Pull request by eLBati**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks, that exactly what I was talking about

:+1:

**Comment by eLBati** [comment]
Travis is failing due to `purchase_discount`.
Just tested `purchase_discount` alone and tests failed even so.
@pedrobaeza are you aware of problems with tests of `purchase_discount`?

**Comment by pedrobaeza** [comment]
Have you rebased your branch against latest changes? I made a refactorization of that module and create tests for it, so when we merged, tests were passing. I'm launching just now a rebuild on branch to see if there's any change.

**Comment by pedrobaeza** [comment]
Well, as I have said, tests were passing, I have ordered a rebuild in 8.0 branch, but it's not happening, so I can't say you more until the rebuild is done and we can see the result.

**Comment by eLBati** [comment]
Let's wait :wink:

**Comment by jaronemo** [comment]
Dear Sir

Test...Ok…
image

image

**Comment by eLBati** [comment]
@jaronemo Thanks.

@pedrobaeza last 8.0 build has the same problem: https://travis-ci.org/OCA/purchase-workflow/builds/80804703
I opened https://github.com/OCA/purchase-workflow/issues/187

**Comment by pedrobaeza** [comment]
PR proposed. You can rebase when merged.

**Comment by eLBati** [comment]
green :green_heart:
:clap:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
