### PR TITLE
[13.0][FIX] purchase_order_secondary_unit, error selecting 2nd_uom when no product_id

### PR DESCRIPTION
**Pull request by kittiu**
Fix -> https://github.com/OCA/purchase-workflow/issues/1053

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
What about don't allow user to select anything until product_id is selected, using an or domain in readonly attribute?
```
attrs="{'readonly': ['|',('state', 'in', ('done', 'cancel')), ('product_id', '=', False)]}"
```

Form view needs to be fixed also

**Comment by kittiu** [comment]
> What about don't allow user to select anything until product_id is selected, using an or domain in readonly attribute?
> 
> ```
> attrs="{'readonly': ['|',('state', 'in', ('done', 'cancel')), ('product_id', '=', False)]}"
> ```
> 
> Form view needs to be fixed also

What ia the benefit? It change behavior, not just fix bug. :p

**Comment by HviorForgeFlow** [comment]
Maybe the current behavior is not the proper solution. Does it make sense to query for product_id equal 0? :P :P

**Comment by HviorForgeFlow** [comment]
I mean by design, you should not change any field that requires that the product was set until you set it.

**Comment by kittiu** [comment]
> I mean by design, you should not change any field that requires that the product was set until you set it.

Fixed!

**Comment by HviorForgeFlow** [comment]
I noticed Odoo use another strategy on sale model. They add a domain on the UoM to use same UoM category that the UoM in the product id: https://github.com/odoo/odoo/blob/13.0/addons/sale/models/sale.py#L1273-L1274

But as far I can see product_secondary_unit allows adding a UoM from another category as secondary.

So I'm not sure about the fix.

ping @pedrobaeza @rousseldenis

**Comment by pedrobaeza** [comment]
First you should see #1066 if it fixes the problem

**Comment by kittiu** [comment]
> First you should see #1066 if it fixes the problem

I tested those, they are not related. Same error there.

**Review by gaikaz — APPROVED** [review]
:shipit: Perfect

**Comment by HviorForgeFlow** [comment]
Add same domain here: 
https://github.com/OCA/purchase-workflow/pull/1074/files#diff-0e2f71df6f79dc375b0e0e9479c9f6c69ca1b85d5908a9fa2e6a2b574c866ecfR23

**Comment by kittiu** [comment]
> Add same domain here:
> https://github.com/OCA/purchase-workflow/pull/1074/files#diff-0e2f71df6f79dc375b0e0e9479c9f6c69ca1b85d5908a9fa2e6a2b574c866ecfR23

Sorry Hvior, not sure what is needed here. :P

**Review by HviorForgeFlow — APPROVED** [review]
Not problem, purchase order line form can't be accessed on edit mode

**Pull request merged**
