### PR TITLE
fix #95: fix purchase requisition line name_get

### LINKED ISSUE #95: purchase_requisition_bid_selection: Bids selection I guess `.name` missing somewhere!
Test on v8 only

Using the module purchase_requisition_bid_selection, when selecting products line (click on "Choose product line" in call for bids form). On the grouped line it's display "product.product(4,)" instead the name_get() result.

### PR DESCRIPTION
**Pull request by petrus-v**
This is a purpose to fix issue #95.

### CODE REVIEW

**Comment by rvalyi** [comment]
:+1:

**Comment by pedrobaeza** [comment]
:+1:

**Comment by yvaucher** [comment]
Thanks @petrus-v  :+1:

**Comment by lepistone** [comment]
I just realized your test was not in `__init__.py` so it wan't being run. No problem, I added it back, and it's :green_apple: .

**Comment by petrus-v** [comment]
@lepistone,

Oh yes, good catch! I use nosetest which doesn't require to add import to launch tests. Thanks

**Comment by lepistone** [comment]
@petrus-v OT: I'm interested in your setup for running odoo tests with nose. At the moment I use a little patch to odoo core to stop it from messing with test output, but it is far from ideal. Thanks!

**Comment by petrus-v** [comment]
Hi @lepistone,

I'm using [openerp_scripts](http://pythonhosted.org/anybox.recipe.odoo/scripts.html) from anybox.recipe.odoo

here a simple example of `buildout.cfg` config file to run test on that module

```
[buildout]
parts = odoo
versions = versions
find-links = http://download.gna.org/pychart/

[odoo]
recipe = anybox.recipe.openerp:server
version = git https://github.com/OCA/OCB odoo 8.0
addons = git https://github.com/OCA/server-tools community-addons/server-tools 8.0
         git https://github.com/OCA/purchase-workflow community-addons/purchase-workflow 8.0

eggs = PyPDF
       nose

openerp_scripts = nosetests=nosetests command-line-options=-d

[versions]
Werkzeug = < 0.10.0
```

bellow running commands

```
cd ~/openerp/OCA/purchase-workflow
~/openerp/odoo-sandbox/bin/python bootstrap.py -c buildout.cfg
bin/buildout -c buildout.cfg
createdb test_pw
bin/start_odoo -d test_pw -i purchase_requisition_bid_selection --stop-after-init
bin/nosetests -d test_pw -- -s -w community-addons/purchase-workflow/purchase_requisition_bid_selection/
```

> note that you have to use `--` to distinguish nose params, also do not miss nose `--failed` option! To re-run only tests that failed!

Hope it helps!

**Comment by lepistone** [comment]
thanks a lot!

**Pull request merged**
