### PR TITLE
[15.0][MIG] purchase_requisition_order_remaining_qty: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT41761

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @victoralmau please review

**Comment by pedrobaeza** [comment]
It seems there's an incompatibility between this module and `purchase_order_no_zero_price`. Please check.

Take also a look to the existing warnings and get rid off them in another PRs.

**Comment by ernesto-garcia-tecnativa** [comment]
@

> It seems there's an incompatibility between this module and `purchase_order_no_zero_price`. Please check.
> 
> Take also a look to the existing warnings and get rid off them in another PRs.

Pedro, I modified the tests and added the cost in the requisition created

**Review by hieulucky111 — APPROVED** [review]
LGTM
Code review

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
