### PR TITLE
[9.0][FIX][purchase_request_to_rfq] Adding PO lines in the PR lines view

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
This fix lets you add Purchase Order Lines in the Purchase Request Lines view.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
Perhaps, would it be good to raise an error if the user tries to add a PO line with a different product than the PR line?

**Review by LoisRForgeFlow — APPROVED** [review]
Looks great now! Thanks

**Review by gmeficent — COMMENTED** [review]
Code review and functional review :+1:

**Review by gmeficent — APPROVED** [review]

**Comment by gmeficent** [comment]
@aheficent , @rgarnau. Could you please review?

**Pull request merged**
