### PR TITLE
[16.0][MIG] purchase_merge: Migration to 16.0

### PR DESCRIPTION
**Pull request by flalexg**

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
It would be nice to increase code coverage during this migration, forcing to raise all _check_content Validation errors

**Review by HviorForgeFlow — APPROVED** [review]
Thank you for increasing the test coverage

**Review by AaronHForgeFlow — APPROVED** [review]
Code LGTM

**Review by MiquelRForgeFlow — APPROVED** [review]

**Pull request merged**
