### PR TITLE
fix travis build

### PR DESCRIPTION
**Pull request by gurneyalex**
test purchase_requisition_multicurrency together with
purchase_requisition_bid_selection

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1: if all green (obviously)

**Comment by pedrobaeza** [comment]
Well, it's still the same. I think it's better to provide a default value for the required field. Don't you think?

**Comment by jaronemo** [comment]
My test results are as follows, still problematic.Test different databases
image

**Comment by gurneyalex** [comment]
thanks @damdam-s for the fix. 

:+1:

**Comment by gurneyalex** [comment]
@damdam-s can you squash the first 3 commits?

**Comment by lmignon** [comment]
:+1:

**Pull request merged**
