### PR TITLE
[MIG] 14.0 purchase_quick

### PR DESCRIPTION
**Pull request by PierrickBrun**
depends on https://github.com/OCA/product-attribute/pull/755

### CODE REVIEW

**Comment by kittiu** [comment]
Test locally, with OCA/product-attribute#755
unit test and functional test OK.

**Comment by legalsylvain** [comment]
There are conflicts. Could you fix them ?

**Comment by sebastienbeau** [comment]
I flag the branch in WIP, as we are fixing some issue in the current implementation of the module (uom support for example).

Current improving PR is here and will be merged soon into this one : https://github.com/akretion/purchase-workflow/pull/10

**Review by sebastienbeau — APPROVED** [review]
LGTM code review and test

**Review by legalsylvain — COMMENTED** [review]
Hi pierrick. 

1) Could you squash all the 14.0 commit together, to make the review easier ? 

2) could you explain the incompatibility with ``purchase_order_type`` in a roadmap.rst file ? 

thanks !

**Comment by kevinkhao** [comment]
I am closing this branch because of several merges with 14.0, pick from 12, makes it hard for squashing/rebasing cleanly. Here is the clean PR/Branch https://github.com/OCA/purchase-workflow/pull/1213

**Pull request closed without merging**
