### PR TITLE
Fix oca logo

### PR DESCRIPTION
**Pull request by yvaucher**
Do not merge, this is a try to see if it fixes the loading of the OCA logo in REAME.rst

### CODE REVIEW

**Comment by pedrobaeza** [comment]
It seems to be the same.

**Comment by gurneyalex** [comment]
@pedrobaeza having an http served an image for an https served page is not a good practise.

**Comment by gurneyalex** [comment]
:+1:

**Comment by pedrobaeza** [comment]
@gurneyalex I mean that the problem is still there. See issue https://github.com/OCA/maintainer-tools/issues/57

**Comment by yvaucher** [comment]
@pedrobaeza @gurneyalex This was just a test, it's not better.

**Comment by yvaucher** [comment]
This has been resolve somehow

**Pull request closed without merging**
