### PR TITLE
[13.0][MIG] purchase_order_line_stock_available: Migration to 13.0

### PR DESCRIPTION
**Pull request by victoralmau**
Supersedes https://github.com/OCA/purchase-workflow/pull/870 to fix tests.

@Tecnativa TT27869

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
You can squash these commits together:

Selección_010

**Review by joao-p-marques — APPROVED** [review]
Code and functional review :+1:

**Comment by victoralmau** [comment]
It's ready to merge right?

**Pull request merged**
