### PR TITLE
[14.0][FIX] purchase_order_vendor_product, fix pre-commit error

### PR DESCRIPTION
**Pull request by kittiu**

### CODE REVIEW

**Comment by kittiu** [comment]
This module cause problem in other PR. but I really can't find reason for this error, any one knows how to fix?
@OCA/procurement-purchase-maintainers 

```
************* Module purchase_order_vendor_product
purchase_order_vendor_product/README.rst:29: [E7901(rst-syntax-error), ]  Duplicate implicit target name: "purchase order vendor products".
```

**Comment by HviorForgeFlow** [comment]
I think title in description needs to be removed

**Comment by kittiu** [comment]
Did that before in the previous force push. Wasn't work.

https://github.com/OCA/purchase-workflow/compare/4831d719b7ccbd8197b889e201af462de355b2fe..f14dbbdd69b426d06b1a2df8b858a3d49deb0559

**Pull request merged**
