### PR TITLE
[14.0][MIG] purchase_minimum_amount, purchase_order_approval_block

### PR DESCRIPTION
**Pull request by mathieudelva**
-  [x] depend on https://github.com/OCA/purchase-workflow/pull/1215

### CODE REVIEW

**Comment by kittiu** [comment]
@math0706 thanks for the migrations.
Can you split the migration?, 1 module for 1 PR please.

**Review by sebastienbeau — APPROVED** [review]
LGTM (code review)
The diff of migration is really small, see here : https://github.com/OCA/purchase-workflow/pull/1226/commits/9afbd81557f245feb2aa20b6c76b4fae577d66e8
and here https://github.com/OCA/purchase-workflow/pull/1226/commits/f28f0280fe6bb2d01d3f2d73dcfea42cc167bc57



So it's fine for me to have one PR for 2 modules

**Review by hparfr — APPROVED** [review]
Code read LGTM

**Pull request merged**
