### PR TITLE
8.0 fix purchase request to rfq terms jne

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
Fix terms PO into RFQ as the module is talking about creating RFQ. Change draft po into rfq terms too to be complient with odoo: a draft po is an rfq

Also provide the fixed .pot, and fr.po with the modifications

cc @jbeficent

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
:+1: Good points.

**Comment by JonathanNEMRY** [comment]
Thank you @jbeficent ! Could you please take a look and give me your opinion on this one too? https://github.com/OCA/purchase-workflow/pull/242 :smile:

**Comment by sbidoul** [comment]
:+1:

**Comment by adrienpeiffer** [comment]
:+1:

**Comment by JordiBForgeFlow** [comment]
Thanks!

**Pull request merged**
