### PR TITLE
[14.0][MIG] purchase_order_line_sequence manifest without stock_picking_line_sequence + installable

### PR DESCRIPTION
**Pull request by andreampiovesana**
Update manifest without stock_picking_line_sequence for possible circular dependences.
And set installable = True

### CODE REVIEW

**Comment by andreampiovesana** [comment]
no response?

**Review by matteoopenf — APPROVED** [review]

**Comment by matteoopenf** [comment]
LGTM

**Comment by matteoopenf** [comment]
@andreampiovesana  you shoudl fix the pre-commit

**Review by matteoopenf — COMMENTED** [review]
fix pre commit

**Comment by matteoopenf** [comment]
@andreampiovesana https://github.com/OCA/purchase-workflow/pull/1564 I fix the pre-commit

**Pull request closed without merging**
