### PR TITLE
[16.0][MIG] purchase_triple_discount: Migration to 16.0

### PR DESCRIPTION
**Pull request by ramiadavid**

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @ramiadavid : could you rebase once purchase_discount has been merged ? 
(this should solve conflict and red CI.)
thanks !

**Review by lehoangan — APPROVED** [review]

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi. could you check and cherry pick commits from pending PR that makes some fixes / improvment in previous versions ?

- https://github.com/OCA/purchase-workflow/pull/1185 by @legalsylvain on 12.0
- https://github.com/OCA/purchase-workflow/pull/1395 by @sergioeix on 14.0
- https://github.com/OCA/purchase-workflow/pull/1615 by  @ae-landoo on 15.0

Thanks ! 
let me know if you want some help.

Note : also a rebase is needed as there are conflict.

**Review by lehoangan — APPROVED** [review]
LGTM

**Review by StephaneMangin — APPROVED** [review]

**Pull request merged**
