### PR TITLE
[14.0][ADD] purchase_order_line_description_single_attribute

### PR DESCRIPTION
**Pull request by ilyasProgrammer**
Shows single value attributes name in the purchase order line description.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok 

equivalent of https://github.com/OCA/sale-workflow/tree/14.0/sale_order_line_description_single_attribute for PO

**Review by SicurSam — APPROVED** [review]
Functional ok!

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers good for merge? :)

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers when possible :)

**Comment by francesco-ooops** [comment]
> Functional ok
> 
> equivalent of https://github.com/OCA/sale-workflow/tree/14.0/sale_order_line_description_single_attribute for PO

@OCA/procurement-purchase-maintainers when you can :)

**Comment by HviorForgeFlow** [comment]
@ilyasProgrammer @francesco-ooops check if this development works for you. It is kind of more global than adding it directly the logic inside purchase scope.

https://github.com/OCA/product-attribute/pull/1194

**Comment by francesco-ooops** [comment]
@ilyasProgrammer this can be closed as https://github.com/OCA/product-attribute/tree/14.0/product_variant_attribute_name_manager has been merged

**Pull request closed without merging**
