### PR TITLE
[16.0][ADD] purchase_vendor_promotion

### PR DESCRIPTION
**Pull request by santostelmo**
This module allows you to visualise the start and end date of a vendor promotion during replenishment.
A vendor price is considered as a promotion if product supplier info is flagged as a `promotion`.

### Configure supplier info as promotion
image

### Replenishment with promotion period info
image

### CODE REVIEW

**Review by cyrilmanuel — APPROVED** [review]
not an expert but lgtm

**Review by trisdoan — APPROVED** [review]
LGTM :+1:

**Comment by trisdoan** [comment]
Hello @santostelmo, would you plz consider this add-on feature: https://github.com/camptocamp/purchase-workflow/pull/2

**Pull request merged**
