### PR TITLE
[IMP][14.0] Purchase_deposit:added button create_deposit

### PR DESCRIPTION
**Pull request by JoanMForgeFlow**
Improved the module of purchase deposit, by adding the possibility to just create the deposit and not the bill, or the two things.
@AaronHForgeFlow 
@JoanSForgeFlow

### CODE REVIEW

**Review by mariadforgeflow — APPROVED** [review]
LGTM!

**Comment by HviorForgeFlow** [comment]
WDYT @kittiu

**Review by AaronHForgeFlow — COMMENTED** [review]
Would it be good to hide the Create deposit button in the PO after the vendor bill is created?

Edit: well let's keep it just in case there is some late deposit

**Review by JoanSForgeFlow — APPROVED** [review]
Tested! LGTM

**Review by AaronHForgeFlow — COMMENTED** [review]
I am not sure if I understand, but it seems the button "Create deposit" is not fine:

1.- Create PO
2.- Create Deposit (without bills) --> a PO line is added
3.- Create vendor bill --> the deposit is not deducted on the bill.

**Comment by JoanMForgeFlow** [comment]
@AaronHForgeFlow 
you have two options, the first one is to create the deposit (a PO line is added), but latter manually you have to create your deposit bill (invocing -> vendors -> bill), to be deducted from the total amount of the vendor bill.
The second option, is to create the deposit and the deposit bill, and in the vendor bill it will be deducted.

So, @AaronHForgeFlow , you are missing the deposit bill.

**Comment by AaronHForgeFlow** [comment]
Ok, I would like some assistance on the creation of the deposit bill after the deposit is created. But I guess that is not trivial as the bill will be created for accountants.

**Review by AaronHForgeFlow — APPROVED** [review]
Functional + code

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by vvrossem** [comment]
> @AaronHForgeFlow you have two options, the first one is to create the deposit (a PO line is added), but latter manually you have to create your deposit bill (invocing -> vendors -> bill), to be deducted from the total amount of the vendor bill. The second option, is to create the deposit and the deposit bill, and in the vendor bill it will be deducted.
> 
> So, @AaronHForgeFlow , you are missing the deposit bill.

Hi @JoanMForgeFlow !
A late functional review: 
I've tested the option n°1 you mentioned (first use "Create deposit", then manually create the vendor bill):

https://user-images.githubusercontent.com/28013700/160088883-5423d87c-d7f8-4204-92dd-dbd016163619.mov

Is it a wanted behaviour to manually encode, on the vendor bill, a negative quantity to have the deposit deducted from the total amount? Or am I missing something?

**Comment by JoanMForgeFlow** [comment]
@vvrossem thanks for the review!
The idea of first creating the deposit and later manually making the bill is creating 2 bills in total, not just one.
So you make the deposit, then you go to invoicing -->bills and fill the autocomplete field,  for example in your case 3 new lines has been created, so you have to delete the 2 lines with the product (because you just want to bill the deposit), and only keep the deposit line. So when you register the payment and make the final bill, you are going to see how the deposit amount is deducted from the total amount.

**Comment by vvrossem** [comment]
@JoanMForgeFlow thank you for the explanation, got it !

**Pull request merged**
