### PR TITLE
[10.0][mig] subcontracted service

### PR DESCRIPTION
**Pull request by florian-dacosta**
V9 contributor/reviewers : 
@damdam-s @jbeficent @lreficent

### CODE REVIEW

**Review by damdam-s — APPROVED** [review]
:+1: thanks

**Review by LoisRForgeFlow — APPROVED** [review]
Great! :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
:+1:

**Comment by JordiBForgeFlow** [comment]
Thanks! Now merged!

**Pull request merged**
