### PR TITLE
[15.0][IMP] purchase_triple_discount: when purchase line created from selle…

### PR DESCRIPTION
**Pull request by ae-landoo**
…r, sets discount2 and discount3

Sets discount2 and discount3 when reordering rule is applied or route MTO.

### CODE REVIEW

**Review by bi-landoo — APPROVED** [review]

**Comment by ae-landoo** [comment]
@ramiadavid @MiquelRForgeFlow 
Hi, could you please review this changes? Thanks.

**Review by ma-landoo — APPROVED** [review]

**Comment by ae-landoo** [comment]
@pedrobaeza can you merge this? It is already approved.

**Comment by pedrobaeza** [comment]
It requires a PSC approval

**Comment by ae-landoo** [comment]
@pedrobaeza Can you review it?

**Comment by pedrobaeza** [comment]
Not using it currently

**Review by dreispt — APPROVED** [review]

**Comment by ae-landoo** [comment]
@dreispt Can you merge it?

**Review by chienandalu — CHANGES_REQUESTED** [review]
This is just missed in migration: https://github.com/OCA/purchase-workflow/blob/13.0/purchase_triple_discount/models/stock_rule.py#L11-L16

Just do as it was and add attribution if possible.

**Comment by ae-landoo** [comment]
@chienandalu We've checked what you've said and we see that that function isn't defined in stock_rule. It seems that in the migration to 14.0 someone forgot to add this functionality in the new correspondent model, which is purchase_order_line. That is why I'm trying to add it in that new model. If they merge my change, I could add it in 14.0 by cherry-picking it.

**Comment by chienandalu** [comment]
@ae-landoo Yes, I think the method changed from version to version, but the spirit is the same.

**Comment by ae-landoo** [comment]
@dreispt after the discussion, can you merge it?

**Comment by chienandalu** [comment]
I meant to cherry-pick and adapt the original contribution.

**Comment by ao-landoo** [comment]
@chienandalu The original commit when that function was added is the first commit from when the module was added to this repository. I added that commit author as a co-author to this commit if you see that OK.

**Comment by js-landoo** [comment]
@chienandalu i remember you this open PR. Can you check and approve it? Thanks.

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by pedrobaeza** [comment]
This should be rebased and check the CI.

**Comment by HviorForgeFlow** [comment]
@ae-landoo @js-landoo could you rebase the PR? Thanks

**Comment by HviorForgeFlow** [comment]
ping @ae-landoo @js-landoo

**Comment by HviorForgeFlow** [comment]
superseed https://github.com/OCA/purchase-workflow/pull/2406

**Pull request closed without merging**
