### PR TITLE
[13.0][FIX] Invoice tax calculation

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Fix Issue https://github.com/OCA/purchase-workflow/issues/880

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
Hi @NCS-75 @HaraldPanten ,
could you review the fix?

Thanks,

**Review by HaraldPanten — APPROVED** [review]
Functional review 👍 .

**Comment by HviorForgeFlow** [comment]
@kongrattapong

**Comment by NCS-75** [comment]
Lgtm on fonctional review
Thanks for your contribution

**Comment by ValentinVinagre** [comment]
please approve the PR @NCS-75

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
