### PR TITLE
Fix indentation error that might prevent check to be run

### PR DESCRIPTION
**Pull request by nbessi**

### CODE REVIEW

**Comment by eLBati** [comment]
:+1: can the travis build be re-launched?

**Comment by rvalyi** [comment]
:+1:  OK for the fix, but fragment_agreement test doesn't run pass yet...

**Comment by nbessi** [comment]
Restoring constraint seems to break the test putting this in WIP

**Comment by pedrobaeza** [comment]
It seems that this is not going to be continued, so I close.

**Pull request closed without merging**
