### PR TITLE
[13.0][MIG] - purchase_packaging 

### PR DESCRIPTION
**Pull request by sbejaoui**

### CODE REVIEW

**Review by ThomasBinsfeld — APPROVED** [review]

**Comment by rousseldenis** [comment]
@Cedric-Pigeon @OCA/procurement-purchase-maintainers

**Review by benwillig — APPROVED** [review]

**Comment by rousseldenis** [comment]
@benwillig Could you update commits comments from migration to 13.0 one to adopt the format `[FIX] purchase_packaging: (...)`? Thanks

**Review by dreispt — APPROVED** [review]
I don't think it is worth the trouble of modifying the early commit messages.

**Pull request merged**
