### PR TITLE
[17][MIG] purchase deposit: migration to 17.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Hi Hector! Can you please review this PR? Thanks!

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review ok. Working as expected. The dowpayments are being created correctly, and the line is added within the PO.

**Review by HviorForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
