### PR TITLE
[15.0][MIG] purchase_deposit

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration 

CC @ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Code review :+1:

**Review by JoanMForgeFlow — APPROVED** [review]
Looks great!
Tests are failing for: https://github.com/OCA/purchase-workflow/pull/1382

**Comment by HviorForgeFlow** [comment]
Test fail on this point also regarding purchase_deposit module:
https://github.com/OCA/purchase-workflow/runs/5566301732?check_suite_focus=true#step:8:111

**Review by vincent-cowboy — APPROVED** [review]
Functional test: OK
Code review: LGTM

If possible, complete `USAGE.rst` explaining the workflow to follow for both options:
- Create and View bills
- Create deposit (cf. https://github.com/OCA/purchase-workflow/pull/1340#issuecomment-1078886400)

Thank you for migrating this module!

**Review by kos94ok-3D — APPROVED** [review]
Functional test: OK

**Pull request merged**
