### PR TITLE
[15.0][MIG]purchase_isolated_rfq: Migration to 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Comment by bizzappdev** [comment]
Ready for the review

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Comment by Saran440** [comment]
@bizzappdev Hi, I implement this module by add new function for update value po from rfq for case copy=False

Could you merge this pr please https://github.com/BizzAppDev-Systems/purchase-workflow/pull/3

**Pull request closed without merging**
