### PR TITLE
[14.0][MIG] subcontracted_service

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* Depends on https://github.com/OCA/stock-logistics-warehouse/pull/1801.

@ForgeFlow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
LGTM, it creates RFQ when confirming sales order with kits with products that are subcontracted.

In v10 when confirming a sales order with a subcobtracted product it created an RFW as well, like it were a MTO for services. I think that makes no sense because the subcobtracted service must come with a storable product the company is selling. In any case that is how the module works in v10 (not in newer versions).

Then I guess some integration is needed MRP in order to create RFQ upon MOs that include subcontracted services, but that should be done in other module if that is the case.

:+1:  ok to refactor.

**Comment by LoisRForgeFlow** [comment]
> LGTM, it creates RFQ when confirming sales order with kits with products that are subcontracted.
> 
> In v10 when confirming a sales order with a subcobtracted product it created an RFW as well, like it were a MTO for services. I think that makes no sense because the subcobtracted service must come with a storable product the company is selling. In any case that is how the module works in v10 (not in newer versions).
> 
> Then I guess some integration is needed MRP in order to create RFQ upon MOs that include subcontracted services, but that should be done in other module if that is the case.
> 
> +1 ok to refactor.

Yes, indeed. Once this base module get merged, I'll propose a submodule to cover those usecases!

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Review by HviorForgeFlow — APPROVED** [review]
LGTM

**Comment by AaronHForgeFlow** [comment]
> > LGTM, it creates RFQ when confirming sales order with kits with products that are subcontracted.
> > In v10 when confirming a sales order with a subcobtracted product it created an RFW as well, like it were a MTO for services. I think that makes no sense because the subcobtracted service must come with a storable product the company is selling. In any case that is how the module works in v10 (not in newer versions).
> > Then I guess some integration is needed MRP in order to create RFQ upon MOs that include subcontracted services, but that should be done in other module if that is the case.
> > +1 ok to refactor.
> 
> Yes, indeed. Once this base module get merged, I'll propose a submodule to cover those usecases!

I cover the case of procuring a service upon the procurement of a storable product here: https://github.com/OCA/purchase-workflow/pull/2030

**Pull request closed without merging**
