### PR TITLE
[9.0] [purchase_request_to_rfq] - Fixes error that made it impossible to create request lines

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
cc @aheficent @JonathanNEMRY @adrienpeiffer

### CODE REVIEW

**Comment by Garamotte** [comment]
Using the create/write/unlink methods in computed fields is a bad practice, as these methods should not modify values in the database (these methods are called as onchanges, when the computed field is displayed in a view).

You should use a for loop instead (either using the `update` method, or a direct affectation).

**Comment by JordiBForgeFlow** [comment]
Thanks @sylvain-garancher !

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Comment by JonathanNEMRY** [comment]
:+1:

**Review by JonathanNEMRY — APPROVED** [review]

**Comment by aheficent** [comment]
I also did not realize of this bug before. With this fix it's working fine. :+1:  Tested on runbot + code review

**Review by AaronHForgeFlow — APPROVED** [review]
I also did not realize of this bug before. With this fix it's working fine. :+1: Tested on runbot + code review

**Review by Garamotte — APPROVED** [review]
Thanks.

@jbeficent I just created a PR on your own branch, to add a unit test for this bug.

**Pull request merged**
