### PR TITLE
12.0 MIG product_supplierinfo_qty_multiplier

### PR DESCRIPTION
**Pull request by legalsylvain**
Hi. Backport of product_supplierinfo_qty_multiplier from 13.0 to 12.0

(original V13 PR : https://github.com/OCA/purchase-workflow/pull/1264)

Note : This PR is build on top of https://github.com/OCA/purchase-workflow/pull/1796 to have the possibility to run pre-commit. Please review the other PR first.

- bd76601 : trivial commit to backport module from 13.0  to 12.0
- 56003ec : trivial typo fix
- da27a0e : Important fix. the call of super for the time being is not done at the good time. 
Typical use case :
a supplier sells beers by 6, at the unit price of 2€. if the quantity is superior to 60, the unit price is 1,90€.
Currently, if the buyer chooses 59 bottles, the quantity will be rounded to 60, but the price will be 2€. With this patch, the price is 1,90€.
- bffc540f : replace blocking warning by web_notify warning. So the user doesn't to click on the message, each time a quantity is rounded.
- 9cac198b : add me as coauthor / comaintainers.

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @victoralmau. Could you take a look on this PR ? 
I backported to 12.0 and once validated, I'll port the module to 16.0 with the extra commits.

thanks !

**Comment by legalsylvain** [comment]
Hi @victoralmau, sorry to bother you again, do you have some time on this PR?

**Comment by legalsylvain** [comment]
@victoralmau friendly reminder. if you have some time to review that PR (and the last commits that provides some fixes.)

**Review by victoralmau — APPROVED** [review]
Sorry for the delay in my review, I have been disconnected for a few days.

Code review OK.

When it is merged, will you be able to fwp those changes to upper versions?

**Comment by legalsylvain** [comment]
> When it is merged, will you be able to fwp those changes to upper versions?

Once merged, I planned to port this module and thoses changes into V16. (and also account_invoice_supplierinfo_update_qty_multiplier). available here in V12, waiting for the current PR : https://github.com/OCA/account-invoicing/pull/1413
If you use ``account_invoice_supplierinfo_update` modules, feel free to review.

**Review by quentinDupont — APPROVED** [review]

**Review by quentinDupont — COMMENTED** [review]
Code review OK !

**Pull request merged**
