### PR TITLE
[17.0][MIG] purchase_allowed_product: Migration to 17.0

### PR DESCRIPTION
**Pull request by achulii**

### CODE REVIEW

**Review by traitrantrobz — APPROVED** [review]
LGTM 👍 Can you squash the commits?

**Comment by leemannd** [comment]
Hello @achulii , thank you for your work. According to OCA's migration wiki, it would be welcome to have the administrative commits squashed togheter -> https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0 .

Could you have a look at it?

**Review by njeudy — APPROVED** [review]
A test on V17.0 community and enterprise and all is ok.

I add a new PR if using purchase_order_matrix module ( https://github.com/OCA/purchase-workflow/pull/2502 )  to keep filtering on purchase.order

**Review by HviorForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
