### PR TITLE
[16.0][MIG] purchase_partner_selectable_option

### PR DESCRIPTION
**Pull request by jaenbox**
Migration to v16.0. Changed the method "fields_view_get()" to "get_view()"

### CODE REVIEW

**Review by navarrorico — APPROVED** [review]
Functional review

**Review by flalexg — APPROVED** [review]
Code review. LGTM!

**Review by ChristianSantamaria — APPROVED** [review]
LGTM functional review 👍 

The first commit must be renamed:
[IMP] : pre-commit stuff
to
[IMP] purchase_partner_selectable_option: pre-commit stuff

**Review by hugo-cordoba — APPROVED** [review]
LGTM! (Code + Functional Review)

> Captura de pantalla de 2023-06-06 13-34-01

> Captura desde 2023-06-06 13-33-49

**Pull request merged**
