### PR TITLE
[11.0][MIG] purchase_order_approved

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Migration to v11.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
@pedrobaeza do I need to do something special to force the readme generation?

**Comment by JordiBForgeFlow** [comment]
@sbidoul should we remove the original README.rst file, if we are adding the readme folder?

**Comment by sbidoul** [comment]
You can leave it there, it will be overwritten during the nightly run. Alternatively you can pip install oca-maintainer-tools in a dedicated virtualenv and run oca-gen-addon-readme manually if you want to preview it.

**Review by HviorForgeFlow — APPROVED** [review]
:+1:

**Review by rousseldenis — APPROVED** [review]
Code review

**Review by MiquelRForgeFlow — APPROVED** [review]

**Review by JordiBForgeFlow — APPROVED** [review]

**Pull request merged**
