### PR TITLE
[9.0] [ADD] Purchase request mts mto rule

### PR DESCRIPTION
**Pull request by alan196**
I this PR I created a module to ADD compatibility of purchase_request_procurement with stock_mts_mto_rule module of stock-logistic-warehouse repo.

This override method _prepare_purchase_request_line method to call method get_mto_qty_to_order from https://github.com/OCA/stock-logistics-warehouse/blob/9.0/stock_mts_mto_rule/model/procurement.py#L37-L52 in order to verify stock before creating the PR

### CODE REVIEW

**Review by moylop260 — APPROVED** [review]

**Comment by alan196** [comment]
Runbot is red because it needs stock-logistics-warehouse repo. Somebody can help me to configure it in runbot, or use runbot_travis2docker

**Comment by moylop260** [comment]
> Runbot is red because it needs stock-logistics-warehouse repo. Somebody can help me to configure it in runbot, or use runbot_travis2docker

cc @gurneyalex @pedrobaeza 
Could you enable this repository for use it with travis2docker, please?

**Comment by gurneyalex** [comment]
@moylop260 @alan196 done, and rebuild triggered. Let's wait and see.

**Comment by moylop260** [comment]
@gurneyalex Thanks now runbot is green 👍

@alan196 codecov show a red... Could you add a test case?

**Comment by moylop260** [comment]
FYI the tests aren't using the inherited method screen shot 2016-11-29 at 12 07 21 pm

**Comment by alan196** [comment]
@moylop260 now is tested.
@jbeficent What do you think?

**Review by SaraiOsorio — APPROVED** [review]

**Comment by alan196** [comment]
@pedrobaeza could you check this?

**Comment by pedrobaeza** [comment]
Sorry, no time now for reviewing

**Comment by alan196** [comment]
@nhomar @jjscarafia @dreispt could you check this?

**Comment by rafaelbn** [comment]
Could you please add in Usage section how to test it? Thanks

**Comment by alan196** [comment]
@rafaelbn The change is done.
Could you review it please?
Thanks in advance

**Comment by AaronHForgeFlow** [comment]
I configured a product with the proper routes MTO + MTS and Buy. Marked Purchase request and added a vendor. I created a SO for more qty than the qty available and I confirmed the SO. The procurement is correctly created and the route in the procurement is set correctly. However neither the Purchase Request  nor the PO are created. What am I missing here?

**Pull request closed without merging**
