### PR TITLE
[11.0][FIX] purchase_request_tier_validation

### PR DESCRIPTION
**Pull request by AdriaGForgeFlow**
Fix to be included after [server-ux/76](https://github.com/OCA/server-ux/pull/76) is merged.

cc ~ @Eficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: tested with base tier validation

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by sbidoul** [comment]
@jbeficent in such case you don't need to retry yourself. I'll see to clarify the message.

**Comment by JordiBForgeFlow** [comment]
@sbidoul ahh, thanks.

**Pull request closed without merging**
