### PR TITLE
[FIX][purchase_order_line_sequence] restore installable

### PR DESCRIPTION
**Pull request by matteoopenf**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Oh, wait, I see that it's not needed anymore.

**Comment by matteoopenf** [comment]
How can I Have the same function without module?

I don't understand, there is an option in odoo 14.0?

Thanks @pedrobaeza

**Comment by pedrobaeza** [comment]
Which function? The line resequenciation is already in core, and now also the propagation of such sequence to invoices.

**Comment by matteoopenf** [comment]
> Which function? The line resequenciation is already in core, and now also the propagation of such sequence to invoices.

The number at left of any purchase.order.line

**Comment by pedrobaeza** [comment]
I see. @rousseldenis did you take that into account?

**Comment by rousseldenis** [comment]
@matteoopenf @pedrobaeza Yes, we could re-activate this one, but that needs to change the code as there are now code duplicates (account move line generation, ...). If the aim of this is to display the sequence, I would prefer making a new module purchase_order_line_sequence_form or something like that. What do you think ?

**Comment by pedrobaeza** [comment]
For this version I would say to keep the module name, but rip out the duplicated code, and rename on next version

**Comment by rousseldenis** [comment]
> For this version I would say to keep the module name, but rip out the duplicated code, and rename on next version

Ok, @matteoopenf could you adapt code and tests ?

**Comment by matteoopenf** [comment]
I will try to adapt the code next week 

Thanks for the help 

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 17 set 2022, alle ore 15:14, Denis Roussel (ACSONE) ***@***.***> ha scritto:
> 
> ﻿
> For this version I would say to keep the module name, but rip out the duplicated code, and rename on next version
> 
> Ok, @matteoopenf could you adapt code and tests ?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by oreju** [comment]
@matteoopenf Hello, any update on this one? Thanks!

**Comment by matteoopenf** [comment]
> @matteoopenf Hello, any update on this one? Thanks!

Hi, actually I haven't time to continue the work

**Comment by matteoopenf** [comment]
@oreju you feel free to superseed

**Comment by matteoopenf** [comment]
> > For this version I would say to keep the module name, but rip out the duplicated code, and rename on next version
> 
> Ok, @matteoopenf could you adapt code and tests ?

I actually I haven't time to adapt code and test

**Review by bosd — COMMENTED** [review]
Odd, Can't see the changes which are reqeusted. Code seems good to me. Shall I approve this one?

**Comment by bosd** [comment]
@pedrobaeza  Can you elaborate which changes you want to see on this pr?
(I can only see that you request changes, but it does not show the details)

**Comment by pedrobaeza** [comment]
This module is not needed anymore in 14.0, as it's a native feature.

**Comment by matteoopenf** [comment]
> This module is not needed anymore in 14.0, as it's a native feature.

which is the module add the function?

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Comment by bosd** [comment]
> This module is not needed anymore in 14.0, as it's a native feature.

Maybe I'm confused.. about this module. 
It appears to do 2 things:


1.
>  The sequence in PO line is propagated to the Stock moves

2.
> The sequence number appears in the PO form view and in the report.


function 1 has become a native function. 

Number 2 as well??
If so, Can we add instructions how to activate the sequence numbers on po views and reports??
(I couldn't find how to activate the sequence line number on po's, on odoo demo)

**Comment by bosd** [comment]
@matteoopenf  Can you re-trigger github actions?
Would like to test this on runboat. 
(logs on failling tests are unavailable right now)

**Comment by matteoopenf** [comment]
> @matteoopenf Can you re-trigger github actions? Would like to test this on runboat. (logs on failling tests are unavailable right now)

I push an empty commit

**Comment by matteoopenf** [comment]
@bosd is ready

**Comment by bosd** [comment]
Thanks,
Functional test --> Line numbers are added correctly on po form view and report.
Tests need to pass to be able to merge this one

**Comment by pedrobaeza** [comment]
The module should be cleaned of code that is already in core, like picking or invoice sequence transfer.

**Comment by matteoopenf** [comment]
> The module should be cleaned of code that is already in core, like picking or invoice sequence transfer.

Can you 

> The module should be cleaned of code that is already in core, like picking or invoice sequence transfer.

thank you @pedrobaeza  for clarification, but i don't understand which is the part of the code I should remove.
If you explain which part I or someone can fix this part of code.

thank you in advance

**Comment by pedrobaeza** [comment]
If as stated, this is done in core, methods like this one should be removed:

https://github.com/OCA/purchase-workflow/blob/70c9533c665ae07d5eb98bedd56c1a3e2e0c34a6/purchase_order_line_sequence/models/purchase.py#L28

**Comment by matteoopenf** [comment]
https://github.com/OCA/purchase-workflow/pull/1933 this PR fix the problem I close that

**Pull request closed without merging**
