### PR TITLE
[MIG] [15.0] purchase_quick to 15.0

### PR DESCRIPTION
**Pull request by angelgarciadelachica**
supersedes: #1721

### CODE REVIEW

**Comment by angelgarciadelachica** [comment]
@ValentinVinagre @HaraldPanten @manuelregidor

**Comment by angelgarciadelachica** [comment]
Hi @pedrobaeza 
I have tried to use a temporary reference to another PR as explained in the following [link](https://github.com/OCA/maintainer-tools/wiki/Use-temporary-reference%28s%29-to-another-pull-request%28s%29). 
The PR I want to create the temporary reference to is https://github.com/OCA/product-attribute/pull/1283.
Also, I have added the product-attribute repository to the oca_dependencies.txt file, but I can't get it to pass the tests.
Am I missing something or have I made a mistake?
Thank you very much

**Comment by pedrobaeza** [comment]
The problem is in one the tests: https://github.com/OCA/purchase-workflow/actions/runs/4293148002/jobs/7480467126#step:8:341

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza 

I think this one could be merged --> https://github.com/OCA/product-attribute/pull/1283 (dependency for this module)

Once the dependency is merged, would we need to change anything else here in order to make this PR mergeable? Apart of changing the requirements back again.

THX in advance.

**Comment by pedrobaeza** [comment]
The other PR doesn't have any review.

**Comment by HaraldPanten** [comment]
> 

Now it has 2 :speak_no_evil:

**Review by HaraldPanten — APPROVED** [review]
LGTM

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Comment by HaraldPanten** [comment]
@pedrobaeza do you mind merging this one? THX!

**Pull request merged**
