### PR TITLE
[FIX] migrates the purchase_state field to v9.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR introduces a migration script that covers the migration of the purchase_state field to v9 and onwards.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
Tested locally in a demo database. :+1:

**Review by MiquelRForgeFlow — APPROVED** [review]
:+1:

**Comment by JordiBForgeFlow** [comment]
@adrienpeiffer Do you agree with this?

**Comment by JordiBForgeFlow** [comment]
cc @gmeficent

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Pull request merged**
