### PR TITLE
[17.0][MIG] purchase_invoice_plan: Migration to 17.0

### PR DESCRIPTION
**Pull request by imlopes**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@imlopes Could you check tests ? Thanks

**Comment by imlopes** [comment]
> @imlopes Could you check tests ? Thanks

It's done ! :D

**Comment by rousseldenis** [comment]
@imlopes Thanks.

Next time, don't hesitate to follow this : https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0#technical-method-to-migrate-a-module-from-160-to-170-branch

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
