### PR TITLE
[12.0][ADD] purchase_default_terms_conditions

### PR DESCRIPTION
**Pull request by marcelsavegnago**
This module allows you to configure standard terms and conditions for purchase orders. This functionality is similar to the functionality of sales orders.

### CODE REVIEW

**Review by mileo — APPROVED** [review]
LGTM: Tested in runbot

**Review by jpcarassato — APPROVED** [review]
Teste Ok!

**Comment by marcelsavegnago** [comment]
@OCA/procurement-purchase-maintainers I appreciate if this PR can be merged or revised by you.

**Pull request merged**
