### PR TITLE
[15.0][MIG] purchase_order_line_packaging_qty

### PR DESCRIPTION
**Pull request by ChrisOForgeFlow**
Standard Migration
@ForgeFlow

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ChrisOForgeFlow Odoo has done this in core :smiley: 

I'm currently investigating if it's 100% done.

**Comment by rousseldenis** [comment]
See #1672

**Comment by LoisRForgeFlow** [comment]
@ChrisOForgeFlow Indeed, I think the changes proposed by @rousseldenis in v16 also apply to v15.

**Comment by rafaelbn** [comment]
@ChrisOForgeFlow please check https://github.com/OCA/purchase-workflow/pull/1672

@LoisRForgeFlow ping ! :-)

**Pull request closed without merging**
