### PR TITLE
[16.0] [IMP] purchase_delivery_split_date: Fix key access to date dict

### PR DESCRIPTION
**Pull request by yassine-rhimi**

### CODE REVIEW

**Comment by yassine-rhimi** [comment]
Hello, why hasn't this merge been merged yet? It's urgent for my work. thanks to check it

**Comment by HviorForgeFlow** [comment]
@yassine-rhimi could you enhance commit message? something like
[IMP] p_delivery_split_date: Fix key access to date dict 

(or so)

**Comment by francesco-ooops** [comment]
hi @yassine-rhimi , thanks for your PR! please check here the guidelines on contributing: https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

check specifically how PR titles and commit names should be formatted.

PRs are merged after two positive reviews; you have more chances to receive them if you explain why this change is useful, and if you review other PRs and ask for a review in return.

**Comment by yassine-rhimi** [comment]
I don't understand how I can commit names should be formatted? , "can you give me an example please". 
 And here's my problem when I use your module,The error is "Error when saving the order after adding order lines (from a confirmed order) and changing the " expected arrival date" after confirmation.
  I add this PR to use the get method to retrieve the value associated with date_key from pickings_by_date 
  I'm blocked by our module can you merge it please?
  thank you for your understanding

**Comment by francesco-ooops** [comment]
@yassine-rhimi go with: 

[IMP] purchase_delivery_split_date: Fix key access to date dict 

You can use the same format for the PR title, just add version at the beginning, eg: 

[16.0] [IMP] purchase_delivery_split_date: Fix key access to date dict 

For merge, you need to have two positive reviews, as I said in previous comment the best way to get one is to review some other open PR and ask for a review in return.

**Comment by yassine-rhimi** [comment]
Hello, I change the format of the PR title. Thanks to check it and merge it

**Comment by francesco-ooops** [comment]
@yassine-rhimi the commit name

**Comment by yassine-rhimi** [comment]
@francesco-ooops The commit name has changed. Please check

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers anyone available for a review of new contributor @yassine-rhimi ?

**Comment by yassine-rhimi** [comment]
Hello, why hasn't this merge been merged yet? It's urgent for my work. thanks to check it

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
