### PR TITLE
[16][MIG] purchase_lot

### PR DESCRIPTION
**Pull request by florian-dacosta**
standard migration

Depends on https://github.com/OCA/sale-workflow/pull/2282

@Kev-Roche

### CODE REVIEW

**Review by Kev-Roche — APPROVED** [review]
LGTM functional review

**Comment by florian-dacosta** [comment]
@HviorForgeFlow would you mind doing a small review on this one ? Changes from last version are trivial

**Review by andreampiovesana — APPROVED** [review]
LGTM

**Pull request merged**
