### PR TITLE
[FIX] purchase_quick: add 'warehouse' and 'to_date' in context

### PR DESCRIPTION
**Pull request by HekkiMelody**
This is necessary to properly compute stock fields.

This is the equivalent of commit
5d26b94ed0653f0168e4a6ac34aa1b56d51d5d4f in OCA/sale-workflow for module sale_quick ( https://github.com/OCA/sale-workflow/pull/2245 )

In addition, this commit adds the same hooks that sale_quick has for potential future extensions.

### CODE REVIEW

**Comment by francesco-ooops** [comment]
@ivantodorovich what do you say? Equivalent to your https://github.com/OCA/sale-workflow/pull/2245

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by ivantodorovich — APPROVED** [review]
Makes sense :)

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
