### PR TITLE
[15.0][IMP] purchase_request - multi currency

### PR DESCRIPTION
**Pull request by Saran440**
Add field currency in purchase request and send it to RFQ

Purchase Request
- Add currency view and can see with multi currency group
Selection_024

RFQ
- Received currency from Purchase Request
Selection_025

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by Taewii23** [comment]
If Purchase Request has exception rule, should calculate estimated cost to THB and check the committee rules
Selection_012
Selection_013

**Comment by Saran440** [comment]
@Taewii23 Thank you for your comment but this error message from https://github.com/OCA/l10n-thailand/pull/333
not this pr. Can you test it again, please?

**Review by PatthamaCH — APPROVED** [review]
OK

**Pull request merged**
