### PR TITLE
[14.0][ADD] purchase_partner_approval

### PR DESCRIPTION
**Pull request by Nikul-OSI**

### CODE REVIEW

**Comment by dreispt** [comment]
This is contributed under the OSI ECLA.

**Comment by dreispt** [comment]
@Nikul-OSI This looks great! Will do some functional tests.

**Review by dreispt — APPROVED** [review]

**Review by patrickrwilson — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@Nikul-OSI @dreispt this module makes it almost impossible to use OCA purchase-workflow runboat for testing, as vendors cannot be selected in PO unless validated (currently only selectable vendor is a demo vendor named "Anna", provided by some other module). 

It took me quite some scanning to find which of the 90+ modules in this repo was responsible for the behavior... this is not ideal for us functionals. Would it be possible for you to add some demo data approving the base runbot demo vendors, or find some other workaround not to disrupt too much basic features?

Thanks a lot!

**Comment by francesco-ooops** [comment]
@Nikul-OSI @dreispt kind reminder if you find the time to improve this, thank you :)

**Comment by HekkiMelody** [comment]
Fixed here: https://github.com/OCA/purchase-workflow/pull/2090

**Pull request merged**
