### PR TITLE
[11.0] [purchase_open_qty] introduces boolean fields to make it easier to find orders with pending (or not pending) quantity to receive/invoice.

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@ageficent @aheficent

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM, it adds more flexibility for the user.

**Review by AdriaGForgeFlow — APPROVED** [review]
Code and functional review :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review  :+1:

**Pull request merged**
