### PR TITLE
[9.0][ADD] product_supplier_code_purchase

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Product Supplier Code Purchase
==============================

This module adds to the purchase order line the supplier code defined in the
product.

Usage
=====

To use this module:

#. Go to 'Purchase' and open a Purchase Order.
#. If the vendor has defined some code for any purchase order line they will be
   displayed in the line under the column 'Product Supplier Code'.

### CODE REVIEW

**Comment by MiquelRForgeFlow** [comment]
You need to rebase. This way you will include the fix to make the travis green 😉

**Comment by LoisRForgeFlow** [comment]
@mreficent Done, thanks! just for info, where has the fix been done?

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Beautiful

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM :+1:

**Pull request merged**
