### PR TITLE
[14.0][IMP] purchase_order_vendor_product:  fix description, add to file roadmap

### PR DESCRIPTION
**Pull request by dessanhemrayev**

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
integration to readme - module is not working correctly with matrix

**Review by SicurSam — APPROVED** [review]
LGTM

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers minimum change to description, can you please merge?

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers

**Pull request merged**
