### PR TITLE
[13.0][MIG] purchase_work_acceptance

### PR DESCRIPTION
**Pull request by ps-tubtim**

### CODE REVIEW

**Review by HviorForgeFlow — COMMENTED** [review]
Check Travis

**Comment by kittiu** [comment]
Functional tested OK!

**Review by kittiu — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@ps-tubtim rebase + precommit required as it changed slightly

**Comment by kittiu** [comment]
@HviorForgeFlow done on behalf of @ps-tubtim

**Pull request merged**
