### PR TITLE
[14.0] Refactor purchase_delivery_split_date (support new PO line or increased qty on a confirmed PO)

### PR DESCRIPTION
**Pull request by sebalix**
Port of:
- https://github.com/OCA/purchase-workflow/pull/1246

### CODE REVIEW

**Comment by i-vyshnevska** [comment]
@sebalix can you rebase pls

**Comment by sebalix** [comment]
Rebased

**Comment by jbaudoux** [comment]
I just included this change: https://github.com/OCA/purchase-workflow/pull/1246#discussion_r822596479

**Comment by jbaudoux** [comment]
@sebalix Can you mark it as ready to merge ?

**Comment by sebalix** [comment]
@ps-tubtim @HviorForgeFlow @ValentinVinagre @HaraldPanten @kittiu @SurachetS Hello, as you already participate to the migration+review of 13.0 and 14.0 versions of this addon, your reviews are welcome on this one :)

We use this refactoring since April 2021 (13.0 and 14.0) and it's working well.
ping @jbaudoux

**Review by ajaniszewska-dev — APPROVED** [review]

**Review by jbaudoux — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
Could you squash fixup commits? Thanks!

**Pull request merged**
