### PR TITLE
[16.0][mig] purchase_quick

### PR DESCRIPTION
**Pull request by PavarunCh**
Standard migration to 16.0 :100:  
Rename field `name` in `product.suplierinfo` model changed to `partner_id`.

### CODE REVIEW

**Comment by flalexg** [comment]
@PavarunCh can you add the module in the task migration? And do you need help for the tests?

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @PavarunCh. Could take a look on red test, and rebase to relanch the runbaot ? 

thanks !

**Comment by legalsylvain** [comment]
Superseded by #2171

**Pull request closed without merging**
