### PR TITLE
[15.0][MIG] purchase_requisition_grouped_by_procurement: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
@tecnativa TT41760

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @victoralmau please review

**Review by victoralmau — APPROVED** [review]
Code review OK.

**Comment by pedrobaeza** [comment]
/ocabot migration purchase_requisition_grouped_by_procurement

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
