### PR TITLE
[FIX] purchase_reception_notify: Use stock move quantity done to show reception quantity notification

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
CC @ForgeFlow @rhendersonLulzbot

### CODE REVIEW

**Review by JordiMForgeFlow — COMMENTED** [review]
Code review LGTM 👍🏼

**Review by JordiMForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Comment by pedrobaeza** [comment]
@sbidoul definitively something weird is happening with the check of the permissions.

**Comment by sbidoul** [comment]
Probably a permissions issues with the token I created yesterday. @HviorForgeFlow can you please retry ?

**Pull request merged**
