### PR TITLE
[9.0][FIX] purchase_discount: Fix calculation order taxes with globally round method

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check how is this done on v10 because I think this one is too much complicated.

**Comment by sergio-teruel** [comment]
It is the same

**Comment by sergio-teruel** [comment]
Sorry it is the same in core....

**Comment by pedrobaeza** [comment]
It's not the same. Please check it again. You are not being very friendly with inheritance.

**Pull request closed without merging**
