### PR TITLE
Added missing file report_purchase_order.xml

### PR DESCRIPTION
**Pull request by sergioeix**

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
thanks !

**Review by flotho — APPROVED** [review]
indeed !
thanks

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Code looks great!
So please:
1. Squash both commits and add a proper commit message (something like: [FIX] p_triple_discount: Add discount 2/3 to PO Report )
2. Sort data __manifest__ alphabetically

thank you for the contribution!

**Comment by HviorForgeFlow** [comment]
@sergioeix could you attend comments? thanks!

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Rewrite commit message like [FIX] purchase_triple_discount: <SHORT EXPLANATION>

**Pull request closed without merging**
