### PR TITLE
[FIX][purchase_partial_invoicing] All line quantity is invoiced when you set zero on the invoicing wizard.

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Please check Travis status

**Comment by adrienpeiffer** [comment]
@pedrobaeza I think that is a connection issue with github. I think I don't have superpower to restart the travis build ... Could you restart the build for me ?

**Comment by pedrobaeza** [comment]
There are pylint errors also. I restarted anyway.

**Comment by adrienpeiffer** [comment]
Thanks Pedro, I'll check PyLint isssues once the build is finished

**Review by andhit-r — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
