### PR TITLE
[ADD] purchase_request: Make product.template#purchase_request a property

### PR DESCRIPTION
**Pull request by hbrunn**
this way we can turn on the request workflow for a product per company

v13 PR in #996

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can't use the same field name for the new company dependent field, as the SQL column is dropped. If I don't remember bad, you can't even use pre-migration for renaming the column, as it's immediately dropped when Python is loaded.

**Comment by pedrobaeza** [comment]
And another thing: this is not `[ADD]`, but `[IMP]`, as you are not adding a module.

**Comment by hbrunn** [comment]
the migration script worked just fine when I developed this, can you point to some code that's supposed to drop the column?

**Comment by StefanRijnhart** [comment]
@hbrunn It's probably https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_model.py#L691 that Pedro is referring to. When the field's xmlid is found to be missing after the upgrade, the column is dropped. But it might be that that only happens after the migration script has already run. Did you test on openupgrade? We disabled the dropping of columns there.

**Comment by hbrunn** [comment]
this happens in https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/models/ir_model.py#L1673 which is called after all migration scripts have run: https://github.com/odoo/odoo/blob/12.0/odoo/modules/loading.py#L473

I think the sentiment is from previous versions where property fields were actually function fields, there indeed the column was dropped immediately.

**Comment by StefanRijnhart** [comment]
Ah yes, the fields record stays on so that would not drop the column.

**Review by HviorForgeFlow — APPROVED** [review]
migration process tested
LGTM :+1:

**Comment by pedrobaeza** [comment]
Good that the process has improved. Indeed the problem was detected in 10.0.

**Review by AdriaGForgeFlow — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]

**Pull request merged**
