### PR TITLE
[9.0][FIX]purchase_request: fix group_purchase_request_user

### PR DESCRIPTION
**Pull request by zakiuu**

### CODE REVIEW

**Review by adrienpeiffer — APPROVED** [review]
:+1:

**Review by JordiBForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
:+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Comment by JordiBForgeFlow** [comment]
Thanks @zakiuu !

**Pull request merged**
