### PR TITLE
[FIX] purchase_discount: take into account returned moves in order set discount for invoice line vals

### PR DESCRIPTION
**Pull request by ozono**
Now, in purchase_discount module discount is set for returned moves in invoice line calculation.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
A test for this would be appreciated.

**Comment by ozono** [comment]
Unit test added to PR

**Comment by pedrobaeza** [comment]
Please fix pylint issues:

```
purchase_discount/tests/test_purchase_discount.py:73:37: W291 trailing whitespace
purchase_discount/tests/test_purchase_discount.py:76:29: E231 missing whitespace after ':'
purchase_discount/tests/test_purchase_discount.py:85:1: W293 blank line contains whitespace
purchase_discount/tests/test_purchase_discount.py:85:1: W391 blank line at end of file
```

**Comment by ozono** [comment]
Fixed. Sorry for the inconvenience.

**Review by pedrobaeza — APPROVED** [review]
Thanks for the PR.

@lmignon, as you use this module, your review is welcome.

**Comment by pedrobaeza** [comment]
@lmignon any possibility of reviewing this?

**Comment by ozono** [comment]
Any news about this?

**Comment by pedrobaeza** [comment]
2 approvals are needed for merging, but as I have checked that is all correct and nobody is interested, I merge.

**Pull request merged**
