### PR TITLE
[10.0] Port purchase_commercial_partner

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by antoniocanovas** [comment]
Must the invoice inherit the new field?

**Comment by alexis-via** [comment]
@antoniocanovas The field "commercial_partner_id" already exists on account.invoice, cf addons/account/models/account_invoice.py line 317

**Review by andhit-r — APPROVED** [review]
:+1:

**Comment by alexis-via** [comment]
This module is required for the v10 migration of the EDI project, cf https://github.com/OCA/edi/pull/14
It's ready to merge.

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by rafaelbn — APPROVED** [review]

**Pull request merged**
