### PR TITLE
[15.0][MIG] purchase_invoice_plan: Migration to 15.0

### PR DESCRIPTION
**Pull request by TheerayutEncoder**
Migration Purchase Invoice Plan to odoo v15.0

@Saran440 
@newtratip

### CODE REVIEW

**Comment by TheerayutEncoder** [comment]
Reopen pull request after module purchase_open_qty got merged.

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by bizzappdev — CHANGES_REQUESTED** [review]
Code looks good. 
but you have migration and pre commit changes commit together
please follow the standards https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0#how-to

**Comment by Saran440** [comment]
@bizzappdev Fixed, Can you check and approve, please?

**Review by bizzappdev — APPROVED** [review]
code LGTM

**Pull request merged**
