### PR TITLE
[17.0][MIG] purchase_warn_message: Migration to 17.0

### PR DESCRIPTION
**Pull request by RogerSans**
Standard migration
T-6498

@HaraldPanten 
@ValentinVinagre 
@luis-ron

### CODE REVIEW

**Review by luis-ron — APPROVED** [review]
Functional Review: LGTM 👍🏻

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HaraldPanten — APPROVED** [review]

**Pull request merged**
