### PR TITLE
[15.0][MIG] purchase_order_line_sequence

### PR DESCRIPTION
**Pull request by OriolMForgeFlow**
Standard migration.

Applying refactor from https://github.com/OCA/purchase-workflow/pull/1933 .

@Forgeflow

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
Works the same as in v14. Thanks!

**Review by rafaelbn — APPROVED** [review]
Thank you! 👍🏼

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM!

**Pull request merged**
