### PR TITLE
[15.0][IMP] purchase_order_secondary_unit: Add secondary units to purchase order reports

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

ping @ernestotejeda @CarlosRoca13

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
:+1: Tested

**Comment by sergio-teruel** [comment]
ping @ernestotejeda

**Review by ernestotejeda — APPROVED** [review]
Code and functional review 👍🏼

**Pull request merged**
