### PR TITLE
[15.0][MIG] product_supplier_code_purchase

### PR DESCRIPTION
**Pull request by vvrossem**

### CODE REVIEW

**Comment by vvrossem** [comment]
Hi @AaronHForgeFlow , @LoisRForgeFlow , @nikul-serpentcs , could you please review this PR? 🙏 Thank you !

**Review by AaronHForgeFlow — APPROVED** [review]
Functional review LGTM

**Review by rapvalencia — APPROVED** [review]

**Comment by JuanyDForgeflow** [comment]
@vvrossem please rebase and run precommit

**Review by JuanyDForgeflow — APPROVED** [review]

**Pull request merged**
