### PR TITLE
[12.0][IMP] purchase_request: copy estimated cost to PO

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Review by douglascstd — APPROVED** [review]
[APPROVED] Funcional Tests

Then the user want do use the "estimated cost" it could be done checking the option:
image

image
image

**Comment by marcelsavegnago** [comment]
ping @OCA/procurement-purchase-maintainers

**Review by WesleyOliveira98 — APPROVED** [review]
LGTM

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
