### PR TITLE
[FIX] purchase_quick search view primary

### PR DESCRIPTION
**Pull request by PierrickBrun**
Search view was not primary and the filter added is not useful if not in this context.

Also search_view_id must be forced from the action

### CODE REVIEW

**Comment by PierrickBrun** [comment]
@bealdav I think this will interest you

**Review by bealdav — APPROVED** [review]

**Review by hparfr — APPROVED** [review]
Thanks !

**Comment by bealdav** [comment]
Please define you as maintainer of the module and other authors
https://github.com/OCA/purchase-workflow/blob/12.0/purchase_quick/__manifest__.py

You may add me too if you want

**Comment by bealdav** [comment]
and fix display images https://github.com/OCA/purchase-workflow/tree/12.0/purchase_quick :p

**Comment by PierrickBrun** [comment]
@bealdav done

**Review by rvalyi — APPROVED** [review]

**Comment by rvalyi** [comment]
/ocabot merge
(I'm not using the patch option as the version number is already incremented)

**Pull request merged**
