### PR TITLE
[14.0][IMP] purchase_blanket_order: add blanket order line form

### PR DESCRIPTION
**Pull request by rodrigonevest**
cc @marcelsavegnago @douglascstd @kaynnan

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by kaynnan — APPROVED** [review]

**Comment by marcelsavegnago** [comment]
ping @renatonlima @rvalyi

**Review by rvalyi — APPROVED** [review]
LGTM (useful when someone would like to extend a base line form view, by overriding a mode attribute in the line_ids field to display more informations).

**Comment by marcelsavegnago** [comment]
ping @OCA/procurement-purchase-maintainers

**Comment by rafaelbn** [comment]
Hello @AdriaGForgeFlow @JordiBForgeFlow @HviorForgeFlow do you want to review or merge? this is ready to merge. Thank you!

**Review by HviorForgeFlow — APPROVED** [review]
Functional review :+1:

**Pull request merged**
