### PR TITLE
[18.0][MIG] purchase_commercial_partner: Migration to 18.0

### PR DESCRIPTION
**Pull request by StefanRijnhart**

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Review by gbrito — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
code review

**Review by marcelsavegnago — APPROVED** [review]

**Comment by StefanRijnhart** [comment]
Retrying @HviorForgeFlow's merge command because it failed temporarily on a pre-commit dependency download.

/ocabot merge nobump

**Pull request merged**
