### PR TITLE
[10.0][MIG] product_supplierinfo_discount

### PR DESCRIPTION
**Pull request by apesquero**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please use migration guide for preserving commit history: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

**Comment by apesquero** [comment]
How can I know what the fault is?

**Comment by pedrobaeza** [comment]
Please preserve commit history as requested first.

**Comment by apesquero** [comment]
I have reviewed the commit history as you suggested, and I have made small changes, but it still has not been approved, even though functionally it does not give any problems.

How can I see what exactly fails in the test?

**Comment by pedrobaeza** [comment]
There's still no commit history preservation. Check logs for seeing problems in Travis / Runbot

**Comment by apesquero** [comment]
Travis / Runbot??

The logs that I have seen in the runbot are correct

**Comment by apesquero** [comment]
Error en travis por --> purchase_discount/report/purchase_report.py -- E8103(sql-injection)
                              --> purchase_fop_shipping/README.rst -- E7901(rst-syntax-error)

**Comment by pedrobaeza** [comment]
No, the error is:
```
product_supplierinfo_discount/models/product_supplierinfo.py:22:64: W292 no newline at end of file
```

**Comment by apesquero** [comment]
Por fin, y que facil era si se lee con mas detenimiento.
Finally, and how easy it was if you read more carefully.

**Comment by pedrobaeza** [comment]
Did you sign the CLA?

**Comment by apesquero** [comment]
now, yes!!

**Comment by pedrobaeza** [comment]
I'm afraid not. You have signed Odoo CLA, not OCA CLA. https://odoo-community.org/page/cla

**Comment by apesquero** [comment]
Send it to: cla AT odoo-community.org?
what is the e-mail?

**Comment by pedrobaeza** [comment]
OK then. I saw the Odoo CLA and thought that you have sent it only that one.

**Comment by apesquero** [comment]
Yes, I only send in Odoo CLA, I'm trying to send the OCA CLA document, but I do not know where to send it.

**Comment by pedrobaeza** [comment]
The email is that one... cla@odoo-community.org

**Comment by apesquero** [comment]
I think, now, it's all ok, isn't it?

**Comment by legalsylvain** [comment]
Hi @apesquero. Thanks for this work. Unfortunately, this module has still been ported 6 monthes ago by @StefanRijnhart. See : https://github.com/OCA/purchase-workflow/pull/407

I allow myself to close your PR. Maybe could you review the other PR ?

kind regards.

**Pull request closed without merging**
