### PR TITLE
[12.0][MIG] purchase_request_tier_validation

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration

Depends on:

- [x] https://github.com/OCA/purchase-workflow/pull/720

CC @Eficent

### CODE REVIEW

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review with several tiers. LGTM.

**Review by AdriaGForgeFlow — APPROVED** [review]
Funtional review :+1: 

Please rebase before merging

**Pull request merged**
