### PR TITLE
[15.0][MIG] purchase_order_price_recalculation: Migration to 15.0

### PR DESCRIPTION
**Pull request by CoraVanga**

### CODE REVIEW

**Review by quannguyen1560 — APPROVED** [review]
LGTM!

**Comment by Spider4eyes** [comment]
LGTM

**Comment by DucTruongKomit** [comment]
LGTM!

**Review by DucTruongKomit — APPROVED** [review]
LGTM

**Comment by Leonidas-VII** [comment]
I tested this PR and it works well. LGTM!

**Comment by pedrobaeza** [comment]
I have cancelled it, because the other PR has preference. Please review the other one.

**Pull request closed without merging**
