### PR TITLE
[16.0][MIG] purchase_order_line_price_history: Migration to 16.0

### PR DESCRIPTION
**Pull request by nileshsheliya**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
This one seems already included in core:

https://twitter.com/rvalyi/status/1600319983271219200?s=20&t=lliWqvfpKGF-hADTTWeYeQ

**Comment by nileshsheliya** [comment]
Yes, I see. Thanks for pointing this out.

**Comment by josep-tecnativa** [comment]
Please, include this changes https://github.com/OCA/purchase-workflow/pull/2054/commits/b31caa3b41c75ba9f1a7f105bc4774739b661902 using imported DISABLED_MAIL_CONTEXT variable.

**Comment by HviorForgeFlow** [comment]
Included in core

**Pull request closed without merging**
