### PR TITLE
[8.0] Port purchase partial invoicing to 8.0

### PR DESCRIPTION
**Pull request by adrienpeiffer**

### CODE REVIEW

**Comment by lepistone** [comment]
Hi, there is a minor lint problem.

**Comment by adrienpeiffer** [comment]
Thanks @lepistone ! Travis is green :smile:

**Comment by eLBati** [comment]
Thanks @adrienpeiffer 
See result of
`git diff origin/7.0..acsone/8.0-port-purchase-partial-invoicing-ape purchase_partial_invoicing/`:
https://gist.github.com/eLBati/4382b651da857dd402ce
I think the module version contained in `__unported__` was not up to date, so German translation is missing. Please add it.
(reference about `__unported__` folder problems: https://www.odoo.com/groups/community-59/community-11266932)

**Comment by pedrobaeza** [comment]
Hi, @adrienpeiffer, have you taken into account #29 and its fix for v7: https://github.com/OCA/purchase-workflow/pull/91?

**Comment by adrienpeiffer** [comment]
@eLBati de.po file is added. Thanks !

**Comment by adrienpeiffer** [comment]
Hi @pedrobaeza !
The patch in #91 isn't incuded in this PR.
I think merge it in this branch as soon as it is accepted on 7.0. What do you think ?
Thanks !

**Comment by pedrobaeza** [comment]
OK, so please stay tuned!

**Comment by chrisdec** [comment]
:+1: (functional test)

**Comment by yvaucher** [comment]
@adrienpeiffer  #91 patch is merged you can add it to this PR and let a notice on #29

**Comment by adrienpeiffer** [comment]
@yvaucher corrections are integrated. Thanks !

**Comment by pedrobaeza** [comment]
Thank you very much :+1: 

I proceed with the merge.

**Comment by yvaucher** [comment]
Thanks :+1:

**Comment by adrienpeiffer** [comment]
Thanks :smile:

**Pull request merged**
