### PR TITLE
[17.0][MIG] purchase_order_type_dashboard

### PR DESCRIPTION
**Pull request by Anxo82**
Standard migration

### CODE REVIEW

**Comment by Anxo82** [comment]
@flalexg @HviorForgeFlow 
Could you review?
Thanks

**Review by pmonje-duonex — CHANGES_REQUESTED** [review]
In the kanban view, the vertical three dots button is not aligned with the title of the purchase type unlike in v16.

image

When clicking the button in v17 it doesnt show any option.


When clicking on "Nothing to bill" or "Waiting to bill" an error occurs and it does not filter the purchases.

**Comment by Anxo82** [comment]
@pmonje-duonex 
Could you review?
Thanks

**Review by pmonje-duonex — APPROVED** [review]
LGTM! Functional review on runboat

**Review by HviorForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
