### PR TITLE
[14.0][ADD] purchase_invoice_plan_deposit

### PR DESCRIPTION
**Pull request by kittiu**
Depends on,
- [x] purchase_deposit #1178
- [x] improvement on purchase_invoice_plan #1180 

TODO:
- [x] Test Script

### CODE REVIEW

**Comment by kittiu** [comment]
TOFIX:

I found a problem in following step,

1. Create invoice plan with 1st invoice deposit.
2. Create 1st deposit invoice.
3. Cancel that deposit invoice.
4. The button to create 1st deposit already disable. So I no longer able to create a new deposit.

**Comment by ps-tubtim** [comment]
@kittiu My commit waiting for https://github.com/OCA/purchase-workflow/pull/1492. Could you review it again?

**Comment by kittiu** [comment]
LGTM

**Review by ps-tubtim — APPROVED** [review]

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
