### PR TITLE
[15.0][MIG] purchase_order_secondary_unit: Migration to 15

### PR DESCRIPTION
**Pull request by BT-mgomez**

### CODE REVIEW

**Review by BT-aestebanez — APPROVED** [review]

**Review by BT-ojossen — APPROVED** [review]

**Review by chienandalu — COMMENTED** [review]
The merge command was aborted due to other module. Can you try again?

**Comment by ernestotejeda** [comment]
@BT-mgomez , I think you should rebase, thanks

**Comment by pedrobaeza** [comment]
Superseded by #1708

**Pull request closed without merging**
