### PR TITLE
[9.0][FIX] [purchase_request_to_rfq] Respect 'Requested day' when converting to PO lines

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
* Respect 'Requested day' when converting to PO lines.
* Correct README.

### CODE REVIEW

**Comment by LoisRForgeFlow** [comment]
cc @jbeficent

**Review by JordiBForgeFlow — APPROVED** [review]
Technical and functional review. :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Technical and functional review @lreficent :star:

**Comment by JordiBForgeFlow** [comment]
@gmeficent can you review?

**Review by gmeficent — APPROVED** [review]
Functional review on runbot
and code review, LGTM :+1:

**Comment by JordiBForgeFlow** [comment]
@lreficent Can you check if this is covered in 10.0?

**Pull request merged**
