### PR TITLE
[12.0][FIX] purchase_request: singleton error on cancel po

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Superseed #768 

CC @astirpe @kittiu @CasVissers @yostashiro @aheficent

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  LGTM

**Review by astirpe — APPROVED** [review]

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Funcional test + code review

**Comment by yostashiro** [comment]
LGTM. 👍

**Pull request merged**
