### PR TITLE
[MIG][12.0] purchase_order_line_deep_sort: Migration to v12.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT20127

### CODE REVIEW

**Comment by sergio-teruel** [comment]
@carlosdauden @AlexandreDz Can you review, please??

**Review by carlosdauden — APPROVED** [review]
Reviewed and tested

**Comment by sergio-teruel** [comment]
@Tardo Can you review?

**Review by pedrobaeza — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Let's /ocabot merge as it's correct and reviewed by 2 persons already

**Pull request merged**
