### PR TITLE
[14.0][FIX] purchase_order_type: No need toggle_active button

### PR DESCRIPTION
**Pull request by newtratip**
Selection_289

cc @PrapassornS @kittiu @SurachetS @HviorForgeFlow

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
/ocabot merge patch

FF

**Comment by newtratip** [comment]
@HviorForgeFlow merge failed, Am I doing something wrong ?

**Comment by HviorForgeFlow** [comment]
Branch 14.0 is broken: https://github.com/OCA/purchase-workflow/issues/1148

**Comment by HviorForgeFlow** [comment]
@newtratip rebase to fix CI

**Pull request merged**
