### PR TITLE
[14.0][ADD] purchase_invoice_create_security_group

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Shouldn't this be called `purchase_invoicing_security` and go to `account-invoicing` the same as other invoicing related things?

**Comment by rousseldenis** [comment]
> 

purchase_invoicing_security is too generic, maybe something more accurate like 'purchase_invoice_create_security_group'

IMHO, as the entry point is in purchase and moreover purchase module pulls account, this module should be here.

**Comment by pedrobaeza** [comment]
Usually *-workflow repositories are very crowded, and that's why I prefer to put invoicing flows on that repo, but as you prefer.

**Comment by rousseldenis** [comment]
> Usually *-workflow repositories are very crowded, and that's why I prefer to put invoicing flows on that repo, but as you prefer.

Yes, but that's quite the same for invoicing one.

IMHO, we maybe need to extract common modules that have the same scope in other repos as soon as possible

**Comment by rousseldenis** [comment]
> IMHO, we maybe need to extract common modules that have the same scope in other repos as soon as possible

e.g: purchase_request*, purchase_work*

**Comment by rousseldenis** [comment]
@OCA/procurement-purchase-maintainers

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by rousseldenis** [comment]
@HviorForgeFlow I will try to add a setting in order to activate the feature as it breaks tests in other modules that try to confirm.

**Comment by HviorForgeFlow** [comment]
Sounds great!

**Comment by rousseldenis** [comment]
@HviorForgeFlow Ready and  :green_apple:

**Comment by rousseldenis** [comment]
@HviorForgeFlow

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
