### PR TITLE
[14.0][MIG] purchase_work_acceptance_invoice_plan

### PR DESCRIPTION
**Pull request by SurachetS**
depends on 

- [x] purchase_work_acceptance[1006](https://github.com/OCA/purchase-workflow/pull/1006)

- [x] purchase_invoice_plan [1024](https://github.com/OCA/purchase-workflow/pull/1024)

### CODE REVIEW

**Review by PrapassornS — APPROVED** [review]
Tested LGTM.

**Comment by SurachetS** [comment]
@Saran440 please review

**Review by kittiu — APPROVED** [review]
Functional tested, LGTM

**Pull request merged**
