### PR TITLE
[13.0][MIG] purchase_order_line_price_history_discount: Migration to 13.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
cc @Tecnativa TT24923

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis

**Comment by HviorForgeFlow** [comment]
@ernestotejeda rebase required, some code was merged yesterday had errors...

**Review by HviorForgeFlow — APPROVED** [review]
Functional Review :+1:

**Review by pedrobaeza — APPROVED** [review]
I have pushed the refactoring of the tests for using DRY principle.

**Pull request merged**
