### PR TITLE
8.0 purchase request to rfq fix

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Fixes singleton error due to bad use of api.multi in method _compute_has_purchase_request_lines

image

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
@JonathanNEMRY can you review plz and give your thumbs up?

**Comment by elicoidal** [comment]
:+1:

**Comment by JonathanNEMRY** [comment]
:+1:

**Comment by pabi2** [comment]
:+1:

**Comment by kittiu** [comment]
:+1:

**Comment by JordiBForgeFlow** [comment]
This one is ready to merge.

**Comment by JordiBForgeFlow** [comment]
Thanks to all!

**Pull request merged**
