### PR TITLE
[9.0][ADD]purchase_order_line_sequence

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
supersedes  #273

### CODE REVIEW

**Comment by gurneyalex** [comment]
can you check travis?

**Comment by AaronHForgeFlow** [comment]
Closing this as the work will not be continued in this version

**Comment by AaronHForgeFlow** [comment]
Somebody is telling me to reopen it :smiley:

**Comment by MiquelRForgeFlow** [comment]
:green_apple: 

@aheficent could you review?

**Review by JordiBForgeFlow — APPROVED** [review]

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
Thank you for fixing this! :+1:

**Pull request merged**
