### PR TITLE
purchase_order_revision: provide a value for unrevisioned_name

### PR DESCRIPTION
**Pull request by gurneyalex**
superseeds #149

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Where is the code for providing the value?

**Comment by gurneyalex** [comment]
forgot to `git add`... Now fixed.

**Comment by pedrobaeza** [comment]
I was thinking in a post_init hook for handling existing purchase orders, because this only handle new created purchase orders.

**Comment by eLBati** [comment]
:+1: 
@pedrobaeza I think we don't need a post_init hook because I think there are not existing DB to fix: the current bug prevents the module to be used correctly, because it always writes 'False' in PO name

**Comment by pedrobaeza** [comment]
I insist: we need a post_init_hook to handle existing orders. Imagine this scenario:
- You have already in your DB plenty of draft sales orders.
- You install the module.
- You cancel one of this sales order, and click on the new revision button.
- You will get the `False-01` sales order number, because this sales order doesn't have any value in unrevisioned_name field

**Comment by eLBati** [comment]
Right @pedrobaeza 
See https://github.com/gurneyalex/purchase-workflow/pull/1
This should also fix @jaronemo's [problem](https://github.com/OCA/purchase-workflow/issues/148#issuecomment-117726467)

**Comment by jaronemo** [comment]
Dear Sir..

test ..code ...still is falied...

problem is some..

**Comment by eLBati** [comment]
@gurneyalex oops
`./purchase_order_revision/__init__.py:5:1: E302 expected 2 blank lines, found 1`

**Comment by gurneyalex** [comment]
@eLBati fixed

**Comment by lepistone** [comment]
@gurneyalex, as for the test failure, it is `purchase_requisition_multicurrency` that makes the field required. I don't know why tests passed before OCA/maintainer-quality-tools#212, but that may well be by accident.

**Comment by pedrobaeza** [comment]
OK, we can move on with this PR, and let the other one be fixed by https://github.com/OCA/purchase-workflow/pull/164

:+1:

**Comment by jaronemo** [comment]
Dear Sir

I re-established a test system, and at the same time today re-download purchase_order_revision verified.
It seems to have a normal job.
However, there is a problem spot for the first time why the establishment of a single number will still be False-01? Rather than follow the original single number PO00002-01 it?
My understanding is that with the actual situation should pic2 is the same only more in line with business processes

pic1:
image

pic2:
image

**Comment by pedrobaeza** [comment]
This is due to the lack of a post-init hook that initializes unrevisioned_name field on existing orders. @gurneyalex, can you make it?

**Comment by eLBati** [comment]
@jaronemo could you provide the steps to reproduce the problem on a new database? Thanks

**Comment by pedrobaeza** [comment]
1. Create a purchase order without installing the module.
2. Install the module
3. Cancel the order and click on new revision

**Comment by jaronemo** [comment]
Dear Sir
1. create new database 
2.create supplier
3.create product with this supplier 
4.create purchase order (confirm order status)
5.install module 
6.cancel purchase order 
7.touch revison button create new purchase ...

show false-01 number...this is wrong..

**Comment by eLBati** [comment]
@gurneyalex @pedrobaeza uh it seems changes of my PR https://github.com/gurneyalex/purchase-workflow/pull/1 have been lost somewhere

Created new PR https://github.com/OCA/purchase-workflow/pull/183

**Pull request merged**
