### PR TITLE
[11.0][MIG] purchase last price info

### PR DESCRIPTION
**Pull request by celm1990**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check Travis and runbot status

**Comment by celm1990** [comment]
**Travis error show this**
image
But the error is on other module(_purchase_discount_), any solution or can skip this error???

**Error on runbot show this**
image
id_xml of product view use as module_name _product_, but i understand is because on module **sale_last_price_info** use same [view inherited](https://github.com/OCA/sale-workflow/blob/8.0/sale_last_price_info/views/product_view.xml#L18)

I Can change view for move fields into page Purchase????
image

**Comment by pedrobaeza** [comment]
They are only warnings. The real errors in this module are:
```
purchase_last_price_info/models/product.py:15:1: W293 blank line contains whitespace
purchase_last_price_info/models/product.py:27:69: W292 no newline at end of file
```

**Comment by celm1990** [comment]
because is not merge????

**Comment by pedrobaeza** [comment]
Because this is not how it goes. Check https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md for general rules. You need 2 positive reviews. You can review other PRs and ask in exchange that they review yours.

**Review by CasVissers-360ERP — APPROVED** [review]
LGTM, functional test.

**Comment by CasVissers-360ERP** [comment]
Maybe it would be nice to add the price to product template form view when variants are not used.

**Comment by AdriaGForgeFlow** [comment]
> Maybe it would be nice to add the price to product template form view when variants are not used.

I've made a PR with some improvements [[IMP] purchase_last_price_info](https://github.com/celm1990/purchase-workflow/pull/1)

@celm1990 could you review and give me some feedback?

**Comment by AdriaGForgeFlow** [comment]
ping @celm1990

**Comment by celm1990** [comment]
@ageficent  you PR must be target OCA's repository, not my repo.

Take into account my suggestions. Think is bad idea show on tree view  fields compute without store on BD

**Comment by HviorForgeFlow** [comment]
Closing as this module is already in v11

**Pull request closed without merging**
