### PR TITLE
[IMP] purchase_order_approved: Allows to activate the two-step approv…

### PR DESCRIPTION
**Pull request by rousseldenis**
…al workflow by supplier

Forwardport of #854

### CODE REVIEW

**Comment by rousseldenis** [comment]
@lmignon @HviorForgeFlow @lmarion-source

**Review by lmignon — APPROVED** [review]

**Review by sebalix — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
