### PR TITLE
[13.0][FIX] purchase_order_type: sequence depending on date ranges

### PR DESCRIPTION
**Pull request by dalonsod**
Custom sequence for an order type wasn't taken in account date ranges during order creation, this fix it.

### CODE REVIEW

**Comment by dalonsod** [comment]
@kittiu @newtratip @vvrossem could you review? Thanks!

When merged, I'll port it to later versions.

**Review by ChristianSantamaria — APPROVED** [review]
LGTM 👍

**Review by kittiu — APPROVED** [review]
Thanks for the fix. LGTM

**Comment by dalonsod** [comment]
@HviorForgeFlow is this ready to be merged? Thanks!

**Comment by dalonsod** [comment]
@pedrobaeza this ready to be merged? Thanks!

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
