### PR TITLE
[13.0][IMP] purchase_request: emails conditionals

### PR DESCRIPTION
**Pull request by glitchov**
The goal is to make the message_posts conditionals in case you don't want emails to be sent.

### CODE REVIEW

**Review by ThomasBinsfeld — APPROVED** [review]

**Review by BenjaHe — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
Code changes do not seems to alter any functionality, unless you override the *_content method separately. Couldn't be better to add some kind of company settings that allow you to decide which messages are wanted to be sent?

**Comment by ThomasBinsfeld** [comment]
> Code changes do not seems to alter any functionality, unless you override the *_content method separately. Couldn't be better to add some kind of company settings that allow you to decide which messages are wanted to be sent?

It would be a good new feature. This PR just aims to make the code more easy to override.

**Review by HviorForgeFlow — APPROVED** [review]
> It would be a good new feature. This PR just aims to make the code more easy to override.

Fair enough, let's merge it

**Pull request merged**
