### PR TITLE
[14.0] [IMP] deprecated values 

### PR DESCRIPTION
**Pull request by enterlineconnor**
Trying to clean deprecation warnings for sentry

CC: @ChrisOForgeFlow

### CODE REVIEW

**Review by ChrisOForgeFlow — APPROVED** [review]
LGTM+

**Comment by wlin-kencove** [comment]
Seems good

**Review by dnplkndll — APPROVED** [review]
looks good

**Comment by dnplkndll** [comment]
@JordiBForgeFlow didn't see a maintainer on this module manifest.

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
