### PR TITLE
[MIG] purchase_order_line_menu

### PR DESCRIPTION
**Pull request by dhp-denero**
Can anyone help me how to contribute my development fixes to oca branch ?

### CODE REVIEW

**Comment by dhp-denero** [comment]
Anyone help me fix the issue of pre-commit failure "Error: Process completed with exit code 1."

**Comment by lawso017** [comment]
LOL just did the same thing myself, with the same result.

**Comment by celm1990** [comment]
duplicate of https://github.com/OCA/purchase-workflow/pull/2253

**Comment by StefanRijnhart** [comment]
@dhp-denero Thank you for your effort to contribute to the OCA! I'm closing this because the module is already migrated at this point. Next time, please have a look at https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0 or the version of this article for the target version of your migration.

**Pull request closed without merging**
