### PR TITLE
[14.0][IMP] purchase_default_terms_conditions: fill the notes field in create method too

### PR DESCRIPTION
**Pull request by WesleyOliveira98**
cc: @marcelsavegnago @kaynnan

### CODE REVIEW

**Review by kaynnan — APPROVED** [review]
LGTM

**Review by marcelsavegnago — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]
code review :+1:

**Comment by marcelsavegnago** [comment]
ping @OCA/procurement-purchase-maintainers

**Review by rvalyi — APPROVED** [review]

**Pull request merged**
