### PR TITLE
15.0 mig purchase order line sequence

### PR DESCRIPTION
**Pull request by espo-tony**
Migrated module purchase_order_line_sequence to version 15.

As noted on PR #1564 , most functionality originally implemented in this module are now natively in Odoo. The only thing currently missing is the displaying of Purchase Order Line sequence on views and reports (as well as some utility method to keep a consistent numbering), so I cleaned-up the module from obsolete code and only kept what is needed.

As a consequence of this, and as also suggested on the referenced PR for v14, I renamed the module to better reflect its scope.

### CODE REVIEW

**Review by bosd — APPROVED** [review]
Functional test LGTM :+1:

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review

**Comment by bosd** [comment]
@rousseldenis Can you merge this?

**Comment by rousseldenis** [comment]
> @rousseldenis Can you merge this?

Unfortunately no.

@OCA/procurement-purchase-maintainers

**Comment by rousseldenis** [comment]
But @espo-tony pre-commit is red

**Comment by bosd** [comment]
> But @espo-tony pre-commit is red

I don't think that is for @espo-tony , Seems like pre-commit broke again....
Should the repo be updated?

**Comment by bosd** [comment]
> > But @espo-tony pre-commit is red
> 
@rousseldenis  I don't think that is for @espo-tony , Seems like pre-commit broke again.... Should the repo be updated?

**Comment by rousseldenis** [comment]
> > > But @espo-tony pre-commit is red
> 
> @rousseldenis I don't think that is for @espo-tony , Seems like pre-commit broke again.... Should the repo be updated?

Yes indeed. You can do a PR for that (copier update) and ping maintainers?

**Comment by sbidoul** [comment]
pre-commit is green on branch 15.0. So perhaps a rebase of this PR will be sufficient to fix the pre-commit issue?

**Comment by bosd** [comment]
@espo-tony Can you rebase?

**Comment by HviorForgeFlow** [comment]
@espo-tony could you rebase against 15.0 OCA branch? It seems that some additional commits are involved in this PR
Thanks!

**Comment by HviorForgeFlow** [comment]
ping @espo-tony

**Comment by HviorForgeFlow** [comment]
@mymage @espo-tony rebase not done properly, do you need any hint?
Take your migration branch
Fetch code from OCA branch 15.0:
```
git fetch <OCA_remote> 15.0
git rebase <OCA_remote>/15.0 # Resolve conflicts if needed.
git push <your_remote> -f
```
If conflicts are huge you can always start migration process again and cherry-pick migration commits

**Comment by espo-tony** [comment]
@HviorForgeFlow 
Please, can you see if the rebase is correct now? If not I'll just start it over again.

**Comment by HviorForgeFlow** [comment]
> ce7477f
it is not, only commits belonging to the module should appear

**Comment by HviorForgeFlow** [comment]
> @HviorForgeFlow Please, can you see if the rebase is correct now? If not I'll just start it over again.

Only commits belonging to the module should appear @espo-tony

**Comment by espo-tony** [comment]
@HviorForgeFlow , @bosd 

I started this migration all over again. Please, check PR #1857 . I'm gonna close this.

**Pull request closed without merging**
