### PR TITLE
[11.0][ADD] purchase_order_archive

### PR DESCRIPTION
**Pull request by astirpe**
On a system with a high volume of purchases, the number of purchase orders displayed in the list view can become huge. This module allows to archive Purchase Orders that are in status Locked or Cancelled.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
I think this will affect purchase analysis report, isn't it?

**Comment by astirpe** [comment]
@CasVissers

**Comment by astirpe** [comment]
@pedrobaeza The `purchase_report` view in postgres does not make use of the newly added field `active`. So this module does not affect the purchase analysis report, in the sense that the archived purchases will be taken into account in the report.

The module was mainly meant to hide the old inactive purchase orders from the purchase order list.

**Comment by pedrobaeza** [comment]
OK, indeed. Thanks for the clarification.

**Review by bodedra — APPROVED** [review]
LGTM :+1:

**Review by pankk — APPROVED** [review]

**Review by tarteo — APPROVED** [review]
Simple but nice, looks good. The readme was probably most of the work ;)

**Pull request merged**
