### PR TITLE
[13.0][MIG] purchase_default_terms_conditions

### PR DESCRIPTION
**Pull request by iannak**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @sbidoul 
https://github.com/OCA/purchase-workflow/runs/5774802352?check_suite_focus=true#step:7:156

image

**Comment by sbidoul** [comment]
It should be fixed now. Please rebase.

**Comment by marcelsavegnago** [comment]
> It should be fixed now. Please rebase.

Thanks

**Comment by marcelsavegnago** [comment]
> It should be fixed now. Please rebase.

@sbidoul Unfortunately it still didn't work
https://github.com/OCA/purchase-workflow/runs/5777810726?check_suite_focus=true#step:7:156

**Comment by sbidoul** [comment]
Ah, that's something else: the python version used for pre-commit is not compatible with the pylint version.

**Comment by sbidoul** [comment]
The pre-commit issue should be fixed in https://github.com/OCA/oca-addons-repo-template/pull/136. I'll redeploy on 13.0 branches soon.

**Pull request closed without merging**
