### PR TITLE
[i18n] add _ to translate state issue #243

### PR DESCRIPTION
**Pull request by halgandd**

### CODE REVIEW

**Comment by halgandd** [comment]
Hi,
my login is halgandd, I have signed the Contributor License Agreement
Thanks
David

**Comment by ahilali** [comment]
+1

**Comment by halgandd** [comment]
Hi,
why this pull request is not merged  since 3 months ?
It's just a pull request test with a minor fix ...

**Comment by pedrobaeza** [comment]
Please check the merge rules here:

https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#review

You can't expect also that your work is merged if there's no motivation for that:

* It's a minor issue that doesn't affect too much people.
* You are not a frequent contributor that can attract reviewers.
* You haven't reviewed any other PR and ask in exchange to review yours.

Please understand that all of this is a voluntary work. There's no obligation to review anything. Although your contribution is of course welcome and appreciated, people needs any of the already said motivations for making the rest of the "contribution" (review + merge).

**Comment by halgandd** [comment]
ok good

**Review by gurneyalex — APPROVED** [review]

**Pull request merged**
