### PR TITLE
[17.0][MIG] purchase_last_price_info

### PR DESCRIPTION
**Pull request by mostafabarmshory**

### CODE REVIEW

**Review by Sanazzzmi — APPROVED** [review]

**Comment by mostafabarmshory** [comment]
Dear all,
@gurneyalex
@fasilwdr 

I add a new PR with history. Woould you check and confirme.

**Review by shrkvr2024 — APPROVED** [review]
I reviewed all changes and implement the module and acknowledge that this module is compatible with Odoo 17

**Comment by mostafabarmshory** [comment]
@HaraldPanten 
Hi, This did not work. I could not see the addon on the branch 17. Would you check, please?

**Comment by HaraldPanten** [comment]
> @HaraldPanten Hi, This did not work. I could not see the addon on the branch 17. Would you check, please?

My command was for adding the link of this PR to the V17 migration issue; and it was successfully done.

What do you mean?

**Comment by mostafabarmshory** [comment]
@HaraldPanten 

I`ve added the repo as a submodule to my project (odoo v17). I update to the latest version but it does not contaion the purchase_last_price_info. 

Dose your command merge the PR to the branch 17.0? If not, what should I do right now?

**Comment by HviorForgeFlow** [comment]
Superseed here -> https://github.com/OCA/purchase-workflow/pull/2281

**Pull request closed without merging**
