### PR TITLE
[15.0][MIG] purchase_order_secondary_unit: Migration to version 15.0

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT36981

BT-mgomez doesn't respond, so I opened a new PR with the commits of his PR (https://github.com/OCA/purchase-workflow/pull/1577) in order to speed up this migration

### CODE REVIEW

**Comment by ernestotejeda** [comment]
ping @chienandalu @pedrobaeza

**Comment by chienandalu** [comment]
please review @pilarvargas-tecnativa

**Review by pilarvargas-tecnativa — APPROVED** [review]
Code and functionality revised :)

**Review by chienandalu — COMMENTED** [review]
Do know where the tests errors come from?

**Comment by ernestotejeda** [comment]
@chienandalu  Tests on other modules are failing. I'm trying to fix it. Thanks

**Comment by pedrobaeza** [comment]
Please rebase.

/ocabot migration purchase_order_secondary_unit

**Review by chienandalu — COMMENTED** [review]
@sergio-teruel Does this need to be adapted in any way to the variant secondary units stuff?

**Comment by sergio-teruel** [comment]
@chienandalu Yes... but I am not sure...

**Comment by ernestotejeda** [comment]
> @sergio-teruel Does this need to be adapted in any way to the variant secondary units stuff?

I added a commit for compatibility with product variants
ping @chienandalu @sergio-teruel

**Comment by sergio-teruel** [comment]
@ernestotejeda please rebase

**Comment by ernestotejeda** [comment]
@sergio-teruel test-requirements.txt commit removed 👍🏼

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge nobump

**Pull request merged**
