### PR TITLE
[15.0][MIG] purchase_order_product_recommendation_classification: Migration to version 15.0

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT38332

Pending from:
- [x] https://github.com/OCA/product-attribute/pull/1248

@chienandalu @CarlosRoca13 please review :)

### CODE REVIEW

**Review by CarlosRoca13 — APPROVED** [review]
Code review :+1:

**Review by CarlosRoca13 — CHANGES_REQUESTED** [review]
Ups! CI is failing, please review it

**Comment by pilarvargas-tecnativa** [comment]
> Ups! CI is failing, please review it

I think it's because of the dependency

**Comment by pilarvargas-tecnativa** [comment]
@chienandalu Can you check, please?

**Review by CarlosRoca13 — APPROVED** [review]

**Comment by pilarvargas-tecnativa** [comment]
@chienandalu can you review please?

**Review by chienandalu — APPROVED** [review]
Thanks :)

**Comment by pedrobaeza** [comment]
/ocabot migration purchase_order_product_recommendation_classification
/ocabot merge nobump

**Pull request merged**
