### PR TITLE
[FIX] bug in onchange function if partner is not defined; [IMP] reduce request time;

### PR DESCRIPTION
**Pull request by legalsylvain**
Step to reproduce : 
- install product_supplier_info_discount;
- create a new purchase order;
- do not set partner ; 
- create a new line  ;
- you'll have a non managed error ;

This PR fix the bug;

### CODE REVIEW

**Comment by legalsylvain** [comment]
CC : @pedrobaeza.

**Comment by pedrobaeza** [comment]
:+1: Thanks

**Comment by eLBati** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis error is unrelated, so I fast-track it

**Pull request merged**
