### PR TITLE
[MIG] migration of purchase_order_secondary_unit to v16

### PR DESCRIPTION
**Pull request by MatiasBanega**
[MIG] migration of purchase_order_secondary_unit to v16

### CODE REVIEW

**Review by rvalyi — CHANGES_REQUESTED** [review]
Hello, thank you for trying to contribute. However you should enforce the OCA migration process described here: https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0
It is designed to preserve the commits history.

**Comment by dalonsod** [comment]
@MatiasBanega thanks for the contribution.

This addon has three migration to v16 open PRs (this one, #2216 and #2068, that is superseded by the second one). @MatiasBanega you might close this and help in #2216 PR revision.

**Comment by MatiasBanega** [comment]
Excellent, thanks for your feedback!

**Comment by sergio-teruel** [comment]
I suppose that this PR can be closed. Do you agree?

**Comment by pedrobaeza** [comment]
Being everything red, and no activity, yes, closing.

**Pull request closed without merging**
