### PR TITLE
[12.0][MIG] purchase_packaging

### PR DESCRIPTION
**Pull request by rousseldenis**
Depends on:

* [x] https://github.com/OCA/product-attribute/pull/486
* [x] Remove entry in oca_dependencies.txt

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hi @rousseldenis This branch has conflicts that must be resolved, could you please rebase?

**Comment by rousseldenis** [comment]
@rafaelbn Done!

**Comment by rafaelbn** [comment]
I want to have this tested and merged next week as latest date!

**Comment by rafaelbn** [comment]
Ping @chienandalu

**Comment by rousseldenis** [comment]
@rafaelbn Done. Maybe some tags on this would make reviewers come :smiley:

**Comment by rousseldenis** [comment]
> I want to have this tested and merged next week as latest date!

And a world in peace ! :smile:

**Review by chienandalu — CHANGES_REQUESTED** [review]
I couldn't make it work:

- I created a product (units) and a packaging for it (hundreds)
- Then a purchase order > select the product, but the package isnt't available
- Then I create the package from the order line (same hundreds package)
- Then confirm the order and go to the product's supplierinfo created: the package isnt't ther either...

**Comment by rafaelbn** [comment]
> @rafaelbn Done. Maybe some tags on this would make reviewers come smiley

@rousseldenis I'm **still** not PSC here . But you know I'm interested in packaging in general :smile:

**Comment by rousseldenis** [comment]
@chienandalu Sorry, I'm not as functional as I would have been... I've just fixed views.

Let me know if it's better (I've tested a bit) and if there remains some bugs.

**Comment by rousseldenis** [comment]
On OCA days, I'll try to see why purchase_quick, purchase_triple_discount and purchase_landed_cost are failing (my tests are green and those modules were merged before mine :-) )

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Functional Review
On purchase order line view, it could be improved the way to show quantities.
image
For example,
Packages Quantity: 1 Unit(s)
Packaging Content Quantity: 1 Dozen(s)

Testing packaging configuration I would have been able to create for example a package of 6 meters of a product measured in cm. To do this, I have to create a new UoM.

**Pull request closed without merging**
