### PR TITLE
[14.0][MIG] purchase_open_qty

### PR DESCRIPTION
**Pull request by SurachetS**
ready to review

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by SurachetS** [comment]
@kittiu @Saran440 please review

**Review by Saran440 — APPROVED** [review]
No major change 👍

**Comment by SurachetS** [comment]
@HviorForgeFlow @Saran440 Thank you :)

**Comment by kittiu** [comment]
@HviorForgeFlow is it possible to merge this? many modules seem to depend on this one. :)
Thank you!

**Pull request merged**
