### PR TITLE
7.0 purchase request

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This PR adds a new entity 'Purchase Request'.

The following modules are added:
- purchase_request
- purchase_request_to_requisition
- purchase_request_to_rfq
- purchase_request_webkit
# Purchase Request

You use this module if you wish to give notification of requirements of
materials and/or external services and keep track of such requirements.

Requests can be created either directly or indirectly. "Directly" means that
someone from the requesting department enters a purchase request manually.

The person creating the requisition determines what and how much to order,
and the requested date.

"Indirectly" means that the purchase request initiated by the application
automatically, for example, from procurement orders.

A purchase request is an instruction to Purchasing to procure a certain
quantity of materials services, so that they are is available at a
certain point in time.

A line of a requisition contains the quantity and requested date of the
material to be supplied or the quantity of the service to be performed. You
can indicate the service specifications if needed.
# Purchase Request to Bid

This module introduces the following features:
- The possibility to create new Bids or update existing Bids from Purchase
  Request Lines.
- The possibility to create Purchase Requests on the basis of Procurement
  Orders.
# Purchase Request to RFQ

This module adds the possibility to create or update Requests for
Quotation (RFQ) from Purchase Request Lines.
# Purchase Request Webkit

Report to print purchase requests.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why bid object is not enough to expand your requirements instead of creating a new one?

**Comment by JordiBForgeFlow** [comment]
The Bid is good as it is now. It plays the role that it is expected.

The Bid assumes that you know the scope of products that you want to
include in a process to negotiate a deal with a supplier. The bidding
process results on one or multiple RFQ's that are won, again for the scope
of all products included in the Bid.

A Bid is a natural step to consolidate and manage the procurements that
were first initiated by Purchase Requests created by different users,
independently.

You create RFQ's for the whole Bid, not parts of it. Because that's the
result of the Bidding process. Negotiation occurs as a whole.

My 2 cents.

Why bid object is not enough to expand your requirements instead of
creating a new one?

**Comment by jbaudoux** [comment]
Reading the explanation of your PR, I though this was the purpose of the procurement order?
A procurement order can be manually created to achieve what you call 'directly'. And you can manage date and qty on it.
The procurement order can generate a RfQ or call for bids.

**Comment by pedrobaeza** [comment]
Sorry but still don't see why you need a new object. Bids or procurement orders can serve for this purpose.

**Comment by JordiBForgeFlow** [comment]
If you use bids, it is a problem because:
1. 1 bid converts to 1 PO, so what if multiple users are requesting a
   purchase separately? This would require merging bids to consolidate
   requests made by various groups independently. Merging means loosing
   traceability.

Procurement orders have the following issues to fulfill the requirements:
1. Product is required in procurement orders. Users often have no idea at
all about what product they need. They just express a need in text form.
2. When procurement is run the PO will be created with the default
supplier. What if you want to choose a different supplier for certain
requests other than the default? The system has now created a consolidated
PO that you now have to split... And if you choose to create a Bid from the
product form so as to be able to choose the supplier, you are stuck with
the problem stated above.
3. The user that asks for material may not even make the certain material
election. She expresses a need, that then purchasing can process adjust the
procurement choosing another material, vendor...

Procurement orders are a good tool to support the structured MRP process to
support continuous or discrete manufacturing, but in other areas where thr
procurement is not as structured.

Bids are ok as they are now, because they allow you to negotiate with
vendors for a fixed scope of products that you can choose, that will result
in a Purchase Order that has exactly the same scope.

But purchasing department wants to have the right to decide what should be
submitted to a bidding/tendering process and what should be directly
processed as purchase orders.
El dia 17/09/2015 21:51, "Pedro M. Baeza" notifications@github.com va
escriure:

**Comment by pedrobaeza** [comment]
AFAIK you can have more than one PO for each bid, at least on v8, but I'm not going deeper in this because I don't have almost any customer in v7 right now, so I let you continue discussion and decide the best approach.

**Comment by JordiBForgeFlow** [comment]
Pedro, this has not changed in 7.0 and 8.0. And I'm happy to port any
agreed solution to 8.0. It's just that my customer uses 7.0 and I'm a bit
more confortable with this environment.

But I need to make sure that there's a consensus with the community on how
to approach a current limitation.

You can have multiple PO's for a single bid. But not a single PO that
fulfulls multiple bids, which is what is needed.

Think of this scenario. I want 3 pencils. Tomorrow my Peter from another
area needs 4 black pen. None of these products exist in the database. I
need to ask purchasing that I need them, and so Peter does. We both want to
know the whereabouts of our requests. Have the pencils been ordered? When
will they arrive? I want to know when they have arrived as well.

How would you map such scenario?
El dia 17/09/2015 23:33, "Pedro M. Baeza" notifications@github.com va
escriure:

**Comment by JordiBForgeFlow** [comment]
And, in the example above, the supplier begs for a single PO (1 pencil and
2 pens.. please not in separate PO's..).
El dia 17/09/2015 23:53, "Jordi Ballester Alomar" <
jordi.ballester@eficent.com> va escriure:

**Comment by pedrobaeza** [comment]
But why don't adapt bids for allowing to share POs? And add in them a "wishlist" one2many field for adding only text lines with needs

**Comment by JordiBForgeFlow** [comment]
@pedrobaeza, 

It's not that bids share PO's. It's that some lines of a bid turn to PO 1 and others to PO B, and so on.

The bid is ok as a tendering process, and OCA has nice improvements that make it a strong tool for what a Bid process is expected to do.  IMHO any change to a bid should make it stronger for the purpose of the tendering process, and not to make it a swiss knife. I wouldn't like to create a small monster.

Changing the Bid would severely impact the existing modules built on top of it, meaning:
1) Remove the bid id from purchase.order. Because a PO can now be created from multiple bid lines.
2) Ability to merge some lines from different bids into a new bid, possibly because you want to negotiate with the supplier on the basis of a single bid. Old bids are cancelled.... Or just some items from the old bid, because others may remain in the existing bids. Users need to be able to trace from old bid to the new one. Can you merge a bid from an already merged bids? How will the user that requested in the first place be able to trace what are the whereabouts of the items he requested? 

This would mean that as a result of a bidding process you would be crating Purchase Orders on a per-bid-line basis. But from a business process point of view, when a bid is approved for a scope of products, it should be ordered for that same scope. You negotiated with a supplier for 3 different products, and then you order for one only? Otherwise it is pointless to use something called bid.

The essential thing is that a tendering process is a business process, and a purchase request is another business process. They can work together, but they are not the same thing.

**Comment by pedrobaeza** [comment]
OK, I refrain them because I don't want to block any improvement, but I'm not sure that a new model is needed. Let's see if others have the same concern.

**Comment by JordiBForgeFlow** [comment]
I have showed the flow to Eva Pinter and she's totally in line with me. She
will comment on this PR.

I am more than happy to walk through the improvements to anyone interested.

On Fri, Sep 18, 2015 at 11:49 AM, Pedro M. Baeza notifications@github.com
wrote:

> OK, I refrain them because I don't want to block any improvement, but I'm
> not sure that a new model is needed. Let's see if others have the same
> concern.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/purchase-workflow/pull/186#issuecomment-141406874
> .

## 

Jordi Ballester Alomar
Founder | Eficent
(+34) 629530707 | jordi.ballester@eficent.com | http://www.eficent.com
Twitter: https://twitter.com/jbeficent_erp | Linkedin:
https://www.linkedin.com/in/jordiballesteralomar

**Comment by jbaudoux** [comment]
> You negotiated with a supplier for 3 different products, and then you order for one only? Otherwise it is pointless to use something called bid.

Yes of course, I already faced customer working lite that. You can send RfQ for a list of products and get bids to know prices from different suppliers. Then you are free to create PO for each of product separately. It depends on type of business but you are not always forced to accept the full bid. There is a call for bids improvement module in oca I wrote 2 years ago that support this if I remember properly.
You also have the case where you ask price for similar products but at the end you create a PO only for one of the product you have choosen.

**Comment by JordiBForgeFlow** [comment]
El dia 18/09/2015 13:16, "Jacques-Etienne Baudoux" notifications@github.com
va escriure:

> > You negotiated with a supplier for 3 different products, and then you
> > order for one only? Otherwise it is pointless to use something called bid.
> 
> Yes of course, I already faced customer working lite that. You can send
> RfQ for a list of products and get bids to know prices from different
> suppliers. Then you are free to create PO for each of product separately.
> It depends on type of business but you are not always forced to accept the
> full bid. There is a call for bids improvement module in oca I wrote 2
> years ago that support this if I remember properly.

Sometimes your bid is made to agree on a price. Then the flow would stop on
the bid, because the result is not a PO, but a change in
product.supplierinfo.

The PO is then free to include products from that bid or any other, but
there's no link from PO to Bid.

> You also have the case where you ask price for similar products but at
> the end you create a PO only for one of the product you have choosen.
> That is fine, but again this results in a PO for a single product on the PO.

My point is that a PO needs to includes the requests for products made by
different requestors independently, and they have the right to know of the
follow up of their requests. The bids are not the tool for that.

**Comment by jbaudoux** [comment]
> I am more than happy to walk through the improvements to anyone interested.
> I'm interested.

I wonder if your module solving/helping purchase planning, i.e. collect needs from warehouse (procurement orders) as well as optionally other needs and allow to organize how you will generate PO. This would require working only with PR lines and having a workflow to confirm this can be ordered. However, I don't see yet the benefit from using only procurement orders.

**Comment by JordiBForgeFlow** [comment]
Yes, the module solves this issue.

The needs from the warehouse are materialized in procurement orders. These
are then translated into purchase requests, if you indicated so in the
material master.

So the purchasing departments can elaborate their purchasing plan
exclusively on purchase requests (those coming from warehouse, and those
coming from users of other departments).

The purchasing department then reviews and approves the requests (requests
coming from procurement orders may not need approval at all) and selects
all the purchase request lines that should be converted to:
a) A Request for Quotation, and once confirmed to a PO
b) A Bid, that can then be converted to a RFQ, and finally to a PO

The link between the purchase request line is passed to the Bid line -> RFQ
line, so that there's full traceability. In fact, when the PO is confirmed
the application goes back to the requests that were included in that PO and
posts a message to notify the followers of this event. And the same happen
when the products for that PO are received. Nice, eh? :)

On Fri, Sep 18, 2015 at 1:38 PM, Jacques-Etienne Baudoux <
notifications@github.com> wrote:

> I am more than happy to walk through the improvements to anyone interested.
> I'm interested.
> 
> I wonder if your module solving/helping purchase planning, i.e. collect
> needs from warehouse (procurement orders) as well as optionally other needs
> and allow to organize how you will generate PO. This would require working
> only with PR lines and having a workflow to confirm this can be ordered.
> However, I don't see yet the benefit from using only procurement orders.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/purchase-workflow/pull/186#issuecomment-141424501
> .

## 

Jordi Ballester Alomar
Founder | Eficent
(+34) 629530707 | jordi.ballester@eficent.com | http://www.eficent.com
Twitter: https://twitter.com/jbeficent_erp | Linkedin:
https://www.linkedin.com/in/jordiballesteralomar

**Comment by jbaudoux** [comment]
Reading you, it sounds great. I need to test.

To remove confusion:
- a bid is a reply to a request for quotation. You send a RfQ to a supplier and you get back a bid from the suppier.
- a call for bids is a tendering process where you send RfQ to multiple suppliers.
  Those terms where improved in v8.

**Comment by ybofr** [comment]
Hi, I looked into it this morning and the concept is clear and exactly what is needed:
1. Any User (any person in the company) can create a Purchase Request. He does not need to know anything about it, no product, no supplier, nothing.
2. The Purchase Request needs to be approved by the manager. This has nothing to do with replenishment, it's an internal standard flow. The manager needs to be able to say, I agree
3. All purchase requests related to the same product or of the same type can be managed by the purchaser easily. The purchaser can replace the description by an existing product.
4. The purchaser can join purchase requests lines and automatically put them as one line in the quotation or a call for bid. The system keeps the whole history of the purchase requests allowing the users to follow it through the days.

Please note that the call for bid is wrongly used in Odoo as purchase requisition and also has a one to one relation with the procurement. This is not what purchasers need.

So based on my experience in purchasing departments, I really believe that this new functionality should be also immediately ported to V8 as it is highly needed and is well integrated with the existing procurement but it extend it the way the purchasing departments work.

**Comment by JordiBForgeFlow** [comment]
Thanks for your review @ybofr. Porting to v8 is in progress. Should be completed by next week

**Comment by agb80** [comment]
My two cents here. I have not tested the modules yet but totally support the point of view about the needed a separate object for manage internal procurement orders. 

We have been working with a couple of customers follow Pedro suggestion extending the bid object but doesn't really fit the purchase department process and were considering create a new internal purchase requisition module. This PR seems to do exactly what we were thinking to include on it.

@jbeficent is here the best place for let you any feedback after test the modules?

**Comment by JordiBForgeFlow** [comment]
@agb80 Yes, you can provide feedback here.

**Comment by dcorio** [comment]
@jbeficent "The possibility to create Purchase Requests on the basis of Procurement Orders."

what about the contrary? i create a purchase request that, once confirmed, creates a procurement order. if an employee needs something and that is available in the warehouse we should not create a purchase order.

**Comment by JordiBForgeFlow** [comment]
@dcorio But what would you do with that procurement order? So the procurement order is run and yes, there's stock. Now what?

IMHO perhaps the purchase request should have the ability to trigger a check of the availability of the material. If the material is available, the purchasing user can just answer to the person who asked for the materials "Just take it from the warehouse. It is in location X". The warehouse manager will then need to report the consumption once the material has been removed from inventory.

Or, perhaps the purchase request should trigger an Internal Move, after the person doing the availability check determines that there's stock, but on a different warehouse.

**Comment by dcorio** [comment]
@jbeficent that can be a solution indeed

**Comment by JordiBForgeFlow** [comment]
Find here https://github.com/OCA/purchase-workflow/pull/189 the PR for version 8.0

**Comment by kittiu** [comment]
@jbeficent 

+1,  finally we have a serious Purchase Request :)

In v7, there is a (joke) Purchase Requisition menu, no matter how we look at it, it is not a Purchase Requisition in the real business sense. Thank God, v8 change name to Call for Bid but still do the exact same thing. Which means there is no Purchase Requisition any more in v8.

The real Purchase Requisition should give "The Power of Negotiation"  into purchaser hand. The flow should be flexible as everyone has explained (splitting lines, grouping lines form many PRs, tracibility, etc). For smaller organization, may not required, but for large organization, it is seriously needed.

**Why can't we extend the existing Call for Bid (purchase_requisition) to cover more cases?**

We did! (https://github.com/kittiu/addons-eco/tree/7.0/purchase_requisition_multi_supplier) but it make the code very complex and still can't cover all cases. Such as we can't select lines form multiple requests.

When I test this Pull Request, it does cover more use cases and at the same time the code is much simpler, which is the result of having a new model.

**So I see the separate model a necessity as well**

**Comment by agb80** [comment]
I've seen there are several fixes on 8.0 branch that have not being backported here, is there any specific reason for that? Or is just that this branch is to old that you are not using anymore?

**Comment by JordiBForgeFlow** [comment]
We don't want to maintain it further in v7. Closing this PR.

**Pull request closed without merging**
