### PR TITLE
[MIG] purchase_request_department: Migration to 16.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Hector! We continue the review on this PR, which has the commits history.

**Review by HviorForgeFlow — APPROVED** [review]
Code looks good

Can you squash last 2 commits adding the module name in the commit itself. Thanks!

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Done! Commits squashed!

**Comment by HviorForgeFlow** [comment]
@mav-adhoc Could you improve the migration commit message? We need to wait for some other approval I guess

**Review by ced-adhoc — APPROVED** [review]

**Comment by ced-adhoc** [comment]
LGTM

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Done!

**Pull request merged**
