### PR TITLE
[12.0][MIG] purchase_work_acceptance_evaluation: Migrate to 12.0

### PR DESCRIPTION
**Pull request by marcelsavegnago**

### CODE REVIEW

**Comment by marcelsavegnago** [comment]
ping @augustodinizl

**Review by kaynnan — APPROVED** [review]
[FUNCTIONAL REVIEW] - Approved

**Review by augustodinizl — APPROVED** [review]
LGTM

**Comment by marcelsavegnago** [comment]
ping @kittiu

**Pull request merged**
