### PR TITLE
[15.0] [MIG] purchase_delivery_split_date

### PR DESCRIPTION
**Pull request by rauferdeveloper**
Standard migration to version 15.

### CODE REVIEW

**Review by CasVissers-360ERP — APPROVED** [review]
Functional review.

**Comment by jbaudoux** [comment]
Note this refactor done in v13 and ported to v14 https://github.com/OCA/purchase-workflow/pull/1326

**Review by JasminSForgeFlow — APPROVED** [review]
Review Functionally

**Pull request merged**
