### PR TITLE
[14.0][FIX] purchase_work_acceptance: stock picking domain wa_id

### PR DESCRIPTION
**Pull request by PrapassornS**
- Cannot search field wa_id in stock picking page because wa_id domain by active_id of purchase_order
- Fix by change domain filter by field purchase_id in table stock picking

### CODE REVIEW

**Comment by kittiu** [comment]
This case shouldn't be fixed in the view. Initial reasons that it was using `active_id` it is because `purchase_id` may not available until stock.picking is saved. Here is the field purchase_id form stock module.
```
class StockPicking(models.Model):
    _inherit = 'stock.picking'

    purchase_id = fields.Many2one('purchase.order', related='move_lines.purchase_line_id.order_id',
        string="Purchase Orders", readonly=True)
```

Please fix in .py file, and test all cases.

```
    wa_id = fields.Many2one(
        comodel_name="work.acceptance",
        string="WA Reference",
        copy=False,
        domain="[('state', '=', 'accept'), ('purchase_id', '=', purchase_id)]"
    )
```

**Comment by PrapassornS** [comment]
Noted ka.

**Comment by kittiu** [comment]
@PrapassornS is this ready for review?

**Comment by PrapassornS** [comment]
> This case shouldn't be fixed in the view. Initial reasons that it was using `active_id` it is because `purchase_id` may not available until stock.picking is saved. Here is the field purchase_id form stock module.
> 
> ```
> class StockPicking(models.Model):
>     _inherit = 'stock.picking'
> 
>     purchase_id = fields.Many2one('purchase.order', related='move_lines.purchase_line_id.order_id',
>         string="Purchase Orders", readonly=True)
> ```
> 
> Please fix in .py file, and test all cases.
> 
> ```
>     wa_id = fields.Many2one(
>         comodel_name="work.acceptance",
>         string="WA Reference",
>         copy=False,
>         domain="[('state', '=', 'accept'), ('purchase_id', '=', purchase_id)]"
>     )
> ```

I  tried but field purchase_id is a compute field that cannot domain if not store field.

**Comment by kittiu** [comment]
> I tried but field purchase_id is a compute field that cannot domain if not store field.

You can make it store=True.

**Review by kittiu — APPROVED** [review]

**Review by ps-tubtim — APPROVED** [review]

**Pull request merged**
