### PR TITLE
[15.0][MIG] purchase_order_product_recommendation: Migration to 15.0

### PR DESCRIPTION
**Pull request by cesar-tecnativa**
@Tecnativa TT36506

### CODE REVIEW

**Comment by cesar-tecnativa** [comment]
Depends on https://github.com/OCA/purchase-workflow/pull/1517

**Comment by cesar-tecnativa** [comment]
@ernestotejeda @pedrobaeza  could you please review?

**Review by pedrobaeza — APPROVED** [review]
Code review

**Comment by cesar-tecnativa** [comment]
@CarlosRoca13 please review

**Review by CarlosRoca13 — APPROVED** [review]

**Pull request merged**
