### PR TITLE
[MIG] purchase_exception: Migrate to version 17.0

### PR DESCRIPTION
**Pull request by sonhd91**
Ref: BSRD-737
Depended on:
* https://github.com/OCA/server-tools/pull/2761

### CODE REVIEW

**Review by gurneyalex — APPROVED** [review]

**Comment by gurneyalex** [comment]
@sonhd91 https://github.com/OCA/server-tools/pull/2809 was merged for base_exception, can you remove the other PR from test-requirements.txt?

**Comment by sonhd91** [comment]
> @sonhd91 [OCA/server-tools#2809](https://github.com/OCA/server-tools/pull/2809) was merged for base_exception, can you remove the other PR from test-requirements.txt?

Thanks. updated

**Review by rousseldenis — APPROVED** [review]
Code review

**Pull request merged**
