### PR TITLE
[14.0][MIG] procurement_batch_generator

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by kittiu** [comment]
Seem pre-commit still pending.

**Comment by alexis-via** [comment]
Should be OK in my last commit.

**Review by fshah-initos — COMMENTED** [review]
Code review Looks good to me.
Functional test:
Shows me this Error though the field UOM has value.
Products-Odoo

**Comment by fshah-initos** [comment]
@alexis-via Is it possible to check the issue.

**Comment by alexis-via** [comment]
Fixed

**Comment by fshah-initos** [comment]
Can you please fix the travis?

**Comment by alexis-via** [comment]
Travis error is unrelated.

**Comment by fshah-initos** [comment]
HI @alexis-via Can you please ask somone for review so that PR can be merged soon?

**Comment by fshah-initos** [comment]
Can somone please review so that we can merge this PR ASAP.

**Comment by fshah-initos** [comment]
It would be great if can get review here and merge the PR soon

**Comment by fshah-initos** [comment]
It would be great if can get review here and merge the PR soon

**Comment by fshah-initos** [comment]
It would be nice we could merge the PR .

**Comment by fshah-initos** [comment]
It would be great if we could merge it

**Comment by fshah-initos** [comment]
@OCA/procurement-purchase-maintainers It would be great if we could merge it

**Review by fshah-initos — APPROVED** [review]

**Comment by fshah-initos** [comment]
It would be great if can get review here so that we can merge the PR soon

**Comment by fshah-initos** [comment]
It would be nice if we get the reviews here.

**Comment by fshah-initos** [comment]
It would be great if we get the reviews here.

**Comment by dreispt** [comment]
Travis is red

**Comment by hkapatel-initos** [comment]
Can you please fix the Travis?

**Comment by hkapatel-initos** [comment]
Can someone please review it so that we can merge this PR ASAP.

**Pull request merged**
