### PR TITLE
[MIG/REM] purchase_order_line_packaging_qty: Makes it uninstallable

### PR DESCRIPTION
**Pull request by rousseldenis**
Keep it in this version uninstallable for records.

### CODE REVIEW

**Comment by rousseldenis** [comment]
@MiquelRForgeFlow @LoisRForgeFlow @ChrisOForgeFlow 

I've added tests to check if all functionalities of this module have been implemented in Odoo. But made it uninstallable.

People needs to 'just' update product_packaging > product_packaging_id field.


The only thing that misses is the creation of purchase order line from procurement.

But IMHO that one should not be part of this module and should be done in another one. I'll do it.

**Comment by lmignon** [comment]
@rousseldenis Thank you for the migration and the proposed approach. IMO we should not merge this one since it's deprecated and useless. The move of remaining logic into an other addon is a good idea.

**Review by LoisRForgeFlow — APPROVED** [review]
Makes sense :+1:

**Review by sbejaoui — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@rousseldenis what to do here?

**Comment by rafaelbn** [comment]
@yajo ping

/ocabot merge patch

**Comment by yajo** [comment]
It seems one test is failing:

```
2023-12-02 17:21:29,452 385 INFO odoo odoo.addons.purchase_order_line_packaging_qty.tests.test_purchase_order_line_packaging_qty: ====================================================================== 
2023-12-02 17:21:29,452 385 ERROR odoo odoo.addons.purchase_order_line_packaging_qty.tests.test_purchase_order_line_packaging_qty: FAIL: TestPurchaseOrderLinePackagingQty.test_product_packaging_qty_inverse
Traceback (most recent call last):
  File "/__w/purchase-workflow/purchase-workflow/purchase_order_line_packaging_qty/tests/test_purchase_order_line_packaging_qty.py", line 87, in test_product_packaging_qty_inverse
    with Form(order) as order_form:
  File "/opt/odoo/odoo/tests/common.py", line 2259, in __exit__
    self.save()
  File "/opt/odoo/odoo/tests/common.py", line 2272, in save
    values = self._values_to_save()
  File "/opt/odoo/odoo/tests/common.py", line 2299, in _values_to_save
    return self._values_to_save_(
  File "/opt/odoo/odoo/tests/common.py", line 2337, in _values_to_save_
    raise AssertionError("{} is a required field ({})".format(f, view['modifiers'][f]))
AssertionError: order_type is a required field ({'readonly': [('state', 'in', ['purchase', 'done', 'cancel'])], 'required': [(1, '=', 1)]})
```

Could you please rebase and see if it fails now, then fix it?

**Review by hspl-niharika — APPROVED** [review]

**Comment by hspl-niharika** [comment]
@rousseldenis Thanx for migration
@pedrobaeza It's good. I thin you can merge this

**Comment by yajo** [comment]
I didn't read https://github.com/OCA/purchase-workflow/pull/1672#issuecomment-1339200483 carefully. It seems to me like this should be handled in a migration script in https://github.com/OCA/openupgrade

**Pull request closed without merging**
