### PR TITLE
[14.0][MIG] purchase_order_type

### PR DESCRIPTION
**Pull request by SurachetS**
standard migration.

depends on  
- [x] waiting merge into oca13.0 https://github.com/OCA/purchase-workflow/pull/898

### CODE REVIEW

**Comment by kittiu** [comment]
Please help in fixing error in https://github.com/OCA/purchase-workflow/pull/898 too, so we can MIG out of 13.0.
Note: you can use this temporarily though.

**Comment by PrapassornS** [comment]
Functional tested, LGTM.

**Review by PrapassornS — APPROVED** [review]
Functional tested, LGTM.

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
