### PR TITLE
purchase_request: fix _compute_qty_to_buy

### PR DESCRIPTION
**Pull request by ajaniszewska-dev**

### CODE REVIEW

**Review by mmequignon — APPROVED** [review]
makes sense

**Review by simahawk — CHANGES_REQUESTED** [review]
pls amend the commit like `purchase_request: fix _compute_qty_to_buy` and move the explanation to the commit description.
Also, remember to never include the Odoo version in the commit.

**Comment by simahawk** [comment]
functionality-wise LG, thanks! :)

**Comment by ajaniszewska-dev** [comment]
> pls amend the commit like `purchase_request: fix _compute_qty_to_buy` and move the explanation to the commit description. Also, remember to never include the Odoo version in the commit.

@simahawk  done!

**Review by simahawk — APPROVED** [review]

**Review by flotho — APPROVED** [review]
code review, LGTM

**Pull request merged**
