### PR TITLE
[MIG]17.0 mig purchase all shipments

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Hi Hector! Can you review this PR please? Thanks!

**Review by bruno-zanotti — APPROVED** [review]
Technical review +1

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Hi Hector! Can you review this PR please? Thanks!

**Review by HviorForgeFlow — APPROVED** [review]
Code review

**Pull request merged**
