### PR TITLE
[17.0][MIG] purchase_order_secondary_unit: Migration to 17.0

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration.

Supersedes #2319 due to inactivity, and keeping migration commit authorship.

I'll clean commit history if tests work fine.

### CODE REVIEW

**Comment by dalonsod** [comment]
@sergio-teruel @HviorForgeFlow could you review? Thanks!

**Review by HviorForgeFlow — APPROVED** [review]
code review :+1:

**Review by sergio-teruel — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Thanks @dalonsod

**Pull request merged**
