### PR TITLE
[14.0][IMP] purchase_request: copy estimated cost to PO

### PR DESCRIPTION
**Pull request by kaynnan**
cc @marcelsavegnago @douglascstd 

Related [[12.0][IMP] purchase_request: copy estimated cost to PO](https://github.com/OCA/purchase-workflow/pull/1597/)

### CODE REVIEW

**Review by marcelsavegnago — APPROVED** [review]

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@kaynnan @marcelsavegnago are you planning to forward port it to more recent versions?

**Comment by kaynnan** [comment]
@HviorForgeFlow  Yes, we are planning to forward port it to more recent versions. 

I noticed that the merge flagged some issues. Do you know if they would be related to PR? To be safe, I ran the rebase origin/14.0 command to keep the PR updated as well.

**Comment by HviorForgeFlow** [comment]
@kaynnan FYI merge issue solved here: https://github.com/OCA/purchase-workflow/pull/2211

**Pull request merged**
