### PR TITLE
[15.0][MIG] purchase_order_line_menu

### PR DESCRIPTION
**Pull request by vvrossem**
- Followed [Migration to version 15.0](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0) guidelines
- Added/Enabled Form view:
  - List and Pivot view unaltered:Screenshot 2022-03-21 at 11 16 28
  - When clicking on a Purchase Order Line, opens its related Form view:Screenshot 2022-03-21 at 11 16 42

### CODE REVIEW

**Comment by vvrossem** [comment]
Hi @Freni-OSI, @dreispt, @dalonsod, @ChristianSantamaria, could you please review this PR? 🙏 Thank you !

**Comment by dalonsod** [comment]
Tested on runboat, LGTM

Maybe you could reword added commits and remove `[15.0]` label for both added commits, following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 guidelines

**Comment by vvrossem** [comment]
> Tested on runboat, LGTM
> 
> Maybe you could reword added commits and remove `[15.0]` label for both added commits, following https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0 guidelines

Thank you for reviewing. both added commits are reworded

**Review by dalonsod — APPROVED** [review]

**Review by dreispt — APPROVED** [review]

**Pull request merged**
