### PR TITLE
[14.0][MIG] purchase_last_price_info: Migration to 14.0

### PR DESCRIPTION
**Pull request by Vanneri**
Ready to Overview

### CODE REVIEW

**Review by tonygalmiche — APPROVED** [review]
LGTM : Functional review only with runbot

image

**Comment by kittiu** [comment]
> Work in Progress , no review

@Vanneri still work in progress or ready for review?

**Comment by Vanneri** [comment]
> > Work in Progress , no review
> 
> @Vanneri still work in progress or ready for review?

ready for overview

**Review by kittiu — APPROVED** [review]
LGTM, no major changed.

**Pull request merged**
