### PR TITLE
Adds purchase_analytic_global,

### PR DESCRIPTION
**Pull request by guewen**
An analytic account field on the purchase order that applies the account on
all the lines of the purchase order.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
:+1:

**Comment by gurneyalex** [comment]
could you rebase?

**Comment by jgrandguillaume** [comment]
Hi,

:+1:  for me when Travis is greenified.

Regards,

**Comment by bwrsandman** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Travis error is unrelated. I merge.

**Pull request merged**
