### PR TITLE
[15.0][IMP] purchase_order_line_menu: added invoice line in tree view

### PR DESCRIPTION
**Pull request by EmilioPascual**
Added invoice lines in tree view

image

@moduon MT-2028 @rafaelbn

### CODE REVIEW

**Comment by EmilioPascual** [comment]
@Shide can you review, plz?

**Review by Shide — APPROVED** [review]

**Review by rafaelbn — APPROVED** [review]
OK! 👍🏼 

@Shide you are maintainer could you merge?

**Comment by rafaelbn** [comment]
We neeed the help of @dreispt to merge this one as maintainer! 😄 🙏🏼

**Review by rafaelbn — APPROVED** [review]
👍🏼 

/ocabot merge minor

**Comment by rafaelbn** [comment]
Please @HviorForgeFlow @dreispt could you please take a look to merge? We would like to merge and migrate to v16 😄 

Thank you!

**Pull request merged**
