### PR TITLE
[15.0][MIG] purchase_triple_discount

### PR DESCRIPTION
**Pull request by ramiadavid**
depends https://github.com/OCA/account-invoicing/pull/1144

### CODE REVIEW

**Comment by ramiadavid** [comment]
Can someone review this PR?

**Comment by ao-landoo** [comment]
@ramiadavid Can you add this commit please?
https://github.com/OCA/purchase-workflow/pull/1587

**Review by bi-landoo — APPROVED** [review]

**Comment by ramiadavid** [comment]
@ao-landoo Done, but the report in v15 has changed, I had to modify it

**Review by ao-landoo — APPROVED** [review]
Technical approval

**Review by ma-landoo — APPROVED** [review]

**Review by manuelregidor — APPROVED** [review]
LGTM

**Comment by HaraldPanten** [comment]
Hi @rousseldenis @gurneyalex @JordiBForgeFlow could you merge this one?

**Review by HaraldPanten — APPROVED** [review]

**Comment by bi-landoo** [comment]
Hi @rousseldenis @gurneyalex @JordiBForgeFlow @pedrobaeza could you please merge it?

Thanks!

**Comment by pedrobaeza** [comment]
Hello from OCA days!

/ocabot migration purchase_triple_discount
/ocabot merge nobump

**Comment by HaraldPanten** [comment]
> Hello from OCA days!
> 
> /ocabot migration purchase_triple_discount /ocabot merge nobump

Thank you Pedro! 🎉

**Pull request merged**
