### PR TITLE
[9.0][FIX] purchase_request_procurement: interfering mrp_production_request

### PR DESCRIPTION
**Pull request by LoisRForgeFlow**
Fixes issue https://github.com/OCA/purchase-workflow/issues/440.

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
LGMT, just one question. Why do you need sudo()?

**Comment by LoisRForgeFlow** [comment]
@aheficent have a look to issue in the description. With sudo() you let the system search and perform actions in a model even if such model is not accessible for the user that triggered the action.

**Comment by AaronHForgeFlow** [comment]
I see @lreficent. Thanks

**Review by MiquelRForgeFlow — APPROVED** [review]

**Comment by JordiBForgeFlow** [comment]
@lreficent Can you make sure that this is also fixed in 10.0?

**Pull request merged**
