### PR TITLE
[14.0][MIG] purchase_work_acceptance

### PR DESCRIPTION
**Pull request by ps-tubtim**
Standard Migration.

### CODE REVIEW

**Comment by kittiu** [comment]
Functional Tested LGTM

**Review by kittiu — APPROVED** [review]

**Comment by kittiu** [comment]
@SurachetS can you help test/review this?

**Review by SurachetS — APPROVED** [review]
Functional Tested OK

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
