### PR TITLE
[FIX][13.0] purchase_isolated_rfq cancel RFQ raise error 

### PR DESCRIPTION
**Pull request by Nikul-Chaudhary**
issue #971

### CODE REVIEW

**Review by Saran440 — CHANGES_REQUESTED** [review]
Functional Test
should it change button name to `button_cancel` ?

**Comment by HviorForgeFlow** [comment]
> Functional Test
> should it change button name to `button_cancel` ?

I think yes! But it should be tested

**Comment by HviorForgeFlow** [comment]
> Functional Test
> should it change button name to `button_cancel` ?

ping @Nikul-Chaudhary

**Comment by kittiu** [comment]
Let's go on, it is a small fix :)
https://github.com/OCA/purchase-workflow/pull/992

**Pull request closed without merging**
