### PR TITLE
[9.0] migrate module "purchase_delivery_split_date"

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
Includes improvements proposed to v8 here: https://github.com/OCA/purchase-workflow/pull/236

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @darshan-serpent @jceficent @aheficent

**Comment by JordiBForgeFlow** [comment]
@clonedagain What do you think about this one?

**Comment by serpentcs-dev1** [comment]
Have tested and reviewed the code. LGTM :+1:

**Review by AaronHForgeFlow — APPROVED** [review]
Functional test :+1:

**Review by LoisRForgeFlow — COMMENTED** [review]
In this case I see the expected behavior. 
image

While as commented @aheficent in https://github.com/OCA/purchase-workflow/pull/236 in the v8 the PO with different dates is not splitted.

I'm wondering if I'm missing something.

**Pull request merged**
