### PR TITLE
[14.0][ADD] purchase_cancel_confirm

### PR DESCRIPTION
**Pull request by kittiu**
Depends on,
- [x] base_cancel_confirm https://github.com/OCA/server-ux/pull/297

This module extend `base_cancel_confirm` to make cancel confirmation with cancel reason (none / optional / requried).

Selection_044

### CODE REVIEW

**Comment by newtratip** [comment]
@kittiu, Please change year copyright of all files to 2021 and check your travis.

**Comment by kittiu** [comment]
Looks like the Travis error is because, this module `purchase_cancel_confirm` is installed, and so it affect `purchase_cancel_reason`

Anyone know if it is possible to ensure `purchase_cancel_confirm` is installed last in this repo when Travis run test?

**Comment by kittiu** [comment]
Test added, ready for review.

**Review by ps-tubtim — APPROVED** [review]

**Comment by kittiu** [comment]
I think this module may conflict with `purchase_cancel_reason`

Anyone know, are there ways, in the travis, not to run these 2 modules together?

**Comment by kittiu** [comment]
@kittiu here is the method to fix conflicting module https://github.com/OCA/purchase-workflow/pull/1213

**Comment by kittiu** [comment]
@kevinkhao can I lend you some help. As suggested by @sbidoul I first try to do, `copier update`
But after few questions, I got following error, 
```
rebel_module_groups? Format: yaml
🎤 [[]]: ["purchase_cancel_reason", "purchase_cancel_confirm"]

Do you need to install wkhtmltopdf? Usually only needed if you're going to test PDF report generation.
include_wkhtmltopdf? Format: bool
🎤? [y/N] N
Make sure Git >= 2.24 is installed to improve updates.
Traceback (most recent call last):
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/copier/main.py", line 271, in update_diff
    diff = diff_cmd("--inter-hunk-context=-1")
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/commands/base.py", line 96, in __call__
    return self.run(args, **kwargs)[1]
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/commands/base.py", line 232, in run
    return p.run()
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/commands/base.py", line 193, in runner
    return run_proc(p, retcode, timeout)
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/commands/processes.py", line 302, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/commands/processes.py", line 22, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/home/kitti/.local/pipx/venvs/copier/lib/python3.8/site-packages/plumbum/machines/base.py", line 24, in verify
    raise ProcessExecutionError(
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 128
Command line: | /usr/bin/git diff-tree --unified=1 HEAD...FETCH_HEAD --inter-hunk-context=-1
Stderr:       | fatal: ambiguous argument 'HEAD...FETCH_HEAD': unknown revision or path not in the working tree.
              | Use '--' to separate paths from revisions, like this:
              | 'git <command> [<revision>...] -- [<file>...]'
```

So, I now editing .travis.yaml manually.
https://github.com/OCA/purchase-workflow/pull/1125/commits/b5409999618833a2b259cd48e08fa864616536bc#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R23-R28

**Comment by kevinkhao** [comment]
@kittiu I did not have this problem, even though it seems we did the same operations. maybe recheck all your answers to copier prompts, check git version ? or I'm not sure but it seems git doesn't know what HEAD...FETCH_HEAD means so it could be a problem with git config

**Comment by kevinkhao** [comment]
@kittiu I succeeded on copier update, so I think it's a problem on your local configuration https://github.com/OCA/purchase-workflow/commit/732d8e32d0065194eb6e8c56616ed4a4e1fb1cec

**Comment by kittiu** [comment]
> @kittiu I succeeded on copier update, so I think it's a problem on your local configuration [732d8e3](https://github.com/OCA/purchase-workflow/commit/732d8e32d0065194eb6e8c56616ed4a4e1fb1cec)

@kevinkhao Thanks for helping. I will try.

**Comment by kittiu** [comment]
@kevinkhao got it sorted out, thanks again. :)

**Review by Saran440 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
