### PR TITLE
[12.0][ADD] purchase_invoice_plan_deposit

### PR DESCRIPTION
**Pull request by kittiu**
- [x] https://github.com/OCA/purchase-workflow/pull/764

Bridge module for purchase_invoice_plan and purchase_deposit
@hveficent

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
#764 merged, rebase required

**Comment by kittiu** [comment]
Rebased, thank you!

**Comment by kittiu** [comment]
@hveficent this should be goo to go.

**Review by HviorForgeFlow — APPROVED** [review]
Functional review. Works as expected :+1:

**Comment by kittiu** [comment]
@HviorForgeFlow can this get merged?

**Pull request merged**
