### PR TITLE
[IMP] purchase_order_general_discount: Make the tests compatible with other modules

### PR DESCRIPTION
**Pull request by ernestotejeda**
Cc @Tecnativa TT36981

Needed for https://github.com/OCA/purchase-workflow/pull/1708

### CODE REVIEW

**Comment by ernestotejeda** [comment]
@chienandalu could you review please?

**Review by chienandalu — APPROVED** [review]
Thanks!

please @pilarvargas-tecnativa add your review as well

**Review by pilarvargas-tecnativa — APPROVED** [review]
That's right, thank you!

**Pull request merged**
