### PR TITLE
13.0[MIG] purchase_location_by_line

### PR DESCRIPTION
**Pull request by HaraldPanten**
Migration to V13. Ready for reviews

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional review. Works as expected.

**Comment by HaraldPanten** [comment]
Minor changes added. Could you review @ValentinVinagre ?

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by pedrobaeza** [comment]
There has been a problem with merge bot, but it's fixed now, so you can relaunch.

**Pull request merged**
