### PR TITLE
[16.0][MIG]purchase_location_by_line

### PR DESCRIPTION
**Pull request by manuelregidor**
Supersedes https://github.com/OCA/purchase-workflow/pull/1686

### CODE REVIEW

**Comment by manuelregidor** [comment]
@HaraldPanten @ValentinVinagre @luis-ron

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM

**Comment by HaraldPanten** [comment]
@HviorForgeFlow @JordiBForgeFlow

**Review by ValentinVinagre — APPROVED** [review]
LGTM 👍🏻

**Review by HviorForgeFlow — APPROVED** [review]
Code + Functional review :+1:

**Pull request merged**
