### PR TITLE
[13.0][MIG] purchase_order_line_menu

### PR DESCRIPTION
**Pull request by ChristianSantamaria**
Standar backport from #1100

### CODE REVIEW

**Comment by ChristianSantamaria** [comment]
@Freni-OSI @dreispt could you review? Thanks!

**Review by dalonsod — CHANGES_REQUESTED** [review]
@ChristianSantamaria monetary widget is not working for price subtotal. Maybe `<field name="currency_id" invisible="1"/>` should be added to purchase line tree view

**Comment by ChristianSantamaria** [comment]
> 
> 
> @ChristianSantamaria monetary widget is not working for price subtotal. Maybe `<field name="currency_id" invisible="1"/>` should be added to purchase line tree view

👍 Done, thanks @dalonsod

**Review by dreispt — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
Functional review. :+1:

**Review by dalonsod — APPROVED** [review]
LGMT. @ChristianSantamaria please squash last commit

**Review by vvrossem — APPROVED** [review]

**Comment by vvrossem** [comment]
reviewed and functionally tested 👍 
@pedrobaeza could this PR be merged ? 🙏

**Comment by pedrobaeza** [comment]
Merging based on existing reviews:

/ocabot merge nobump

**Pull request merged**
