### PR TITLE
[15.0][MIG]purchase_manual_currency: Migration to 15.0

### PR DESCRIPTION
**Pull request by bizzappdev**

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Review by PatthamaCH — APPROVED** [review]
Thanks for creating the module. This module is very useful.

**Review by Saran440 — CHANGES_REQUESTED** [review]
@bizzappdev Can you cherry-pick 5515eda218b02794782f2a4306c6ae156aa2ab16 please,

or we move on to PR https://github.com/OCA/purchase-workflow/pull/1765/commits

**Comment by bizzappdev** [comment]
@Saran440 I can do it, only the thing is some code refactoring will be needed accordingly to the standards in your code.
should I take care of it in my PR or suggest those changes in your PR and then I do cherry-pick.

**Comment by Saran440** [comment]
you can use this PR and cherry-pick to here.
after that i will close my PR :)

**Comment by bizzappdev** [comment]
ready for review

**Comment by Saran440** [comment]
@bizzappdev Sorry, I add new feature in this PR https://github.com/OCA/purchase-workflow/pull/1765
can you cheery-pick https://github.com/OCA/purchase-workflow/pull/1765/commits/26459fca8125f2c98db970381c5d70d52ea8cbbd with new commit please?

**Pull request closed without merging**
