### PR TITLE
[12.0][ADD] product_form_purchase_link

### PR DESCRIPTION
**Pull request by rousseldenis**
As Odoo removed links in product forms and replaced it by a purchase.report model, this reintroduces the link to purchases.

### CODE REVIEW

**Review by bealdav — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
What is the difference with the standard button?

image

**Comment by rousseldenis** [comment]
> What is the difference with the standard button?
> 
> image

If you click, you go to a new model 'purchase.report' with graph/pivot views and you don't have access to purchases themselves...

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: It works and it makes sense

**Comment by rousseldenis** [comment]
Soon the little brother for Sales as Odoo did the same :smile:

**Comment by sbidoul** [comment]
`product_purchase` might be too generic as a module name?

**Comment by rousseldenis** [comment]
> `product_purchase` might be too generic as a module name?

product_purchase_link ?

**Comment by bealdav** [comment]
I ask myself if we don't need to switch from smart button to action button.
Isn't it confusing to have so many blocks in UI and so many computed fields ?

In small project no problem but in big ones ...

**Comment by rousseldenis** [comment]
> I ask myself if we don't need to switch from smart button to action button.
> Isn't it confusing to have so many blocks in UI and so many computed fields ?
> 
> In small project no problem but in big ones ...

The computed field is done once (as it appears yet in first button).

I agree that it can be bulky to use but I don't like Actions when it should be accessible quickly.

If you have a more suitable solution (In Purchase tab maybe, but it requires two clicks).

**Comment by rousseldenis** [comment]
Any idea for the name ? Suggested one is the good one ?

**Comment by bodedra** [comment]
`product_purchase_report_link` or these LGTM `product_purchase_link`

**Comment by LoisRForgeFlow** [comment]
I think product_purchase_link is good, but to be extra-specific about the functionality added you could go for `product_form_purchase_link`.

**Comment by rousseldenis** [comment]
> I think product_purchase_link is good, but to be extra-specific about the functionality added you could go for `product_form_purchase_link`.

I like that last one !

**Comment by LoisRForgeFlow** [comment]
@rousseldenis can you do the rename then? :smile:

**Comment by pedrobaeza** [comment]
I prefer `product_purchase_info`

**Review by AdriaGForgeFlow — APPROVED** [review]
> I think product_purchase_link is good, but to be extra-specific about the functionality added you could go for `product_form_purchase_link`.

Agreed :+1:

**Comment by rafaelbn** [comment]
@rousseldenis please could you please rename? Thanks!

**Comment by LoisRForgeFlow** [comment]
@rousseldenis ping, are you going to rename this?

**Comment by rousseldenis** [comment]
@rafaelbn @lreficent Done !

**Comment by legalsylvain** [comment]
Thanks @rousseldenis for this usefull module.

**Pull request merged**
