### PR TITLE
[13.0] [MIG] purchase all shipments

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Review by Saran440 — APPROVED** [review]
Functional Test :+1:

**Comment by nicomacr** [comment]
@kittiu could you review this PR?

**Comment by kittiu** [comment]
Functional tested and code reviewed, LGTM. :+1: 
(sorry for much delayed, just saw).

**Review by kittiu — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@nicomacr rebase the branch, thanks!

**Comment by nicomacr** [comment]
@HviorForgeFlow Rebase Done!

**Comment by HviorForgeFlow** [comment]
@nicolasramos try again it was fixed here https://github.com/OCA/purchase-workflow/commit/0ae782430ee4e3e4dd8cf34b1ac50a0332e7720d

**Comment by nicomacr** [comment]
@HviorForgeFlow Rebase again Done!

**Pull request merged**
