### PR TITLE
[16.0][IMP]purchase_order_type: Automatically get partner purchase type on purchase creation.

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Backport of https://github.com/OCA/purchase-workflow/pull/2396

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten could u merge it?

**Review by HaraldPanten — APPROVED** [review]
Functional review in runboat. LGTM.

Merging for fast tracking

**Comment by HaraldPanten** [comment]
> @HaraldPanten The merge process could not be finalized, because command `oca-gen-addon-readme --if-source-changed --org-name OCA --repo-name purchase-workflow --branch 16.0 --addons-dir /tmp/tmp14oq1xqc --commit` failed with output:
> 
> ```
> Both .md and .rst found for CONTRIBUTORS. Please remove one of /tmp/tmp14oq1xqc/purchase_order_type/readme/CONTRIBUTORS.rst or /tmp/tmp14oq1xqc/purchase_order_type/readme/CONTRIBUTORS.md.
> `

@ValentinVinagre you should check README/CONTRIBUTORS files

**Pull request merged**
