### PR TITLE
[14.0][ADD] purchase_report_menu_move

### PR DESCRIPTION
**Pull request by newtratip**
This module is move purchase analysis report to under Reporting menu.

### CODE REVIEW

**Comment by legalsylvain** [comment]
The name of the module is a little confusing. (looks like it adds purchase report)
Something like purchase_report_menu_move could be better in my opinion. 
Whzt do you think ?

**Comment by newtratip** [comment]
@legalsylvain, I agree with you. I will change module's name and push again.

**Comment by newtratip** [comment]
@legalsylvain, done.

**Comment by dalonsod** [comment]
Hello @newtratip tested on runbot, it seems that changes did not take effect. Could you check?

**Comment by dalonsod** [comment]
> 
> 
> Hello @newtratip tested on runbot, it seems that changes did not take effect. Could you check?

Forget it. Inspecting runbot, the addon wasn't installed :O. Then, I've manually installed it and works as expected

**Review by dalonsod — APPROVED** [review]

**Review by kittiu — APPROVED** [review]
Code review.

**Pull request merged**
