### PR TITLE
[16.0][MIG] sale_purchase_force_vendor: Migration to 16.0

### PR DESCRIPTION
**Pull request by joepsanders**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please fix CI

**Comment by joepsanders** [comment]
Fixed

**Comment by chrisb-c01** [comment]
@joepsanders pre-commit is failing because there is a redundant `import json` in `sale_purchase_force_vendor/models/sale_order_line.py`. Please remove the `import json` statement.

**Comment by joepsanders** [comment]
@pedrobaeza could you help this one forward? It should be ok now?

**Review by pedrobaeza — APPROVED** [review]

**Comment by victoralmau** [comment]
Please, cherry-pick https://github.com/OCA/purchase-workflow/pull/2091 to commit history

**Review by victoralmau — APPROVED** [review]

**Pull request merged**
