### PR TITLE
[11.0][DEL] purchase_procurement_run_buy_hook

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Unneeded hook.

- [x] Depends of https://github.com/OCA/stock-logistics-warehouse/pull/395.

### CODE REVIEW

**Review by LoisRForgeFlow — APPROVED** [review]
It's ok for me, not sure how the deleting policy works for the OCA though...

**Comment by pedrobaeza** [comment]
Please document commit putting why is not needed and in what commit is added the hook in Odoo.

**Comment by MiquelRForgeFlow** [comment]
@pedrobaeza done

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
