### PR TITLE
 [14.0][ADD] purchase_vendor_bill_product_breakdown

### PR DESCRIPTION
**Pull request by geomer198**

### CODE REVIEW

**Comment by rousseldenis** [comment]
Hi @geomer198. Thanks for this.

I have tested it. Functionally, I think you need to find a way to fill in the quantities received on Reception picking too (that fill then the quantities in PO components).

IMHO, you could split this module with a first module that defines the products supplier components. Then, the bill breakdown.

**Comment by elvise** [comment]
> IMHO, you could split this module with a first module that defines the products supplier components. Then, the bill breakdown.

@rousseldenis good point! what's the advantage?

**Comment by rousseldenis** [comment]
> > IMHO, you could split this module with a first module that defines the products supplier components. Then, the bill breakdown.
> 
> @rousseldenis good point! what's the advantage?

A better inheritance mechanism without pulling the whole big module. We could imagine another workflow that uses thoses 'breakable' products.

**Comment by geomer198** [comment]
> > > IMHO, you could split this module with a first module that defines the products supplier components. Then, the bill breakdown.
> > 
> > 
> > @rousseldenis good point! what's the advantage?
> 
> A better inheritance mechanism without pulling the whole big module. We could imagine another workflow that uses thoses 'breakable' products.

@rousseldenis Hi!) I start splitting the module. Can you do a technical review? 
First of two module: https://github.com/OCA/purchase-workflow/pull/1554

**Comment by pedrobaeza** [comment]
Isn't this similar to what is done on `product_pack` and `sale_product_pack`?

**Comment by geomer198** [comment]
> Isn't this similar to what is done on `product_pack` and `sale_product_pack`?

Module 'product_pack' uses fixed products sets.
This module uses dynamic product pack which depend on vendor. Moreover same vendor can have same products in the same document one of them is a pack and another one is not.
The primary goal of this module is to handle accounting documents not to track physical products

**Comment by pedrobaeza** [comment]
OK, I won't force any kind of convergence.

**Comment by francesco-ooops** [comment]
@geomer198 please close this one

**Pull request closed without merging**
