### PR TITLE
[FIX] purchase_partial_invoicing rst syntax errors

### PR DESCRIPTION
**Pull request by sbidoul**

### CODE REVIEW

**Comment by sbidoul** [comment]
Hm. The rst error was red so I thought it was the one breaking the lint check. But it's not.

@moylop260 do you know which one is the real error?

**Comment by pedrobaeza** [comment]
I think is this one:

```
purchase_picking_state/__openerp__.py:4: [C8101(manifest-required-author), ] Missing author required "Odoo Community Association (OCA)" in manifest file
```

**Comment by moylop260** [comment]
sorry for delay... verifying...
(Note: We need this information from MQT, errors as real errors... I'll work on this change...)

**Comment by moylop260** [comment]
I re-bulid travis and now is green

**Comment by moylop260** [comment]
Merging since that is a small RST syntax fix (without changes of logic)
Thanks

**Pull request merged**
