### PR TITLE
[16.0][ADD] purchase_stock_packaging

### PR DESCRIPTION
**Pull request by rousseldenis**

### CODE REVIEW

**Comment by rousseldenis** [comment]
@ChrisOForgeFlow 

This will fill the missing gap in Odoo core from #1672

**Review by lmignon — APPROVED** [review]
LGTM (code review)

**Review by LoisRForgeFlow — APPROVED** [review]
Thanks for taking care of this :+1:

**Comment by rousseldenis** [comment]
> Thanks for taking care of this +1

Maybe supported by Odoo in further version :smiley:

**Pull request merged**
