### PR TITLE
[14.0][MIG] purchase_order_type_dashboard

### PR DESCRIPTION
**Pull request by dalonsod**
Standard migration + two new commits:

* <ins>Added some demo data</ins>, so dashboard will show some initial numbers.
* <ins>Order type views improvements</ins>. New column and summarize in `tree` view:
  
  imagen
  
  , and new buttons within `form` view:
  
  imagen

### CODE REVIEW

**Comment by dalonsod** [comment]
@HviorForgeFlow @kittiu @SurachetS could you review?

Thanks!

PS: there's a test error that seems to be a problem with other addon, but I'm not sure. Which should be the next step to fix it?

**Comment by dalonsod** [comment]
@hparfr @rousseldenis could you review? Thanks!

**Review by HviorForgeFlow — APPROVED** [review]
Functional review! LGTM

**Review by hparfr — APPROVED** [review]

**Comment by rousseldenis** [comment]
@HviorForgeFlow Is there someone that is managing purchase_manual_currency tests corrections ?

**Comment by HviorForgeFlow** [comment]
@dalonsod ocabot can't merge it. Can you take a look on the issue on github tests? thanks

**Comment by dalonsod** [comment]
Error takes place here:

```
(odoo.addons.purchase_stock_secondary_unit.tests.test_purchase_stock_secondary_unit.TestPurchaseStockSecondaryUnit)
Traceback (most recent call last):
  File "/opt/odoo/odoo/tests/common.py", line 173, in _handleClassSetUp
    setUpClass()
  File "/__w/purchase-workflow/purchase-workflow/purchase_stock_secondary_unit/tests/test_purchase_stock_secondary_unit.py", line 42, in setUpClass
    line.secondary_uom_qty = 2.0
  File "/opt/odoo/odoo/tests/common.py", line 1880, in __exit__
    self.save()
  File "/opt/odoo/odoo/tests/common.py", line 1893, in save
    values = self._values_to_save()
  File "/opt/odoo/odoo/tests/common.py", line 1922, in _values_to_save
    changed, all_fields
  File "/opt/odoo/odoo/tests/common.py", line 1958, in _values_to_save_
    raise AssertionError("{} is a required field ({})".format(f, view['modifiers'][f]))
AssertionError: order_type is a required field ({'readonly': [('state', 'in', ['purchase', 'done', 'cancel'])], 'required': True})
```

The same error is fired linked to `purchase_manual_currency` tests. Those problems seem to be an incompatibility with `purchase_order_type` addon (the parent addon of this one), the use of `Form` in tests, `order_type` field required in view and a missing default value:

https://github.com/OCA/purchase-workflow/blob/14.0/purchase_order_type/views/view_purchase_order.xml#L3-L11

As @rousseldenis said, maybe this problem generated by `purchase_order_type` should be fixed first. Every test in this repo should fail because of this problem?

**Comment by dalonsod** [comment]
With the issue in tests described above, is there any solution that could be implemented in this PR, or should it be solved in other addon?

**Comment by dalonsod** [comment]
@HviorForgeFlow shoud I make a rebase before you try again?

**Comment by HviorForgeFlow** [comment]
@dalonsod A rebase won't fix this problem, it is required to update https://github.com/OCA/purchase-workflow/blob/14.0/.github/workflows/test.yml adding purchase_order_type_dashboard where the purchase_order_type module is defined in include or excluded key for the different test matrix.

**Comment by dalonsod** [comment]
Well, IMO current test issue is bypassed, but a new one raised, because original tests actually depend on `purchase_stock` and that isn't right. I'll take a look and try to fix them.

Anyway @HviorForgeFlow could you review if `test.yml` changes are those suggested?

**Comment by HviorForgeFlow** [comment]
> Well, IMO current test issue is bypassed, but a new one raised, because original tests actually depend on `purchase_stock` and that isn't right. I'll take a look and try to fix them.
> 
> Anyway @HviorForgeFlow could you review if `test.yml` changes are those suggested?

test.yml looks good!

Waiting test fixing! Because yes testing with pickings logic on a module that can work seamlessly without them is not a good idea

Thanks @dalonsod for your contribution

**Comment by dalonsod** [comment]
@HviorForgeFlow now tests work fine. Could you try merging again? Thanks!

**Pull request merged**
