### PR TITLE
[13.0][MIG] purchase_last_price_info

### PR DESCRIPTION
**Pull request by kongrattapong**
Standard migration

### CODE REVIEW

**Review by AdriaGForgeFlow — CHANGES_REQUESTED** [review]
I don't see the fields in the Product template view nor the Product product view.

image

**Comment by kongrattapong** [comment]
@AdriaGForgeFlow Thank for reivew, Fixed it.

Selection_008

**Review by AdriaGForgeFlow — APPROVED** [review]
Now works as expected :+1: 

Thanks!

**Review by HviorForgeFlow — APPROVED** [review]

**Pull request merged**
