### PR TITLE
[12.0][IMP] purchase_discount: Add tracking to default_supplierinfo_discount on partners

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT28073

please @sergio-teruel @carlosdauden review this.

### CODE REVIEW

**Review by cubells — APPROVED** [review]
:+1: 

LGTM

Code review and test

**Review by victoralmau — APPROVED** [review]

**Review by bodedra — APPROVED** [review]
LG :+1:

**Review by marcelsavegnago — APPROVED** [review]
LGTM

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
The tracking is not performed on children models, so it doesn't serve to put `track_visibility` in the field for seeing it on the chatter of the purchase order.

**Review by pedrobaeza — APPROVED** [review]
Sorry, I was thinking on the discount field. This is correct.

**Pull request merged**
