### PR TITLE
update travis config

### PR DESCRIPTION
**Pull request by gurneyalex**
use UNIT_TEST=1 rather than maintain a complex include/exclude configuration

### CODE REVIEW

**Comment by lepistone** [comment]
:+1:

**Comment by pedrobaeza** [comment]
I see that you are changing all Travis config to this option, but I don't think that it's convenient, because one of the most powerful things we have with this is to see incompatibilities between modules. In this way, we are isolating each one and not seeing possible conflicts. This is a bad practise and will lead to a lot of problems in environments with some of these modules.

**Comment by gurneyalex** [comment]
not all of them, only the ones I'm concerned with.

Then there are 2 kinds on incompatibilities:
- install time incompatibilities (and these are indeed not tested with the new setup), and we generally don't do much about these apart from separating the tests. 
- test time incompatibilities (tests not green for one module when another module is installed) and these are generally painfully worked around in the travis config with include / exclude rules

I find the second issue error prone and hard to maintain and I'd like to simplify the travis configurations.

**Comment by gurneyalex** [comment]
regarding install time incompatibilities, in case we decide that we don't want incompatible modules within a project, then a solution could be to have travis_run_tests to install all modules together after testing each module separately and to exit with an error in case all modules cannot be installed together. But this is an issue to create on OCA/maintainer-quality-tools

**Comment by bwrsandman** [comment]
While you're at this, please remove the .coveragerc file as it is now provided by MQT

**Comment by yvaucher** [comment]
(Need fixing added to remove .coveragerc)

**Comment by gurneyalex** [comment]
tests are red because of #22, don't merge this until this is fixed otherwise the other modules won't be tested at all.

**Comment by bwrsandman** [comment]
:+1:

**Comment by gurneyalex** [comment]
builds with this config take way to much time, and we are finding this difficult to cope with in OCA/vertical-ngo and we are reverting the change. I'm withdrawing this PR for now.

**Pull request closed without merging**
