### PR TITLE
[13.0][MIG] product_supplier_code_purchase

### PR DESCRIPTION
**Pull request by HviorForgeFlow**
Standard migration of #835 

New features:
- [x] Supplier Code is propagated to Vendor Bills.
- [x] Column displayed on PO and Vendor Bill report

CC @ForgeFlow @AaronHForgeFlow @legalsylvain

### CODE REVIEW

**Review by AaronHForgeFlow — APPROVED** [review]
:+1: Functional on runbot works as expected

**Review by AaronHForgeFlow — APPROVED** [review]
Nice improvement. It works and it is nice so :+1:

**Comment by AaronHForgeFlow** [comment]
why closing?

**Comment by HviorForgeFlow** [comment]
It is not working as expected and is incompatible with how Odoo deals product codes on purchase form.

**Pull request closed without merging**
