### PR TITLE
[14.0][ADD]purchase_work_acceptance_late_fines

### PR DESCRIPTION
**Pull request by PrapassornS**
- onchange method  returned a domain, this is deprecated

depends on
- [x] purchase_work_acceptance

### CODE REVIEW

**Comment by kittiu** [comment]
@PrapassornS since the v13 is not merged (and never be merged), I have changed name of this PR to [ADD].

**Comment by kittiu** [comment]
Can you squash all your commit into one (3 commits that you did, not include the v13 that you use to start)

**Comment by PrapassornS** [comment]
OK

**Comment by PrapassornS** [comment]
@kittiu  please review

**Comment by PrapassornS** [comment]
@kittiu  Edited commit, please review.

**Comment by SurachetS** [comment]
@kittiu 
error when creating an invoice
image

in this step, if we get active_ids from context, active_ids it's come with active_model='purchase.order'

maybe we cannot use to browse as work.acceptance

image

**Comment by kittiu** [comment]
Thanks @SurachetS, fixed! Can you try again.
https://github.com/OCA/purchase-workflow/compare/30d26003e6a24d7edb3723c650aa2410b29691d7..c9b32ec1df6bb5a4a1712b068896cb6b6c30dcee

**Comment by SurachetS** [comment]
@kittiu 
error when want to see which invoice linked with this WA
image
image

**Comment by kittiu** [comment]
Fixed!
https://github.com/OCA/purchase-workflow/compare/c9b32ec1df6bb5a4a1712b068896cb6b6c30dcee..c772f3411e944a6bc273994d7e0097a004582e9b

**Comment by SurachetS** [comment]
Functional Tested, LGTM

**Review by SurachetS — APPROVED** [review]
Functional Tested, LGTM

**Review by Saran440 — APPROVED** [review]

**Pull request merged**
