### PR TITLE
[FIX] don't change the currency

### PR DESCRIPTION
**Pull request by gurneyalex**
in the test, changing the currency of the company
is not nice and can cause other modules' test to
fail for no good reason.

Instead, make sure that the rate of the company
currency is 1.

### CODE REVIEW

**Comment by gurneyalex** [comment]
I expect this fix to get a green build for e.g.  #516 which is failing with

2018-03-14 06:27:34,645 5034 ERROR openerp_test odoo.addons.purchase_discount.tests.test_purchase_discount: `     raise UserError(_('You cannot change the currency of the company since some journal items already exist'))

**Review by max3903 — APPROVED** [review]

**Review by bodedra — APPROVED** [review]

**Review by StefanRijnhart — APPROVED** [review]
I was confused because 'not nice' is not a compelling argument in test transactions which are rolled back and this must have been green once, but I see this is a very recent change in Odoo in https://github.com/odoo/odoo/commit/0e881fcd3a5

**Comment by StefanRijnhart** [comment]
Short tracking this to fix test compatibility with Odoo.

**Comment by StefanRijnhart** [comment]
Anyone who still needs to change the company's currency in their test can do what Odoo does and make the change in SQL ;-) https://github.com/odoo/odoo/commit/6deed45

**Comment by gurneyalex** [comment]
@StefanRijnhart  sorry for the poor wording and thanks for the fast tracking :smile_cat:

**Pull request merged**
