### PR TITLE
[15.0][ADD] purchase_deposit_analytic

### PR DESCRIPTION
**Pull request by Saran440**
This module add field `analytic account` and `analytic tag` on register deposit wizard
and update it to po line and invoice lines.

Depend on:
- [x] https://github.com/OCA/purchase-workflow/pull/1773

### CODE REVIEW

**Review by Nantikan23 — APPROVED** [review]
Functional Tested

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Review by HviorForgeFlow — APPROVED** [review]
code review :+1:

**Pull request merged**
