### PR TITLE
[FIX] missing translated terms due to #245

### PR DESCRIPTION
**Pull request by JonathanNEMRY**
some missing terms into #245

### CODE REVIEW

**Comment by JonathanNEMRY** [comment]
cc @chrisdec

**Comment by sbidoul** [comment]
:+1:

**Comment by pedrobaeza** [comment]
Please remove pot file

**Comment by JonathanNEMRY** [comment]
Aren't .pot the base for transiflex files generation?

**Comment by pedrobaeza** [comment]
They are generated on the fly on the Travis build, so keeping an outdated copy only confuses contributors.

**Comment by yvaucher** [comment]
:+1: with removal of .pot

**Comment by JonathanNEMRY** [comment]
done

**Comment by JonathanNEMRY** [comment]
Thanks @yvaucher ! :smile:

**Pull request merged**
