### PR TITLE
[15.0][MIG] purchase_v12_control_menu: Migration to 15.0

### PR DESCRIPTION
**Pull request by malvaprior**
@Tecnativa TT37299

This module recovers the Purchase control menu as it was in v12. It gave two handy
accesses: 
- See pending incoming movements.
- See provider invoices.

Please review @sergio-teruel @chienandalu

### CODE REVIEW

**Review by chienandalu — CHANGES_REQUESTED** [review]
Check pre-commit

**Review by chienandalu — APPROVED** [review]
Thanks @malvaprior :+1: !

**Review by pedrobaeza — APPROVED** [review]

**Pull request merged**
