### PR TITLE
[14.0][IMP] purchase_tier_validation: Simplify the tests.

### PR DESCRIPTION
**Pull request by victoralmau**
Simplify the tests.

Please @pedrobaeza and @joao-p-marques can you review it?

@Tecnativa TT33774

### CODE REVIEW

**Comment by victoralmau** [comment]
`purchase_quick` test errors are resolved in https://github.com/OCA/purchase-workflow/pull/1325

**Review by joao-p-marques — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Travis is failing

**Comment by victoralmau** [comment]
Sorry, travis is green now.

**Review by pedrobaeza — APPROVED** [review]
You mean green :smiley:

**Pull request merged**
