### PR TITLE
[17.0] [MIG] purchase_order_line_menu

### PR DESCRIPTION
**Pull request by lawso017**
* Change version number
* Remove deprecated XML headers in HTML files
* Update maintainer tools commit hash

### CODE REVIEW

**Comment by lawso017** [comment]
@pedrobaeza thank you for your patience and excellent documentation. Tried again with a fresh PR.

**Comment by pedrobaeza** [comment]
Great, you are almost there.

/ocabot migration purchase_order_line_menu

Now someone else should review the PR:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review
https://odoo-community.org/resources/review

**Review by celm1990 — APPROVED** [review]
LGTM

**Review by MarwanBHL — APPROVED** [review]
Tested in Runboat

**Review by LoisRForgeFlow — CHANGES_REQUESTED** [review]
There has been a recent change in v16: https://github.com/OCA/purchase-workflow/pull/1971. Could you include it here?

**Comment by HviorForgeFlow** [comment]
Superseed #2378

**Pull request closed without merging**
