### PR TITLE
[13.0][ADD] purchase_order_line_packaging_qty

### PR DESCRIPTION
**Pull request by MiquelRForgeFlow**
Inspired in https://github.com/OCA/sale-workflow/pull/1114.

### CODE REVIEW

**Comment by JordiBForgeFlow** [comment]
cc @jgrandguillaume @didierdonze

**Comment by JordiBForgeFlow** [comment]
@MiquelRForgeFlow When you create a PO and enter an initial quantity and package you cannot change neither the quantity in normal units or the package quantity. It stays in the original value. Can you review?

**Comment by MiquelRForgeFlow** [comment]
@JordiBForgeFlow could you check again, please?

**Comment by jgrandguillaume** [comment]
Hi @MiquelRForgeFlow ,

Thanks for the PR. Functional test, I see that the order of fields is different from the last version we have on the sale here https://github.com/OCA/sale-workflow/pull/1114 (see attached image).

Screenshot from 2020-06-02 11-12-30

Naturally, you always prefer to 1st chose the packaging, then its quantity which update the unit quantity.

Could you adapt this ?

**Review by jgrandguillaume — CHANGES_REQUESTED** [review]
See my last comment

**Comment by MiquelRForgeFlow** [comment]
@jgrandguillaume done

**Review by grindtildeath — COMMENTED** [review]
Looks ok technically.
However, since most of the code is the same that I wrote in https://github.com/OCA/sale-workflow/pull/1114 , I feel like dropping the Camptocamp copyright and relicensing to LGPL is not right, and that authorship must be respected. :slightly_smiling_face:

**Comment by MiquelRForgeFlow** [comment]
@grindtildeath is it ok now?

**Comment by jgrandguillaume** [comment]
Hi @MiquelRForgeFlow 

Still need to move it there:

Screenshot from 2020-06-02 14-22-06

otherwie good

**Comment by MiquelRForgeFlow** [comment]
ready

**Review by grindtildeath — APPROVED** [review]

**Review by jgrandguillaume — APPROVED** [review]
LGTM now, thanks @MiquelRForgeFlow

**Pull request merged**
