### PR TITLE
[16.0][FIX][purchase_discount] discount are readonly when invoice state is fully billed

### PR DESCRIPTION
**Pull request by ernesto-garcia-tecnativa**
Forward-port of https://github.com/OCA/purchase-workflow/pull/1811

https://github.com/Tecnativa TT30233

### CODE REVIEW

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza @chienandalu  please review

**Review by pedrobaeza — APPROVED** [review]

**Review by chienandalu — APPROVED** [review]
:+1:

**Comment by ernesto-garcia-tecnativa** [comment]
@pedrobaeza please review

**Comment by pedrobaeza** [comment]
Please forward-port the same patch that has been done in 15.0 for fixing the recursion problem.

**Review by pedrobaeza — APPROVED** [review]
/ocabot merge minor

**Pull request merged**
