### PR TITLE
[10.0][FIX]account_type does was removed from analytic_account

### PR DESCRIPTION
**Pull request by AaronHForgeFlow**
Fixes this https://github.com/OCA/purchase-workflow/issues/457

### CODE REVIEW

**Review by pedrobaeza — CHANGES_REQUESTED** [review]
Please change version number according https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#version-numbers

**Comment by AaronHForgeFlow** [comment]
Version number corrected. Thanks @pedrobaeza

**Review by LoisRForgeFlow — APPROVED** [review]

**Review by pedrobaeza — APPROVED** [review]
Well, it should be 10.0.1.1.0, as it requires module update, but it's not so important

**Review by leemannd — APPROVED** [review]

**Review by karan-dreambits — APPROVED** [review]
Checked the relevant issue and this solves it  :+1:

**Pull request merged**
