### PR TITLE
[13.0] [MIG] supplier_calendar

### PR DESCRIPTION
**Pull request by NuriaXifre**
Migration of the module supplier_calendar to v13. ~ @ForgeFlow

### CODE REVIEW

**Comment by legalsylvain** [comment]
It seems that you cherry picked some undesired commits. (like changes in ``purchase_deposit``)

**Comment by bealdav** [comment]
Thanks for your contribution.
FYI there is a module https://github.com/OCA/server-tools/tree/13.0/base_time_window that could help on this topic but with a different implementation. Maybe indicate in readme to converge both in 14.0 (not mandatory)

**Comment by LoisRForgeFlow** [comment]
@bealdav I think we rather keep this module simple and stick to the use or resourece.calendar. Thanks for the tip though, it is an interesting module!

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM :+1:

**Review by HviorForgeFlow — APPROVED** [review]

**Review by AdriaGForgeFlow — APPROVED** [review]
Code review :+1:

**Comment by rousseldenis** [comment]
@LoisRForgeFlow I want to know your feedback on resource.calendar usage in particular the impact on performances as resource module used to be bulky in previous versions ? Thanks

**Comment by rousseldenis** [comment]
@bealdav I think keeping stuck to standard has advantages as it has methods to plan things for a particular date.

I will use it for delivery too as it has no way to manage leaves.

**Comment by rousseldenis** [comment]
> I will use it for delivery too as it has no way to manage leaves.

@bealdav I wanted to say : using resource.calendar :sweat_smile:

**Comment by LoisRForgeFlow** [comment]
> @LoisRForgeFlow I want to know your feedback on resource.calendar usage in particular the impact on performances as resource module used to be bulky in previous versions ? Thanks

Hi @rousseldenis 

We decided to go for resource.calendar for that particular reason, i.e. to not "reinvent the wheel" (do you have this expression in french? :laughing: ). It is obviously not a perfect fit as there is bunch of extra things in the rourserce.calendar that are not needed for the purpose but it finally did the job, it is easier to maintain and also got improved in newer versions. Regarding performance, I cannot say it is used in heavy loaded environment but on our case there are no complains for now.

My 2 cents.

Regards,

**Comment by rousseldenis** [comment]
> > @LoisRForgeFlow I want to know your feedback on resource.calendar usage in particular the impact on performances as resource module used to be bulky in previous versions ? Thanks
> 
> Hi @rousseldenis
> 
> We decided to go for resource.calendar for that particular reason, i.e. to not "reinvent the wheel" (do you have this expression in french? laughing ). It is obviously not a perfect fit as there is bunch of extra things in the rourserce.calendar that are not needed for the purpose but it finally did the job, it is easier to maintain and also got improved in newer versions. Regarding performance, I cannot say it is used in heavy loaded environment but on our case there are no complains for now.
> 
> My 2 cents.
> 
> Regards,

@LoisRForgeFlow Thanks for your answer !

**Pull request merged**
