### PR TITLE
[MIG] purchase_tier_validation: Migration to 16.0

### PR DESCRIPTION
**Pull request by imarulbala**
Depends on https://github.com/OCA/server-ux/pull/540

### CODE REVIEW

**Review by StefanRijnhart — COMMENTED** [review]
Thanks! Code reviewed, ran tests and tested manually (locally, because of unmerged dependency base_tier_validation).

**Review by StefanRijnhart — APPROVED** [review]

**Review by alan196 — APPROVED** [review]
Tested locally 👍

**Comment by StefanRijnhart** [comment]
Please add odoo_test_helper as a test requirement of the branch (like https://github.com/OCA/purchase-workflow/blob/15.0/test-requirements.txt)
```
  File "/__w/purchase-workflow/purchase-workflow/purchase_tier_validation/tests/test_tier_validation.py", line 4, in <module>
    from odoo_test_helper import FakeModelLoader
ModuleNotFoundError: No module named 'odoo_test_helper'
```

**Comment by rven** [comment]
@StefanRijnhart Done!

> Please add odoo_test_helper as a test requirement of the branch (like https://github.com/OCA/purchase-workflow/blob/15.0/test-requirements.txt)
> 
> ```
>   File "/__w/purchase-workflow/purchase-workflow/purchase_tier_validation/tests/test_tier_validation.py", line 4, in <module>
>     from odoo_test_helper import FakeModelLoader
> ModuleNotFoundError: No module named 'odoo_test_helper'
> ```

**Comment by yankinmax** [comment]
@StefanRijnhart can we merge this PR?

**Pull request merged**
