### PR TITLE
[ADD] procurement_group_purchase_orders

### PR DESCRIPTION
**Pull request by JordiBForgeFlow**
This module is a backport from version 8.0 to 7.0 of the purchase order
creation from procurement orders. At the time of running the scheduler the
application will search for an existing PO in draft state for the same
supplier and with the same destination location. If found, it will extend
the PO to include the new product and quantity to be procured.

The main difference with version 8.0 is that the application will not
attempt to increase the quantity of a line for an existing PO, because each
line in a PO is associated in 7.0 to the procurement's stock move.

Regards,
Jordi.

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi Jordi,

Thanks for this contrib, once more this is a very welcome one. Everything looks good to me except :
- As you override the make_po method completely (not calling super()), I would make a note about this in the description of the module because then other modules that inherit this method may be lost.
- It would be good to also have a warning about this in the code's comments

Otherwise :+1: for me

Regards,

**Comment by JordiBForgeFlow** [comment]
Thanks for your review @jgrandguillaume! I just submitted a new commit incorporating your review comments.
Unfortunately I found no way around, other than overriding 'make_po' completely.

Regards,

**Comment by gurneyalex** [comment]
@jbeficent could you fix the flake8 issues?

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
./procurement_group_purchase_orders/model/purchase.py:24:1: F401 'DATETIME_FORMATS_MAP' imported but unused
./procurement_group_purchase_orders/model/purchase.py:27:1: F401 'workflow' imported but unused
./procurement_group_purchase_orders/model/purchase.py:88:25: E225 missing whitespace around operator

**Comment by JordiBForgeFlow** [comment]
I fixed the flake8 errors, but Travis is still in error. I don't understand why.

Thanks!
Jordi.

**Comment by jgrandguillaume** [comment]
@gurneyalex Any hint about the test failing here ?

**Comment by gurneyalex** [comment]
@jbeficent sorry for the late answer Lots of things have changed in the project CI configuration. Could you rebase the PR on top of the current 7.0 branch?

**Comment by pedrobaeza** [comment]
@jbeficent Can you also remove the plural from the module name?

**Comment by vrenaville** [comment]
:+1:

**Comment by pedrobaeza** [comment]
This one is very old and with red status, so I'm closing. Feel free to reopen if still needed.

**Pull request closed without merging**
