### PR TITLE
[14.0][FIX] purchase_location_by_line : Too many receipts are created

### PR DESCRIPTION
**Pull request by mmarcot**
This PR aims to fix issue #1094

### CODE REVIEW

**Review by HviorForgeFlow — APPROVED** [review]

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Rebase your branch with OCA/14.0 to avoid this kind of merge commits.
```
git fetch origin 14.0
git rebase origin/14.0
```

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by mmarcot** [comment]
Thank you @HviorForgeFlow 

Hope it will be good now

**Review by AaronHForgeFlow — APPROVED** [review]
:+1:  LGTM

**Review by LoisRForgeFlow — APPROVED** [review]
LGTM

**Comment by mmarcot** [comment]
@HviorForgeFlow 
I missed the conflict resolution
Please have a look at commit b83a6f7, otherwise the fix will not work

**Comment by HviorForgeFlow** [comment]
squash both commits  @mmarcot

**Comment by mmarcot** [comment]
> squash both commits @mmarcot

done

**Pull request merged**
