### PR TITLE
[15.0][MIG] purchase_partner_incoterm: Migration to version 15.0

### PR DESCRIPTION
**Pull request by vvrossem**
standard migration

- followed OCA's ["Migration to version 15.0"](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0) guidelines
- functionally tested on odoo 15.0 (CE)

### CODE REVIEW

**Comment by vvrossem** [comment]
@TDu would you be interested to review your module? :)

**Comment by vvrossem** [comment]
Hi @ReedHayashikawa, @HaraldPanten , @atchuthan , could you please review this PR ? it's quite similar to https://github.com/OCA/sale-workflow/pull/1955

**Review by HaraldPanten — APPROVED** [review]
Functional review. LGTM 👍

**Comment by vvrossem** [comment]
closing as https://github.com/OCA/purchase-workflow/pull/1571 was merged

**Pull request closed without merging**
