### PR TITLE
[MIG]purchase_request_department: Migration to 16.0

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Review by florenciafrigieri2 — APPROVED** [review]
Functional review. Field department is working correctly withing the purchase request.

**Comment by florenciafrigieri2** [comment]
@HviorForgeFlow Hello Hi Héctor, can you please check this PR to migrate the module to version 16? So we can start the migration to version 17. Thanks in advance!

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Please preserve commit history, thanks.

**Comment by mav-adhoc** [comment]
@HviorForgeFlow I didn't understood what you mean with preserve the commit history. Did i lost the history of the commit?

**Comment by HviorForgeFlow** [comment]
There is only one commit which reflect the addition of the module in v16, but this is tricky, because this module was available on previous versions so you need to keep the history of commits from the beginning following the OCA migration guidelines:

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0#technical-method-to-migrate-a-module-from-150-to-160-branch

@mav-adhoc

Remember fetching the origin of version from you are migrating and version to you migrate and if version is not the previous one you need to adjust the git format-patch command

**Comment by mav-adhoc** [comment]
@HviorForgeFlow Thanks! BTW, you know how can i fix the errors in the failed tests? I see tests are failing in purchase_request module, which is a dependency of this module, but none of the purchase_request_department tests are failing.

**Comment by HviorForgeFlow** [comment]
@mav-adhoc try rebasing your branch with the last commit of v16.

`git pull origin 16.0 --rebase` then push force

**Comment by mav-adhoc** [comment]
@HviorForgeFlow We continue on this PR! https://github.com/OCA/purchase-workflow/pull/2373

**Pull request closed without merging**
