### PR TITLE
[14.0][IMP] purchase_order_partner_manual_rank: filter vendor pricelists

### PR DESCRIPTION
**Pull request by HekkiMelody**
Adds the same filter to vendor pricelists.

Also adds maintainers.

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional ok!

**Review by geomer198 — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@pedrobaeza I know it's not 5 days yet, but it's quite straightforward and we've added maintainership too :)

**Review by pedrobaeza — APPROVED** [review]
Yes, it seems coherent with the feature of the module.

/ocabot merge major

**Pull request merged**
