### PR TITLE
[18.0][MIG] purchase_request_department: Migration to 18.0

### PR DESCRIPTION
**Pull request by lef-adhoc**
I migrated the module through this pr #2455

### CODE REVIEW

**Review by mav-adhoc — APPROVED** [review]

**Review by ced-adhoc — APPROVED** [review]

**Comment by ced-adhoc** [comment]
LGTM

**Comment by mav-adhoc** [comment]
LGTM

**Review by luc-adhoc — APPROVED** [review]
functional review

**Review by HviorForgeFlow — COMMENTED** [review]
/ocabot merge nobump

**Pull request merged**
