### PR TITLE
[15.0][MIG] purchase_work_acceptance_invoice_plan

### PR DESCRIPTION
**Pull request by Saran440**
Standard Migrated

Depend on:
- [x] https://github.com/OCA/purchase-workflow/pull/1596

### CODE REVIEW

**Comment by PatthamaCH** [comment]
@Saran440 field Amount Invoiced in Invoice Plan Tab not show when bill posted.

**Comment by Saran440** [comment]
@PatthamaCH Fixed, Thank you for your review. Copy code from https://github.com/OCA/purchase-workflow/pull/1212#issuecomment-1126634023

**Review by PatthamaCH — APPROVED** [review]
OK ka.

**Review by PatthamaCH — APPROVED** [review]
OK

**Review by Nantikan23 — APPROVED** [review]
OK - Functional test

**Pull request merged**
