### PR TITLE
14.0[FIX] purchase_order_vendor_product

### PR DESCRIPTION
**Pull request by ivs-cetmix**
Current behavior 
- In PO lines all product variants are available even if there is a product varian selected in the Supplierinfo line

Intended behavior after this fix
- If there a product varian is set in the Supplierinfo line only this variant will be available
- If there is no product variant selected all variants are available

### CODE REVIEW

**Review by francesco-ooops — APPROVED** [review]
Functional review ok!

**Review by elvise — APPROVED** [review]
LGTM!

**Comment by francesco-ooops** [comment]
@OCA/procurement-purchase-maintainers can you please review this fix?

**Review by HviorForgeFlow — APPROVED** [review]
Code review :+1:

**Pull request merged**
