### PR TITLE
[15.0][FIX] purchase_order_approved: missing name for approved orders report

### PR DESCRIPTION
**Pull request by dalonsod**
For _Purchase Order_ report, order name was missing when PO was in `approved` state.

cc @lmignon @rousseldenis @moaadbourhim

### CODE REVIEW

**Review by lmignon — APPROVED** [review]
Code review only

**Comment by dalonsod** [comment]
@DavidJForgeFlow @EmilioPascual could you review? Thanks!

**Review by DavidJForgeFlow — APPROVED** [review]
LGTM!

**Comment by dalonsod** [comment]
@pedrobaeza could you merge it? Thanks!

**Pull request merged**
