### PR TITLE
[16.0][MIG] purchase_location_by_line: Migration to 16.0

### PR DESCRIPTION
**Pull request by FernandoRomera**

### CODE REVIEW

**Comment by FernandoRomera** [comment]
#1585

**Comment by FernandoRomera** [comment]
depends #1687

**Review by AntoniRomera — APPROVED** [review]

**Comment by HaraldPanten** [comment]
@FernandoRomera will you continue with this PR? THX

**Comment by HaraldPanten** [comment]
@pedrobaeza Could you close this one? It's not being continued so we superseded.

**Pull request closed without merging**
