### PR TITLE
[MIG] Migrated purchase_analytic_global to v13.

### PR DESCRIPTION
**Pull request by sudhir-erpharbor**

### CODE REVIEW

**Comment by HviorForgeFlow** [comment]
@sudhir-erpharbor could you follow the [guidelines](https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0) and split in 2 commits pre-commit and migration even if migration is just version number change.

If you want to be contributor you should do some improvements in code, for example, this module would need some test to ensure portability to next versions.

**Review by HviorForgeFlow — COMMENTED** [review]
LGTM :+1: 
Functional review

Please squash last 2 commits into the third

**Comment by sudhir-erpharbor** [comment]
> Please squash last 2 commits into the third

Done :thumbsup:

**Review by misern2 — COMMENTED** [review]
LGTM :+1: 
Please squash the last 2 commits.

**Comment by sudhir-erpharbor** [comment]
> LGTM +1
> Please squash the last 2 commits.

Done :+1:

**Review by misern2 — APPROVED** [review]

**Comment by AaronHForgeFlow** [comment]
I tested and works as expected.

FYI, I noticed that this module does exactly the same as https://github.com/OCA/account-analytic/tree/12.0/purchase_analytic

Basically, both modules do the same thing. Any of those two should be not continued in any case. From my point of view it is ok to continue with this one and not to port the other one.

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@sudhir-erpharbor please rebase the branch with current 13.0 and let's see

**Comment by sudhir-erpharbor** [comment]
> @sudhir-erpharbor please rebase the branch with current 13.0 and let's see

Done. Let's wait and watch if this helps.

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
:green_apple: please

**Review by ivantodorovich — APPROVED** [review]
LG but travis is red

**Review by HviorForgeFlow — APPROVED** [review]

**Comment by HviorForgeFlow** [comment]
@sudhir-erpharbor pre-commit needs to be run with a proper rebase earlier

**Pull request closed without merging**
