### PR TITLE
[14.0][IMP] purchase_request : show only the same uom category of product_id

### PR DESCRIPTION
**Pull request by hitrosol**
Show only the same uom category of product_id

### CODE REVIEW

**Review by kittiu — APPROVED** [review]

**Review by hitrosol — COMMENTED** [review]
I'm not sure why there is error that's not related to this module

**Comment by hitrosol** [comment]
@rousseldenis, thanks for your UPD in the Github Action.
Would you please review this PR and merge if it's okay ?

**Review by rousseldenis — APPROVED** [review]
LGTM

**Comment by rousseldenis** [comment]
> @rousseldenis, thanks for your UPD in the Github Action. Would you please review this PR and merge if it's okay ?

Don't have superpowers here. But @kittiu does

**Comment by hitrosol** [comment]
@kittiu would you please merge this ?
I see https://github.com/OCA/purchase-workflow/pull/1507 is also similar with this but for v 13.

**Review by HviorForgeFlow — CHANGES_REQUESTED** [review]
Add only the required commits and keep changes as clean as possible. Thanks!

**Comment by hitrosol** [comment]
already have alternatif PR

**Pull request closed without merging**
