### PR TITLE
[15.0][MIG/ENH] purchase_manual_currency : allow select inverse company_rate

### PR DESCRIPTION
**Pull request by Saran440**
In version15 currency has 2 rate
Selection_013

So, This pr enhance module `purchase_manual_currency` to support this case. Users can select type currency for keep rate with user need (Main to Currency or Currency to Main).
Selection_022

This PR continue with https://github.com/OCA/purchase-workflow/pull/1717 from @bizzappdev
Do you want to cherry-pick commit 086b0860e62bb4fcdcbe0b579d9c6ad03f5064f3 to your PR?
if not please close your PR and move to review this PR instead

Thank you.

Depend:
- [x] account_manual_currency - https://github.com/OCA/account-invoicing/pull/1486

### CODE REVIEW

**Review by navarrorico — APPROVED** [review]
Functional review :+1:

**Review by ps-tubtim — APPROVED** [review]
LGTM

**Comment by Saran440** [comment]
This PR is enhanced for send manual currency from Purchase to Bills
So it will depend on https://github.com/OCA/account-invoicing/pull/1486

**Comment by newtratip** [comment]
@Saran440 Some checks were failing, could you check it please ?

**Review by cmcreamm — COMMENTED** [review]
In my opinion for functional user the word of "Unit" should change to "Currency" to reduce user confusing. Moreover, I suggest that the sentence will be more clarify if we change it to " Currency per (main currency)" for example, 0.5 currency per 1 THB and 25 THB per 1 currency.
Could you please check if this suggestion has a chance to be possible?

**Comment by Saran440** [comment]
@newtratip @cmcreamm Fixed. Thank you for reviewed.

- Change name `custom_rate` to `manual_currency_rate`
- Change label to currency
Selection_021

**Pull request merged**
