### PR TITLE
[14.0][MIG] - purchase_order_line_invoicing

### PR DESCRIPTION
**Pull request by sbejaoui**
FW #319

### CODE REVIEW

**Comment by sbejaoui** [comment]
cc/ @rousseldenis

**Review by rousseldenis — APPROVED** [review]
Code review

**Comment by kittiu** [comment]
Function test, I found this,

1. Open partner "Ready Mat", and open purchase lines.
2. Select multiple purchase lines and create Invoice
3. Invoice created, but it direct me to all invoices. (I would expect to see only one invoice, the top one line, that I just create, right?).

image

**Comment by rousseldenis** [comment]
> Function test, I found this,
> 
> 1. Open partner "Ready Mat", and open purchase lines.
> 2. Select multiple purchase lines and create Invoice
> 3. Invoice created, but it direct me to all invoices. (I would expect to see only one invoice, the top one line, that I just create, right?).
> 
> image

@xavier-bouquiaux Do your last changes fix that ?

**Comment by xavier-bouquiaux** [comment]
> > Function test, I found this,
> > 
> > 1. Open partner "Ready Mat", and open purchase lines.
> > 2. Select multiple purchase lines and create Invoice
> > 3. Invoice created, but it direct me to all invoices. (I would expect to see only one invoice, the top one line, that I just create, right?).
> > 
> > image
> 
> @xavier-bouquiaux Do your last changes fix that ?

I made 2 commit on this PR and the last one solve this issue indeed <br/>
Now after the wizard finished it opens the draft created

**Comment by rousseldenis** [comment]
> > > Function test, I found this,
> > > 
> > > 1. Open partner "Ready Mat", and open purchase lines.
> > > 2. Select multiple purchase lines and create Invoice
> > > 3. Invoice created, but it direct me to all invoices. (I would expect to see only one invoice, the top one line, that I just create, right?).
> > > 
> > > image
> > 
> > 
> > @xavier-bouquiaux Do your last changes fix that ?
> 
> I made 2 commit on this PR and the last one solve this issue indeed Now after the wizard finished it opens the draft created

Great!

@kittiu Could you update your review ?

**Review by kittiu — APPROVED** [review]
Good thank you!

**Pull request merged**
