### PR TITLE
8.0 Fixes for Comparative bid analysis (bid selection)

### PR DESCRIPTION
**Pull request by yvaucher**
- store computed values in company currency to make them orderable
- store related incoterm to make it groupable
- add separators between filters to add them as AND conditions
- add a help text on wizard which had no label and no instructions
- add missing POT file

### CODE REVIEW

**Comment by lepistone** [comment]
thanks :+1:

**Comment by gurneyalex** [comment]
:+1: any idea why the runbot was red?

**Comment by gurneyalex** [comment]
amended head to force rebuild

**Comment by yvaucher** [comment]
Runbot logs

```
2015-03-25 07:51:00,473 1205 WARNING 2925725-112-3ea807-all openerp.models.schema: Table 'purchase_requisition': unable to set a NOT NULL constraint on column 'pricelist_id' !
If you want to have it, you should update the records and execute manually:
```

**Comment by mdietrichc2c** [comment]
:+1:

**Pull request merged**
