### PR TITLE
[ENH] purchase_requisition_bid_selection - add comparative bid analysis report

### PR DESCRIPTION
**Pull request by yvaucher**
depends on
- [x] https://github.com/OCA/purchase-workflow/pull/109

reverse dependency (possibly merge at the same time):
- [x] OCA/vertical-ngo#149

Fixes https://github.com/OCA/purchase-workflow/issues/79

### CODE REVIEW

**Comment by jgrandguillaume** [comment]
Hi,

@yvaucher Please make a git amend + commit

Otherwise, I've tested the report, it is just AWESOME ! Thanks a lot for this contrib. :+1: if runbot green

Regards,

Joël

**Comment by gurneyalex** [comment]
@jgrandguillaume done (cc @yvaucher)

**Comment by gurneyalex** [comment]
weird errors in the runbot build :astonished: 

```
INFO 2925710-111-4a5cb7-all openerp.modules.loading: loading board/views/board.xml
Exception RuntimeError: 'maximum recursion depth exceeded' in <function _remove at 0x36d71b8> ignored
[...]
ERROR 2925710-111-4a5cb7-all openerp.sql_db: bad query: ALTER TABLE "purchase_requisition" ALTER COLUMN "pricelist_id" SET NOT NULL
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2925710-111-4a5cb7/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "pricelist_id" contains null values
```

**Comment by yvaucher** [comment]
rebased

**Comment by lepistone** [comment]
Thanks :+1:

**Comment by lepistone** [comment]
I am amending the last commit to see if runbot gets green.

**Comment by gurneyalex** [comment]
error in the runbot logs:

```
INFO 2925858-111-775225-all openerp.modules.module: module purchase_requisition_multicurrency: creating or updating database tables
ERROR 2925858-111-775225-all openerp.sql_db: bad query: ALTER TABLE "purchase_requisition" ALTER COLUMN "pricelist_id" SET NOT NULL
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2925858-111-775225/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "pricelist_id" contains null values

WARNING 2925858-111-775225-all openerp.models: WARNING: unable to set column pricelist_id of table purchase_requisition not null !
Try to re-run: openerp-server --update=module
If it doesn't work, update records and execute manually:
ALTER TABLE purchase_requisition ALTER COLUMN pricelist_id SET NOT NULL
Traceback (most recent call last):
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2925858-111-775225/openerp/models.py", line 2643, in _auto_init
    cr.execute('ALTER TABLE "%s" ALTER COLUMN "%s" SET NOT NULL' % (self._table, k))
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2925858-111-775225/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/srv/openerp/instances/openerp-oca-runbot/parts/odoo-extra/runbot/static/build/2925858-111-775225/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
IntegrityError: column "pricelist_id" contains null values
```

**Comment by lepistone** [comment]
@gurneyalex on travis we split module installation. Do we do the same on runbot?

**Comment by lepistone** [comment]
I think the runbot problem is unrelated, and fixed by #118.

**Comment by lepistone** [comment]
So this PR adds a dependency on `purchase_requisition_bid_selection` towards `purchase_requisition_multicurrency` so the YAML tests of the first need to take into account the required field introduced (now for real) in the latter. I'm fixing this.

**Comment by gurneyalex** [comment]
:+1: :fireworks:

**Comment by lepistone** [comment]
This is good. I started a temporary build on OCA/vertical-ngo#149 so we can merge the two together.

**Comment by jgrandguillaume** [comment]
:+1:

**Pull request merged**
